import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { after, before, describe, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";
import {
  AgencyInvitationError,
  runAgencyInvitationAction,
} from "../supabase/functions/_shared/agencyInvitationCore.mjs";

const COMPANY_A = "10000000-0000-4000-8000-000000000001";
const COMPANY_B = "10000000-0000-4000-8000-000000000002";
const RM_A = "20000000-0000-4000-8000-000000000001";
const ADMIN_A = "20000000-0000-4000-8000-000000000002";
const OFFICER_A = "20000000-0000-4000-8000-000000000003";
const ADMIN_B = "20000000-0000-4000-8000-000000000004";
const AGENCIES = Array.from(
  { length: 8 },
  (_, index) =>
    `30000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`
);
const AGENCY_B = "30000000-0000-4000-8000-000000000100";

const fixtureSql = `
create schema auth;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table auth.users (
  id uuid primary key,
  email text not null,
  raw_user_meta_data jsonb not null default '{}'::jsonb
);

create table public.companies (
  id uuid primary key,
  name text not null,
  status text not null
);

create table public.agencies (
  id uuid primary key,
  created_at timestamptz not null default now(),
  name text not null,
  country text,
  contact_person text,
  email text,
  phone text,
  status text not null,
  company_id uuid,
  updated_at timestamptz not null default now()
);

create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  company_id uuid,
  agency_id uuid,
  agency_name text,
  name text,
  email text,
  role text not null,
  status text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.company_agency_access (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  agency_id uuid not null,
  status text not null default 'Active',
  can_view_requests boolean not null default true,
  can_upload_candidates boolean not null default true,
  can_update_candidates boolean not null default true,
  can_view_interviews boolean not null default true,
  unique (company_id, agency_id)
);

create table public.agency_company_user_access (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  agency_id uuid not null,
  user_id bigint not null,
  role text not null default 'Agency User',
  status text not null default 'Invitation Sent',
  can_view_requests boolean not null default true,
  can_upload_candidates boolean not null default true,
  can_update_candidates boolean not null default true,
  can_view_interviews boolean not null default true,
  unique (company_id, agency_id, user_id)
);

create table public.agency_provisioning_requests (
  id uuid primary key default gen_random_uuid(),
  idempotency_key uuid not null,
  company_id uuid not null,
  agency_id uuid,
  requested_by_user_id bigint not null,
  requested_by_auth_user_id uuid not null,
  agency_name text not null,
  country text,
  contact_person text,
  admin_email text not null,
  phone text,
  permissions jsonb not null default '{}'::jsonb,
  send_invitation boolean not null default true,
  status text not null default 'Draft',
  auth_user_id uuid,
  public_user_id bigint,
  attempt_count integer not null default 0,
  failure_code text,
  failure_metadata jsonb not null default '{}'::jsonb,
  invitation_sent_at timestamptz,
  activated_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, idempotency_key)
);

create unique index agency_provisioning_active_email_unique
on public.agency_provisioning_requests (
  company_id,
  lower(btrim(admin_email))
)
where status in ('Draft', 'Provisioning', 'Invitation Sent');

create table public.agency_provisioning_events (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null,
  event_key text not null,
  company_id uuid not null,
  agency_id uuid,
  actor_user_id bigint,
  actor_auth_user_id uuid,
  event_type text not null,
  from_status text,
  to_status text,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (request_id, event_key)
);

create table public.system_activity_logs (
  id bigint generated by default as identity primary key,
  company_id uuid,
  module_name text,
  record_id text,
  action_type text,
  action_title text,
  changed_by_user_id bigint,
  changed_by_role text,
  notes text,
  source text,
  created_at timestamptz not null default now()
);

create function public.agency_provisioning_public_result(
  request_row public.agency_provisioning_requests
)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select pg_catalog.jsonb_build_object(
    'id', request_row.id,
    'agency_id', request_row.agency_id,
    'agency_name', request_row.agency_name,
    'admin_email', request_row.admin_email,
    'status', request_row.status,
    'auth_user_id', request_row.auth_user_id,
    'public_user_id', request_row.public_user_id,
    'attempt_count', request_row.attempt_count,
    'failure_code', request_row.failure_code,
    'invitation_sent_at', request_row.invitation_sent_at,
    'activated_at', request_row.activated_at,
    'updated_at', request_row.updated_at
  )
$$;

grant usage on schema public, auth to authenticated, service_role;
grant execute on function auth.uid() to authenticated;
grant select on table public.agencies, public.company_agency_access,
  public.agency_company_user_access, public.agency_provisioning_requests,
  public.agency_provisioning_events to authenticated;

-- Deliberately broad fixture grants prove that the migration re-revokes them.
grant insert, update, delete on table public.users,
  public.agency_company_user_access,
  public.agency_provisioning_requests,
  public.agency_provisioning_events to authenticated;

alter table public.agency_company_user_access enable row level security;
create function public.current_test_user_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select app_user.id
  from public.users as app_user
  where app_user.auth_user_id = auth.uid()
$$;
revoke all on function public.current_test_user_id()
  from public, anon, authenticated;
grant execute on function public.current_test_user_id()
  to authenticated;
create policy agency_user_own_access
on public.agency_company_user_access
for select to authenticated
using (
  user_id = public.current_test_user_id()
  and status = 'Active'
);
`;

let db;
let inviteSequence = 0;

async function setActor(authUserId) {
  await db.exec("reset role");
  await db.query(
    "select set_config('request.jwt.claim.sub', $1::text, false)",
    [authUserId]
  );
}

async function asAuthenticated(authUserId, callback) {
  await setActor(authUserId);
  await db.exec("set role authenticated");
  try {
    return await callback();
  } finally {
    await db.exec("reset role");
  }
}

async function asService(callback) {
  await db.exec("reset role");
  await db.exec("set role service_role");
  try {
    return await callback();
  } finally {
    await db.exec("reset role");
  }
}

function actor(authUserId, role, companyId = COMPANY_A) {
  return {
    authUserId,
    userId: 1,
    companyId,
    role,
    isActive: true,
  };
}

function repositoryFor(authUserId) {
  return {
    begin: ({ agencyId }) =>
      asAuthenticated(authUserId, async () => {
        const result = await db.query(
          "select public.agency_invitation_begin($1::uuid) as result",
          [agencyId]
        );
        return result.rows[0].result;
      }),
    recordAuthUser: ({ actorAuthUserId, requestId, authUserId }) =>
      asService(async () => {
        const result = await db.query(
          `select public.agency_invitation_record_auth_user(
             $1::uuid, $2::uuid, $3::uuid
           ) as result`,
          [actorAuthUserId, requestId, authUserId]
        );
        return result.rows[0].result;
      }),
    complete: ({ actorAuthUserId, requestId, authUserId }) =>
      asService(async () => {
        const result = await db.query(
          `select public.agency_invitation_complete(
             $1::uuid, $2::uuid, $3::uuid
           ) as result`,
          [actorAuthUserId, requestId, authUserId]
        );
        return result.rows[0].result;
      }),
    markFailed: ({ actorAuthUserId, requestId, code }) =>
      asService(async () => {
        const result = await db.query(
          `select public.agency_invitation_mark_failed(
             $1::uuid, $2::uuid, $3::text
           ) as result`,
          [actorAuthUserId, requestId, code]
        );
        return result.rows[0].result;
      }),
    activate: () =>
      asAuthenticated(authUserId, async () => {
        const result = await db.query(
          "select public.agency_invitation_activate() as result"
        );
        return result.rows[0].result;
      }),
  };
}

function authAdmin({ fail = false } = {}) {
  const state = { calls: 0, lastAuthUserId: null };
  return {
    state,
    api: {
      async inviteUserByEmail(email, options) {
        state.calls += 1;
        if (fail) {
          return {
            data: null,
            error: Object.assign(new Error("mail provider failed"), {
              code: "unexpected_failure",
            }),
          };
        }
        inviteSequence += 1;
        const authUserId =
          `40000000-0000-4000-8000-${String(inviteSequence).padStart(12, "0")}`;
        state.lastAuthUserId = authUserId;
        await db.query(
          `insert into auth.users (id, email, raw_user_meta_data)
           values ($1::uuid, $2::text, $3::jsonb)`,
          [authUserId, email, JSON.stringify(options.data)]
        );
        return {
          data: { user: { id: authUserId, email } },
          error: null,
        };
      },
    },
  };
}

async function invite({
  authUserId,
  role,
  agencyId,
  companyId = COMPANY_A,
  fail = false,
}) {
  const auth = authAdmin({ fail });
  const result = await runAgencyInvitationAction({
    body: { action: "invite_existing", agency_id: agencyId },
    actor: actor(authUserId, role, companyId),
    repository: repositoryFor(authUserId),
    authAdmin: auth.api,
    inviteRedirectUrl: "https://preview.example.test/agency-invite",
  });
  return { result, auth };
}

describe("existing agency invitation flow on temporary PostgreSQL", () => {
  before(async () => {
    db = new PGlite();
    const migration = await readFile(
      new URL(
        "../supabase/migrations/20260730000200_add_existing_agency_invitation_flow.sql",
        import.meta.url
      ),
      "utf8"
    );
    await db.exec(fixtureSql);

    await db.exec(`
      insert into public.companies (id, name, status) values
        ('${COMPANY_A}', 'Company A', 'Active'),
        ('${COMPANY_B}', 'Company B', 'Active');

      insert into auth.users (id, email) values
        ('${RM_A}', 'rm-a@example.test'),
        ('${ADMIN_A}', 'admin-a@example.test'),
        ('${OFFICER_A}', 'officer-a@example.test'),
        ('${ADMIN_B}', 'admin-b@example.test');

      insert into public.users (
        auth_user_id, company_id, name, email, role, status, is_active
      ) values
        ('${RM_A}', '${COMPANY_A}', 'RM A', 'rm-a@example.test', 'Recruitment Manager', 'Active', true),
        ('${ADMIN_A}', '${COMPANY_A}', 'Admin A', 'admin-a@example.test', 'Company Admin', 'Active', true),
        ('${OFFICER_A}', '${COMPANY_A}', 'Officer A', 'officer-a@example.test', 'Recruitment Officer', 'Active', true),
        ('${ADMIN_B}', '${COMPANY_B}', 'Admin B', 'admin-b@example.test', 'Company Admin', 'Active', true);
    `);

    for (let index = 0; index < AGENCIES.length; index += 1) {
      await db.query(
        `insert into public.agencies (
           id, name, email, country, status
         ) values ($1::uuid, $2::text, $3::text, 'India', 'Active')`,
        [
          AGENCIES[index],
          `Agency ${index + 1}`,
          `agency-${index + 1}@example.test`,
        ]
      );
      await db.query(
        `insert into public.company_agency_access (
           company_id, agency_id, status
         ) values ($1::uuid, $2::uuid, 'Active')`,
        [COMPANY_A, AGENCIES[index]]
      );
    }
    await db.exec(`
      insert into public.agencies (
        id, name, email, country, status
      ) values (
        '${AGENCY_B}', 'Agency B', 'agency-b@example.test', 'India', 'Active'
      );
      insert into public.company_agency_access (
        company_id, agency_id, status
      ) values ('${COMPANY_B}', '${AGENCY_B}', 'Active');
    `);

    await db.exec(migration);
  });

  after(async () => {
    await db?.close();
  });

  test("Recruitment Manager sends an invitation", async () => {
    const { result } = await invite({
      authUserId: RM_A,
      role: "Recruitment Manager",
      agencyId: AGENCIES[0],
    });
    assert.equal(result.request.status, "Invitation Sent");
    assert.equal(result.request.agency_id, AGENCIES[0]);
  });

  test("Company Admin sends an invitation", async () => {
    const { result } = await invite({
      authUserId: ADMIN_A,
      role: "Company Admin",
      agencyId: AGENCIES[1],
    });
    assert.equal(result.request.status, "Invitation Sent");
  });

  test("an unauthorized user is rejected by core and PostgreSQL", async () => {
    await assert.rejects(
      invite({
        authUserId: OFFICER_A,
        role: "Recruitment Officer",
        agencyId: AGENCIES[2],
      }),
      (error) =>
        error instanceof AgencyInvitationError &&
        error.code === "AGENCY_INVITATION_UNAUTHORIZED"
    );
    await assert.rejects(
      asAuthenticated(OFFICER_A, () =>
        db.query(
          "select public.agency_invitation_begin($1::uuid)",
          [AGENCIES[2]]
        )
      ),
      /AGENCY_INVITATION_UNAUTHORIZED/
    );
  });

  test("an agency linked to another company is rejected", async () => {
    await assert.rejects(
      invite({
        authUserId: RM_A,
        role: "Recruitment Manager",
        agencyId: AGENCY_B,
      }),
      /AGENCY_INVITATION_AGENCY_NOT_AVAILABLE/
    );
    const count = await db.query(
      `select count(*)::integer as count
       from public.agency_provisioning_requests
       where agency_id = $1::uuid`,
      [AGENCY_B]
    );
    assert.equal(count.rows[0].count, 0);
  });

  test("a sent invitation cannot be duplicated", async () => {
    const first = await invite({
      authUserId: RM_A,
      role: "Recruitment Manager",
      agencyId: AGENCIES[3],
    });
    await assert.rejects(
      invite({
        authUserId: RM_A,
        role: "Recruitment Manager",
        agencyId: AGENCIES[3],
      }),
      (error) =>
        error instanceof AgencyInvitationError &&
        error.code === "AGENCY_INVITATION_ALREADY_SENT"
    );
    assert.equal(first.auth.state.calls, 1);
    const count = await db.query(
      `select count(*)::integer as count
       from public.agency_provisioning_requests
       where agency_id = $1::uuid`,
      [AGENCIES[3]]
    );
    assert.equal(count.rows[0].count, 1);
  });

  test("the public user and access use the trusted agency and company", async () => {
    const { result } = await invite({
      authUserId: ADMIN_A,
      role: "Company Admin",
      agencyId: AGENCIES[4],
    });
    const rows = await db.query(
      `select app_user.role as user_role,
              app_user.company_id,
              app_user.agency_id,
              access.company_id as access_company_id,
              access.agency_id as access_agency_id,
              access.role as access_role,
              access.status
       from public.users as app_user
       join public.agency_company_user_access as access
         on access.user_id = app_user.id
       where app_user.id = $1::bigint`,
      [result.request.public_user_id]
    );
    assert.deepEqual(rows.rows[0], {
      user_role: "Agency",
      company_id: null,
      agency_id: AGENCIES[4],
      access_company_id: COMPANY_A,
      access_agency_id: AGENCIES[4],
      access_role: "Agency User",
      status: "Invitation Sent",
    });
  });

  test("an agency user receives no access to another company", async () => {
    const { result, auth } = await invite({
      authUserId: RM_A,
      role: "Recruitment Manager",
      agencyId: AGENCIES[5],
    });
    const activated = await runAgencyInvitationAction({
      body: { action: "activate" },
      actor: { authUserId: auth.state.lastAuthUserId },
      repository: repositoryFor(auth.state.lastAuthUserId),
      authAdmin: {},
    });
    assert.equal(activated.request.status, "Active");

    const visible = await asAuthenticated(
      auth.state.lastAuthUserId,
      () => db.query(
        `select company_id, agency_id
         from public.agency_company_user_access
         order by company_id`
      )
    );
    assert.deepEqual(visible.rows, [{
      company_id: COMPANY_A,
      agency_id: AGENCIES[5],
    }]);
    assert.equal(result.request.public_user_id != null, true);
  });

  test("email delivery failure records Failed without partial linking", async () => {
    await assert.rejects(
      invite({
        authUserId: RM_A,
        role: "Recruitment Manager",
        agencyId: AGENCIES[6],
        fail: true,
      }),
      (error) =>
        error instanceof AgencyInvitationError &&
        error.code === "AGENCY_INVITATION_SEND_FAILED"
    );
    const request = await db.query(
      `select id, status, public_user_id
       from public.agency_provisioning_requests
       where agency_id = $1::uuid`,
      [AGENCIES[6]]
    );
    assert.equal(request.rows[0].status, "Failed");
    assert.equal(request.rows[0].public_user_id, null);
    const links = await db.query(
      `select count(*)::integer as count
       from public.agency_company_user_access
       where agency_id = $1::uuid`,
      [AGENCIES[6]]
    );
    assert.equal(links.rows[0].count, 0);

    const retry = await invite({
      authUserId: RM_A,
      role: "Recruitment Manager",
      agencyId: AGENCIES[6],
    });
    assert.equal(retry.result.request.status, "Invitation Sent");
    const requestCount = await db.query(
      `select count(*)::integer as count
       from public.agency_provisioning_requests
       where agency_id = $1::uuid`,
      [AGENCIES[6]]
    );
    assert.equal(requestCount.rows[0].count, 1);
  });

  test("accepting the invitation changes the state to Accepted", async () => {
    const { auth } = await invite({
      authUserId: ADMIN_A,
      role: "Company Admin",
      agencyId: AGENCIES[7],
    });
    const activated = await runAgencyInvitationAction({
      body: { action: "activate" },
      actor: { authUserId: auth.state.lastAuthUserId },
      repository: repositoryFor(auth.state.lastAuthUserId),
      authAdmin: {},
    });
    assert.equal(activated.request.status, "Active");
    const stored = await db.query(
      `select request.status, app_user.status as user_status,
              access.status as access_status
       from public.agency_provisioning_requests as request
       join public.users as app_user
         on app_user.id = request.public_user_id
       join public.agency_company_user_access as access
         on access.user_id = app_user.id
        and access.company_id = request.company_id
        and access.agency_id = request.agency_id
       where request.agency_id = $1::uuid`,
      [AGENCIES[7]]
    );
    assert.deepEqual(stored.rows[0], {
      status: "Active",
      user_status: "Active",
      access_status: "Active",
    });
  });

  test("authenticated cannot mutate sensitive invitation or link tables directly", async () => {
    const privileges = await db.query(`
      select
        has_table_privilege('authenticated', 'public.users', 'INSERT') as users_insert,
        has_table_privilege('authenticated', 'public.agency_company_user_access', 'INSERT') as access_insert,
        has_table_privilege('authenticated', 'public.agency_company_user_access', 'UPDATE') as access_update,
        has_table_privilege('authenticated', 'public.agency_company_user_access', 'DELETE') as access_delete,
        has_table_privilege('authenticated', 'public.agency_provisioning_requests', 'INSERT') as request_insert,
        has_table_privilege('authenticated', 'public.agency_provisioning_events', 'INSERT') as event_insert
    `);
    assert.deepEqual(privileges.rows[0], {
      users_insert: false,
      access_insert: false,
      access_update: false,
      access_delete: false,
      request_insert: false,
      event_insert: false,
    });

    await asAuthenticated(RM_A, async () => {
      await assert.rejects(
        db.query(
          `insert into public.agency_company_user_access (
             company_id, agency_id, user_id
           ) values ($1::uuid, $2::uuid, 1)`,
          [COMPANY_A, AGENCIES[0]]
        ),
        /permission denied for table agency_company_user_access/
      );
    });
  });
});
