const defineTemplate = ({
  profession,
  profession_ar,
  category,
  library,
  focus,
  job_description,
  years_experience,
  qualifications,
  certifications = "Role-relevant certificates are preferred only when required by the employer.",
  difficulty = "Medium",
  question_count = 12,
  passing_score = 75,
}) => Object.freeze({
  profession,
  profession_ar,
  category,
  library,
  focus,
  job_description,
  years_experience,
  qualifications,
  certifications,
  difficulty,
  question_count,
  passing_score,
  source_type: `VisaFlow ${library} Master Framework`,
});

export const TECHNICIAN_AI_TEMPLATE_CATALOG = Object.freeze([
  defineTemplate({
    profession: "Electrical Technician",
    profession_ar: "فني كهرباء",
    category: "Technical / Skilled",
    library: "Technician",
    focus: "Distribution boards, electrical measurements, motors, fault isolation and safe work.",
    job_description: "Install, inspect, maintain and troubleshoot low-voltage distribution boards, lighting, sockets, motors, starters, contactors and basic control circuits. Read single-line and wiring diagrams; use multimeters, clamp meters and insulation testers; identify overloads, short circuits, earth faults, loose connections and phase imbalance; apply lockout/tagout, verify isolation and restore equipment safely. Questions must test practical diagnosis, measurement selection, wiring logic, escalation and evidence that the repair is safe and effective.",
    years_experience: "3+ years",
    qualifications: "Technical diploma or vocational certificate in electrical technology or a closely related trade.",
  }),
  defineTemplate({
    profession: "HVAC Technician",
    profession_ar: "فني تكييف وتبريد",
    category: "Technical / Skilled",
    library: "Technician",
    focus: "Refrigeration cycle, pressures, airflow, electrical faults and preventive maintenance.",
    job_description: "Operate, maintain and troubleshoot split, package, DX, AHU and FCU systems. Check refrigeration pressures, temperatures, superheat, subcooling, airflow, filters, coils, fans, compressors, capacitors, contactors, thermostats and controls. Diagnose poor cooling, icing, leakage, high current, abnormal noise and drainage problems; recover and handle refrigerants responsibly; complete preventive maintenance and verify performance after repair. Questions must require a safe diagnostic sequence and interpretation of readings rather than guessing parts.",
    years_experience: "3+ years",
    qualifications: "Technical diploma or vocational certificate in HVAC and refrigeration.",
  }),
  defineTemplate({
    profession: "Mechanical Maintenance Technician",
    profession_ar: "فني ميكانيكا وصيانة",
    category: "Technical / Skilled",
    library: "Technician",
    focus: "Pumps, bearings, alignment, lubrication, vibration and mechanical fault diagnosis.",
    job_description: "Inspect, dismantle, repair, align and return mechanical equipment to service, including pumps, motors, gearboxes, bearings, couplings, valves and basic piping assemblies. Diagnose vibration, overheating, leakage, cavitation, misalignment and lubrication failures; use precision tools and safe lifting practices; follow permits and isolation procedures; record findings, parts and measurements; and verify the repair under controlled operating conditions. Questions must test hands-on sequence, tolerances, root cause and prevention of repeat failure.",
    years_experience: "3+ years",
    qualifications: "Technical diploma or vocational certificate in mechanical maintenance or industrial mechanics.",
  }),
  defineTemplate({
    profession: "Plumbing Technician",
    profession_ar: "فني سباكة",
    category: "Technical / Skilled",
    library: "Technician",
    focus: "Water supply, drainage, pumps, leakage, pressure and blockage diagnosis.",
    job_description: "Install, inspect and repair potable-water, drainage and sanitary systems, fixtures, valves, pumps and associated piping. Read basic plumbing drawings; locate concealed leaks; diagnose low pressure, water hammer, repeated blockage, pump cycling and drainage odor; select compatible materials and fittings; isolate work safely; test pressure and flow; protect hygiene and finishes; and document completed repairs. Questions must test practical diagnosis, correct repair method and prevention of recurrence.",
    years_experience: "3+ years",
    qualifications: "Vocational plumbing certificate or demonstrated equivalent trade experience.",
    question_count: 10,
    passing_score: 70,
  }),
  defineTemplate({
    profession: "Fire Protection and Alarm Technician",
    profession_ar: "فني مكافحة حريق وإنذار",
    category: "Security & Safety",
    library: "Technician",
    focus: "Fire pumps, sprinklers, alarm panels, devices, testing and life-safety escalation.",
    job_description: "Inspect, test and maintain fire pumps, valves, hydrants, hose reels, sprinklers, extinguishing interfaces, fire-alarm panels, detectors, modules, sounders and supervised circuits. Follow approved testing procedures; interpret panel faults and cause-and-effect; investigate pressure, flow, device, loop and false-alarm problems; keep systems available or implement approved impairment controls; and maintain accurate test records. Questions must prioritize life safety, code-compliant escalation and proof that systems operate correctly.",
    years_experience: "3+ years",
    qualifications: "Technical diploma or vocational certificate in fire protection, electrical systems or a related trade.",
    passing_score: 80,
  }),
  defineTemplate({
    profession: "BMS and Controls Technician",
    profession_ar: "فني أنظمة تحكم وBMS",
    category: "Technical / Skilled",
    library: "Technician",
    focus: "Sensors, actuators, I/O, control panels, alarms, trends and systematic diagnosis.",
    job_description: "Inspect and troubleshoot BMS and basic control systems, including sensors, actuators, controllers, relays, control panels, I/O points and communication links. Read wiring diagrams and point schedules; validate field signals; distinguish device, wiring, logic and network faults; review alarms and trends; apply safe overrides only with authorization; restore normal sequences; and document changes and test evidence. Questions must test signal tracing, control logic, safe bypass decisions and verification from field to workstation.",
    years_experience: "3+ years",
    qualifications: "Technical diploma in controls, instrumentation, electronics, electrical technology or a related discipline.",
  }),
  defineTemplate({
    profession: "Multi-Skilled Facilities Technician",
    profession_ar: "فني مرافق متعدد المهارات",
    category: "Technical / Skilled",
    library: "Technician",
    focus: "First-line electrical, HVAC, plumbing and general facilities response.",
    job_description: "Respond to facilities work orders and perform safe first-line inspection and minor repair across electrical, HVAC, plumbing and general building services within defined competence limits. Triage urgent faults, protect occupants and assets, isolate hazards, collect readings and evidence, complete preventive tasks, coordinate specialist escalation, communicate downtime and close work orders with accurate records. Questions must test prioritization, trade boundaries, customer communication and knowing when not to proceed.",
    years_experience: "3+ years",
    qualifications: "Facilities maintenance diploma, vocational certificate or verified multi-trade experience.",
    passing_score: 70,
  }),
  defineTemplate({
    profession: "Maintenance Supervisor",
    profession_ar: "مشرف فني وصيانة",
    category: "Operations",
    library: "Technician",
    focus: "Team allocation, preventive maintenance, permits, spares, SLA/KPI and incident leadership.",
    job_description: "Supervise technicians and contractors delivering planned and corrective maintenance. Prioritize work by safety and service impact; allocate competent resources; verify permits, isolation and method statements; review backlog, repeat failures, spares and shift handovers; inspect completed work; manage emergencies; track SLA and KPI performance; coach technicians; and escalate technical or commercial risks with evidence. Questions must test frontline leadership, technical judgment, planning and accountability under pressure.",
    years_experience: "5+ years including supervisory responsibility",
    qualifications: "Technical diploma or degree in a relevant maintenance discipline with proven supervisory experience.",
    difficulty: "Advanced",
    passing_score: 75,
  }),
]);

export const FINANCE_AI_TEMPLATE_CATALOG = Object.freeze([
  defineTemplate({
    profession: "General Accountant",
    profession_ar: "محاسب عام",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Journal entries, reconciliations, accruals, closing and financial statement accuracy.",
    job_description: "Maintain accurate general-ledger records, prepare and review journal entries, accruals, prepayments, fixed assets and account reconciliations, support monthly closing and produce reliable schedules for financial statements and audit. Investigate unusual balances, preserve supporting documents, follow approval controls and explain corrections clearly. Questions must include realistic entries, reconciliation differences, period cut-off and detection of unsupported or duplicated transactions.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in accounting, finance or a closely related field.",
  }),
  defineTemplate({
    profession: "Accounts Payable Accountant",
    profession_ar: "محاسب حسابات دائنة",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Supplier invoices, three-way matching, approvals, payments and reconciliations.",
    job_description: "Process supplier invoices and credit notes; verify vendor, tax and banking data; perform purchase-order, receipt and invoice matching; resolve quantity, price and approval exceptions; prepare controlled payment runs; reconcile supplier statements; manage advances and aging; and maintain a complete audit trail. Questions must test duplicate detection, mismatches, cut-off, segregation of duties and handling urgent payment pressure without bypassing controls.",
    years_experience: "2+ years",
    qualifications: "Diploma or bachelor's degree in accounting or finance.",
    question_count: 10,
  }),
  defineTemplate({
    profession: "Accounts Receivable Accountant",
    profession_ar: "محاسب حسابات مدينة",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Billing, collections, customer reconciliation, aging and credit control.",
    job_description: "Issue accurate customer invoices and credit notes, allocate receipts, reconcile customer accounts, investigate deductions and disputes, maintain aging reports, follow collection actions and support credit-limit decisions. Verify contractual billing evidence, revenue cut-off and approval for adjustments while communicating professionally with operations and customers. Questions must test unapplied cash, disputed invoices, overdue balances, write-offs and reliable collection forecasting.",
    years_experience: "2+ years",
    qualifications: "Diploma or bachelor's degree in accounting or finance.",
    question_count: 10,
  }),
  defineTemplate({
    profession: "Cost Accountant",
    profession_ar: "محاسب تكاليف",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Cost centers, allocations, standards, variance analysis and profitability.",
    job_description: "Build and maintain cost-center and cost-object records, classify direct and indirect costs, calculate allocations and unit or service costs, analyze material, labor, overhead and productivity variances, reconcile costing to the ledger and explain profitability drivers. Challenge weak assumptions and protect traceability from source data to management reports. Questions must require calculations, allocation choices, variance diagnosis and identification of distorted margins.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in accounting or finance; cost-accounting certification is preferred when required.",
  }),
  defineTemplate({
    profession: "Project and Contracting Accountant",
    profession_ar: "محاسب مشاريع ومقاولات",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Project billing, progress, subcontractors, commitments, retention and margin control.",
    job_description: "Control project financial records from approved budget and commitments through progress billing and closeout. Review customer and subcontractor certificates, retention, advances, variations, accruals, cost-to-complete and revenue recognition evidence; reconcile site and finance records; monitor cash flow and margin; and escalate unsupported progress or cost forecasts. Questions must use contracting scenarios involving cut-off, unapproved variations, retention and forecast-at-completion.",
    years_experience: "4+ years in project or contracting accounting",
    qualifications: "Bachelor's degree in accounting or finance with relevant project-accounting experience.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Tax and Zakat Accountant",
    profession_ar: "محاسب ضريبة وزكاة",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "VAT documentation, reconciliations, returns, records and controlled compliance.",
    job_description: "Prepare controlled tax and zakat workpapers using the organization's approved policies and current regulatory guidance. Validate invoice data, tax treatment and supporting evidence; reconcile returns to ledgers and source transactions; investigate exceptions; maintain filing and payment calendars; support audits; and escalate uncertain treatment for authorized review. Questions must test evidence, reconciliation, correction and professional judgment without encouraging unsupported legal conclusions.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in accounting, finance or taxation with relevant Saudi compliance experience.",
    difficulty: "Advanced",
    passing_score: 80,
  }),
  defineTemplate({
    profession: "Financial Analyst",
    profession_ar: "محلل مالي",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Financial statements, ratios, budgets, cash flow, forecasting and decision support.",
    job_description: "Analyze income statements, balance sheets, cash flow, budgets and operational drivers; build transparent forecasts and scenarios; explain variance, liquidity, profitability and working-capital movements; validate data and assumptions; and present decision-focused recommendations with risks and sensitivities. Questions must require numerical interpretation, scenario analysis, identification of misleading comparisons and a defensible recommendation.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in finance, accounting, economics or a related analytical field.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Payroll Accountant",
    profession_ar: "محاسب رواتب",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Payroll inputs, allowances, deductions, reconciliations, controls and confidentiality.",
    job_description: "Prepare and reconcile payroll using approved employee, attendance, allowance, deduction and change records. Validate joiners, leavers, unpaid leave, overtime and retroactive adjustments; investigate variances; protect confidential information; coordinate controlled approvals and payment files; reconcile payroll liabilities to the ledger; and resolve employee queries with evidence. Questions must test calculation logic, cutoff, duplicate or unauthorized changes and segregation of duties.",
    years_experience: "3+ years",
    qualifications: "Diploma or bachelor's degree in accounting, finance or a related field with payroll experience.",
    question_count: 10,
  }),
  defineTemplate({
    profession: "Senior Accountant or Chief Accountant",
    profession_ar: "محاسب أول أو رئيس حسابات",
    category: "Finance & Accounting",
    library: "Finance",
    focus: "Close governance, controls, review, audit readiness, reporting and team leadership.",
    job_description: "Lead or review the accounting close, reconciliations, estimates, financial schedules and control evidence. Challenge material entries and unusual trends; resolve cross-functional issues; maintain audit readiness; improve processes without weakening controls; coach accountants; and communicate financial risk and deadlines to management. Questions must combine technical accounting, review judgment, fraud and error indicators, prioritization and leadership under a constrained close timetable.",
    years_experience: "6+ years including review or team leadership responsibility",
    qualifications: "Bachelor's degree in accounting or finance; a recognized professional accounting qualification is preferred.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
]);

export const HR_AI_TEMPLATE_CATALOG = Object.freeze([
  defineTemplate({
    profession: "HR Generalist",
    profession_ar: "أخصائي موارد بشرية عام",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Employee lifecycle, records, attendance, leave, policy service and case coordination.",
    job_description: "Support the employee lifecycle from approved hiring and onboarding through records, attendance, leave, changes, employee queries and separation. Maintain accurate confidential files, apply approved policies consistently, coordinate payroll and managers, track deadlines and escalate exceptions or sensitive cases to authorized decision makers. Questions must use realistic employee-service scenarios and test accuracy, confidentiality, documentation and fair process.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in human resources, business administration or a related field.",
    passing_score: 70,
  }),
  defineTemplate({
    profession: "Recruitment Specialist",
    profession_ar: "أخصائي توظيف",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Requisition intake, sourcing, structured screening, interviews, offers and hiring metrics.",
    job_description: "Translate approved workforce needs into clear role requirements, sourcing plans and structured selection criteria. Screen candidates using job-related evidence, coordinate interviews, maintain candidate communication and consent, prepare approved offers, track funnel quality and time, and protect equal and consistent treatment. Questions must test difficult intake conversations, evidence-based shortlisting, candidate experience, offer risk and ethical handling of confidential data.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in human resources, business administration or a related field with recruitment experience.",
  }),
  defineTemplate({
    profession: "Personnel Affairs Specialist",
    profession_ar: "أخصائي شؤون موظفين",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Contracts, employee files, attendance, leave, lifecycle transactions and controlled compliance.",
    job_description: "Administer approved employee contracts, personal records, attendance, leave, status changes, letters and separation documents. Verify authorization and effective dates, maintain complete confidential evidence, reconcile HR-system records, follow the organization's current Saudi employment procedures and escalate uncertain or exceptional cases for authorized review. Questions must test document accuracy, deadlines, conflicting instructions and correction of employee-record errors.",
    years_experience: "3+ years in Saudi personnel operations",
    qualifications: "Bachelor's degree or diploma in human resources, business administration or a related field.",
  }),
  defineTemplate({
    profession: "Compensation and Payroll Specialist",
    profession_ar: "أخصائي رواتب ومزايا",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Payroll inputs, benefits, changes, reconciliation, employee queries and data confidentiality.",
    job_description: "Coordinate controlled payroll and benefit inputs, including joiners, leavers, attendance, leave, allowances, deductions and approved changes. Validate effective dates and evidence, reconcile outputs, investigate variances, protect sensitive data, coordinate finance approval and resolve employee queries without exposing other employees' information. Questions must test calculation reasoning, unauthorized changes, cutoff, reconciliation and confidential communication.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in human resources, accounting, finance or business administration with payroll experience.",
  }),
  defineTemplate({
    profession: "Employee Relations Specialist",
    profession_ar: "أخصائي علاقات موظفين",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Complaints, investigations, conflict, disciplinary process and consistent documentation.",
    job_description: "Receive and triage employee concerns, preserve confidentiality, identify conflicts of interest and urgent safety risks, gather evidence fairly, document interviews, apply approved grievance and disciplinary procedures, support proportionate decisions and monitor corrective actions. Questions must use sensitive workplace scenarios and test neutrality, evidence, escalation, anti-retaliation and communication without making unsupported legal conclusions.",
    years_experience: "4+ years",
    qualifications: "Bachelor's degree in human resources, business administration, law or a related field with employee-relations experience.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Learning and Development Specialist",
    profession_ar: "أخصائي تدريب وتطوير",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Training needs, learning design, delivery, evaluation and measurable impact.",
    job_description: "Analyze capability gaps using performance and business evidence, define learning objectives, select suitable interventions and providers, coordinate delivery, evaluate participation, learning and workplace application, and report impact against baseline measures. Questions must distinguish training needs from process or management problems and test practical design, vendor control, accessibility and evidence of behavior change.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in human resources, education, business administration or a related field.",
    question_count: 10,
    passing_score: 70,
  }),
  defineTemplate({
    profession: "Performance and Organization Development Specialist",
    profession_ar: "أخصائي أداء وتطوير تنظيمي",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Objectives, KPIs, performance cycles, job design, structures and change adoption.",
    job_description: "Support job analysis, role clarity, organization structures, goal and KPI design, performance-cycle governance and improvement initiatives. Test metric quality, calibrate evidence, identify process bias, translate strategy into accountable roles and measure whether organization changes improve outcomes. Questions must require diagnosis of weak KPIs, inconsistent ratings, overlapping responsibilities and change resistance.",
    years_experience: "4+ years",
    qualifications: "Bachelor's degree in human resources, organization development, business administration or a related field.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "HR Business Partner",
    profession_ar: "شريك أعمال موارد بشرية",
    category: "HR & Recruitment",
    library: "HR",
    focus: "Workforce planning, manager advisory, performance, retention and evidence-based decisions.",
    job_description: "Partner with business leaders on workforce plans, organization capability, performance, talent, retention and employee risk. Use reliable people data, challenge unsupported requests, coordinate specialist HR services, protect fair and consistent process and translate business priorities into measurable people actions. Questions must use ambiguous cases involving restructuring, critical vacancies, weak leadership, turnover and conflicting stakeholder demands.",
    years_experience: "6+ years including business-partnering responsibility",
    qualifications: "Bachelor's degree in human resources, business administration or a related field; advanced HR certification is preferred.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
  defineTemplate({
    profession: "HR Manager",
    profession_ar: "مدير موارد بشرية",
    category: "HR & Recruitment",
    library: "HR",
    focus: "HR strategy, governance, workforce, risk, budget, leadership and executive advice.",
    job_description: "Lead human-resources strategy and operations across workforce planning, recruitment, employee relations, rewards, performance, development, HR data and controlled compliance. Establish decision rights and service standards, manage budget and team capability, protect confidential information, advise executives with evidence and escalate legal or ethical risk to authorized specialists. Questions must test strategic prioritization, governance, difficult leadership decisions and measurable business impact.",
    years_experience: "8+ years including HR leadership responsibility",
    qualifications: "Bachelor's degree in human resources, business administration or a related field; postgraduate or professional HR qualification is preferred.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
]);

export const IT_AI_TEMPLATE_CATALOG = Object.freeze([
  defineTemplate({
    profession: "IT Support Specialist",
    profession_ar: "أخصائي دعم تقنية المعلومات",
    category: "IT",
    library: "IT",
    focus: "Incident triage, endpoint support, identity, networking basics, documentation and user service.",
    job_description: "Provide structured first- and second-line support for user devices, operating systems, productivity applications, printers, accounts and common connectivity issues. Capture symptoms and impact, protect user data, diagnose systematically, use approved remote-support tools, apply access and change controls, document evidence, restore service and escalate recurring or high-risk incidents with complete context. Questions must test troubleshooting sequence, prioritization, security awareness and communication with non-technical users.",
    years_experience: "2+ years",
    qualifications: "Diploma or bachelor's degree in information technology, computer science or a related discipline, or verified equivalent support experience.",
    question_count: 10,
    passing_score: 70,
  }),
  defineTemplate({
    profession: "Systems Administrator",
    profession_ar: "مسؤول أنظمة",
    category: "IT",
    library: "IT",
    focus: "Server administration, identity, patching, backup, monitoring, automation and recovery.",
    job_description: "Administer Windows or Linux servers, directory and identity services, permissions, patching, configuration, monitoring, backup and recovery. Diagnose service, capacity, authentication and performance failures; automate controlled routine work; maintain inventories and runbooks; test restore procedures; protect privileged access; and plan changes with rollback and communication. Questions must test evidence-based diagnosis, least privilege, resilience, recovery objectives and safe production change.",
    years_experience: "4+ years",
    qualifications: "Bachelor's degree or diploma in information technology, computer science or systems administration with relevant platform experience.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Network Engineer",
    profession_ar: "مهندس شبكات",
    category: "IT",
    library: "IT",
    focus: "Routing, switching, wireless, addressing, segmentation, monitoring and fault isolation.",
    job_description: "Design, configure, monitor and troubleshoot enterprise LAN, WAN, wireless and secure connectivity. Interpret topology, addressing, VLAN, routing, switching, DNS, DHCP, VPN and firewall dependencies; isolate packet loss, latency, loops, reachability and configuration faults; protect segmentation and management access; plan resilient changes and preserve configuration backups and evidence. Questions must require layered diagnosis, command and capture interpretation, risk control and verification after change.",
    years_experience: "4+ years",
    qualifications: "Bachelor's degree in networking, information technology or computer engineering; relevant network certification is preferred.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Cybersecurity Analyst",
    profession_ar: "محلل أمن سيبراني",
    category: "IT",
    library: "IT",
    focus: "Alert triage, incident response, vulnerability, identity, evidence and risk communication.",
    job_description: "Monitor and investigate security alerts, validate indicators and scope, preserve evidence, coordinate containment and recovery, document timelines and support lessons learned. Review vulnerability and access findings, prioritize remediation by exploitability and business impact, protect confidential information and escalate material incidents through approved channels. Questions must test analytical reasoning, false-positive handling, chain of evidence, least privilege and communication without encouraging unsafe offensive activity.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in cybersecurity, information technology, computer science or a related field; relevant defensive-security certification is preferred.",
    difficulty: "Advanced",
    passing_score: 80,
  }),
  defineTemplate({
    profession: "Software Developer",
    profession_ar: "مطور برمجيات",
    category: "IT",
    library: "IT",
    focus: "Requirements, design, implementation, testing, debugging, security and maintainability.",
    job_description: "Translate approved requirements into maintainable software, select appropriate designs, implement and review code, write automated tests, diagnose defects, protect secrets and user data, manage dependencies and changes, and support reliable deployment and rollback. Explain trade-offs and document assumptions so others can operate the solution. Questions must test problem decomposition, data and API design, debugging evidence, test strategy, secure coding and ownership of production outcomes rather than language trivia alone.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in computer science, software engineering or a related discipline, or verified equivalent development experience.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Database Administrator",
    profession_ar: "مسؤول قواعد بيانات",
    category: "IT",
    library: "IT",
    focus: "Availability, performance, backup, recovery, access, change and data protection.",
    job_description: "Administer production databases, users and privileges, backup and recovery, monitoring, maintenance, capacity and controlled schema changes. Diagnose blocking, slow queries, storage, replication and availability problems; protect sensitive data; test restores; define recovery evidence; coordinate releases and document runbooks and incidents. Questions must test transaction and index reasoning, safe troubleshooting, least privilege, recovery objectives and prevention of data loss.",
    years_experience: "4+ years",
    qualifications: "Bachelor's degree in computer science, information systems or a related field with production database experience.",
    difficulty: "Advanced",
    passing_score: 80,
  }),
  defineTemplate({
    profession: "Cloud and DevOps Engineer",
    profession_ar: "مهندس سحابة وDevOps",
    category: "IT",
    library: "IT",
    focus: "Cloud architecture, infrastructure as code, CI/CD, observability, security and reliability.",
    job_description: "Design and operate cloud infrastructure and delivery pipelines using controlled infrastructure as code, secure identity, network boundaries, secrets management, automated testing, deployment strategies, monitoring and cost visibility. Diagnose application and platform incidents, protect production environments, implement rollback and disaster-recovery practices and reduce manual risk through reviewed automation. Questions must test architecture trade-offs, pipeline failure, observability, least privilege, resilience and responsible cost control.",
    years_experience: "4+ years",
    qualifications: "Bachelor's degree in computer science, information technology or engineering with relevant cloud and automation experience.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Data and Business Intelligence Analyst",
    profession_ar: "محلل بيانات وذكاء أعمال",
    category: "IT",
    library: "IT",
    focus: "Metric definition, SQL, data quality, dashboards, analysis and decision communication.",
    job_description: "Translate business questions into defined metrics, trustworthy queries, analyses and dashboards. Inspect source lineage and data quality, write and review SQL, reconcile totals, select suitable comparisons and visualizations, document assumptions and communicate findings without overstating causality. Protect sensitive data and design repeatable reporting controls. Questions must test metric ambiguity, join and aggregation errors, validation, analytical reasoning and decision-focused communication.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in information systems, computer science, statistics, analytics or a related quantitative field.",
  }),
  defineTemplate({
    profession: "IT Project Manager",
    profession_ar: "مدير مشاريع تقنية معلومات",
    category: "IT",
    library: "IT",
    focus: "Scope, delivery planning, dependencies, vendors, risk, change, adoption and governance.",
    job_description: "Lead technology projects from business case and requirements through design, delivery, testing, migration, adoption and closure. Establish scope, milestones, dependencies, responsibilities and acceptance criteria; control risk, budget, vendors and change; surface technical constraints early; protect security and operational readiness; and report evidence-based status to stakeholders. Questions must use difficult delivery scenarios involving unclear ownership, failed testing, scope pressure and go-live decisions.",
    years_experience: "6+ years including technology project leadership",
    qualifications: "Bachelor's degree in information technology, business, engineering or a related field; recognized project-management certification is preferred.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
]);

export const OPERATIONS_MANAGEMENT_AI_TEMPLATE_CATALOG = Object.freeze([
  defineTemplate({
    profession: "Operations Coordinator",
    profession_ar: "منسق عمليات",
    category: "Operations",
    library: "Operations Management",
    focus: "Daily coordination, records, scheduling, issue follow-up and stakeholder communication.",
    job_description: "Coordinate daily operational activities, schedules, work requests, records and stakeholder updates. Confirm inputs and ownership, track deadlines and exceptions, maintain accurate logs, escalate service risks promptly and close actions with evidence. Balance multiple requests without bypassing approvals or losing traceability. Questions must test prioritization, handover quality, handling incomplete information, professional communication and accurate operational reporting.",
    years_experience: "2+ years",
    qualifications: "Diploma or bachelor's degree in business administration, operations management or a related field.",
    question_count: 10,
    passing_score: 70,
  }),
  defineTemplate({
    profession: "Operations Supervisor",
    profession_ar: "مشرف عمليات",
    category: "Operations",
    library: "Operations Management",
    focus: "Shift control, people allocation, safety, productivity, incidents and handover.",
    job_description: "Supervise daily shifts and frontline teams against approved procedures, service levels, quality and safety requirements. Allocate competent resources, conduct briefings and handovers, respond to incidents, verify completed work, manage absence and workload, coach performance and escalate constraints with facts. Questions must test immediate leadership decisions, fair allocation, service recovery, evidence-based escalation and accountability under pressure.",
    years_experience: "4+ years including supervisory responsibility",
    qualifications: "Diploma or bachelor's degree in operations, business administration or a relevant technical field with frontline leadership experience.",
  }),
  defineTemplate({
    profession: "Operations Manager",
    profession_ar: "مدير عمليات",
    category: "Operations",
    library: "Operations Management",
    focus: "Operating model, capacity, KPI, cost, risk, service performance and leadership.",
    job_description: "Lead an operating function against service, quality, safety, cost and customer commitments. Establish procedures, capacity and workforce plans, review KPI integrity, manage budget and suppliers, respond to incidents, remove bottlenecks and govern continuous improvement. Translate strategy into accountable routines and communicate trade-offs and risks to executives. Questions must use ambiguous multi-site or high-volume scenarios and test prioritization, financial judgment and sustainable performance improvement.",
    years_experience: "7+ years including operations leadership",
    qualifications: "Bachelor's degree in operations management, business administration, engineering or a related field.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
  defineTemplate({
    profession: "Facilities Operations Manager",
    profession_ar: "مدير عمليات مرافق",
    category: "Operations",
    library: "Operations Management",
    focus: "Service continuity, FM contracts, SLA/KPI, assets, occupants, safety and lifecycle decisions.",
    job_description: "Lead integrated facilities operations across hard and soft services, planned and reactive maintenance, compliance, utilities, customer requests and contractors. Protect service continuity and occupant safety, challenge SLA and KPI evidence, control backlog and shutdowns, manage budget and lifecycle priorities and coordinate emergency response and handover. Questions must test multidisciplinary prioritization, contractor accountability, client communication and risk-based asset decisions.",
    years_experience: "7+ years in facilities management including leadership responsibility",
    qualifications: "Bachelor's degree or technical qualification in facilities, engineering, operations or a related discipline with relevant FM experience.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
  defineTemplate({
    profession: "Maintenance Operations Manager",
    profession_ar: "مدير عمليات الصيانة",
    category: "Operations",
    library: "Operations Management",
    focus: "Reliability strategy, backlog, shutdowns, spares, contractors, risk and maintenance economics.",
    job_description: "Lead maintenance operations for critical assets using risk-based preventive, predictive and corrective strategies. Govern planning, backlog, permits, isolation, shutdowns, spares, contractor quality and return-to-service evidence; analyze repeat failure, availability, MTBF and MTTR; balance production and lifecycle risk; and develop team capability. Questions must test reliability judgment, emergency leadership, constrained-resource decisions and proof that improvement is sustained.",
    years_experience: "7+ years including maintenance leadership",
    qualifications: "Bachelor's degree or advanced technical qualification in mechanical, electrical, maintenance or reliability engineering.",
    difficulty: "Advanced",
    question_count: 15,
    passing_score: 80,
  }),
  defineTemplate({
    profession: "Logistics and Warehouse Operations Manager",
    profession_ar: "مدير عمليات لوجستية ومستودعات",
    category: "Operations",
    library: "Operations Management",
    focus: "Receiving, storage, inventory, fulfillment, transport, safety, capacity and accuracy.",
    job_description: "Lead receiving, put-away, storage, picking, dispatch, transport coordination and inventory control. Design safe flows and responsibilities, protect stock accuracy and traceability, plan labor and capacity, investigate losses and delays, manage carriers and service levels and improve cost without weakening controls. Questions must test inventory discrepancies, peak demand, damaged or urgent material, segregation of duties and measurable process improvement.",
    years_experience: "6+ years including logistics or warehouse leadership",
    qualifications: "Bachelor's degree in logistics, supply chain, operations or business administration, or verified equivalent management experience.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Service Delivery Manager",
    profession_ar: "مدير تقديم الخدمات",
    category: "Operations",
    library: "Operations Management",
    focus: "Customer commitments, SLA, governance, incidents, suppliers, improvement and commercial risk.",
    job_description: "Own delivery of contracted or internal services against scope, service levels, quality, cost and customer expectations. Establish governance and reporting, validate SLA data, coordinate incident and problem management, manage suppliers and escalations, control service changes and improvement plans and communicate commercial or operational risk early. Questions must test service recovery, disputed performance, stakeholder conflict and sustainable corrective action.",
    years_experience: "6+ years including service-delivery leadership",
    qualifications: "Bachelor's degree in business, operations, information technology, engineering or a related service discipline.",
    difficulty: "Advanced",
  }),
  defineTemplate({
    profession: "Process Improvement Specialist",
    profession_ar: "أخصائي تحسين العمليات",
    category: "Operations",
    library: "Operations Management",
    focus: "Process mapping, root cause, data, waste, controls, change and benefits validation.",
    job_description: "Analyze operational processes using reliable data, observation and stakeholder evidence. Define the problem and baseline, map flow and controls, identify bottlenecks and root causes, design and test improvements, evaluate risk and cost, support adoption and verify benefits after implementation. Questions must test whether the candidate distinguishes symptoms from causes, avoids shifting risk and uses measurable controls to sustain results.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in industrial engineering, operations, business or a related analytical field; process-improvement certification is preferred.",
  }),
  defineTemplate({
    profession: "Workforce Planning and Scheduling Specialist",
    profession_ar: "أخصائي تخطيط وجدولة القوى العاملة",
    category: "Operations",
    library: "Operations Management",
    focus: "Demand forecasting, capacity, rosters, skills, coverage, overtime and scenario planning.",
    job_description: "Translate service demand into transparent staffing and roster requirements using volume, productivity, skill, shift, leave and legal or policy constraints. Build scenarios, identify coverage risk, reconcile planned and actual hours, explain overtime and utilization drivers and coordinate changes fairly with operations and HR. Questions must require numerical reasoning, assumptions, peak-demand response and protection against unsafe or unsustainable scheduling.",
    years_experience: "3+ years",
    qualifications: "Bachelor's degree in operations, industrial engineering, analytics, human resources or a related field.",
  }),
]);

export const SPECIALIZED_AI_TEMPLATE_CATALOG = Object.freeze([
  ...TECHNICIAN_AI_TEMPLATE_CATALOG,
  ...FINANCE_AI_TEMPLATE_CATALOG,
  ...HR_AI_TEMPLATE_CATALOG,
  ...IT_AI_TEMPLATE_CATALOG,
  ...OPERATIONS_MANAGEMENT_AI_TEMPLATE_CATALOG,
]);
