import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { after, before, describe, test } from 'node:test'
import { PGlite } from '@electric-sql/pglite'

const COMPANY_ONE = '10000000-0000-4000-8000-000000000001'
const COMPANY_TWO = '10000000-0000-4000-8000-000000000002'
const AGENCY_ONE = '20000000-0000-4000-8000-000000000001'
const COMPANY_ACTOR_AUTH = '30000000-0000-4000-8000-000000000001'
const AGENCY_ACTOR_AUTH = '30000000-0000-4000-8000-000000000002'
const OTHER_RECIPIENT_AUTH = '30000000-0000-4000-8000-000000000003'

const fixtureSql = `
create schema auth;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.companies (
  id uuid primary key,
  status text not null
);

create table public.agencies (
  id uuid primary key,
  name text not null,
  status text not null
);

create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  company_id uuid references public.companies(id),
  agency_id uuid references public.agencies(id),
  name text,
  email text,
  role text not null,
  status text not null,
  is_active boolean not null default true
);

create table public.company_agency_access (
  company_id uuid not null references public.companies(id),
  agency_id uuid not null references public.agencies(id),
  status text not null,
  primary key (company_id, agency_id)
);

create table public.agency_company_user_access (
  user_id bigint not null references public.users(id),
  company_id uuid not null references public.companies(id),
  agency_id uuid not null references public.agencies(id),
  status text not null,
  primary key (user_id, company_id, agency_id)
);

create table public.visa_allocations (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id),
  allocated_qty bigint not null,
  visa_no text,
  request_no text,
  visa_batch_line_id bigint
);

create table public.visa_authorizations (
  id uuid primary key default gen_random_uuid(),
  visa_id uuid not null default gen_random_uuid(),
  visa_no text,
  authorization_no text,
  agency text,
  office_country text,
  allocated_qty bigint,
  received_candidates bigint,
  interview_passed bigint,
  mobilized bigint,
  status text,
  created_at timestamptz,
  request_no text,
  cancellation_no text,
  cancelled_at date,
  company_id uuid references public.companies(id),
  profession text,
  nationality text,
  gender text,
  visa_allocation_id bigint references public.visa_allocations(id),
  visa_batch_line_id bigint,
  created_by_name text,
  created_by_email text,
  created_by_role text,
  updated_by_name text,
  updated_by_email text,
  updated_by_role text
);

create table public.notification_events (
  id bigint generated by default as identity primary key,
  status text not null,
  data jsonb,
  delivery_status text default 'Pending',
  error_message text,
  created_at timestamptz default now(),
  sent_at timestamptz,
  company_id uuid references public.companies(id),
  user_id uuid,
  agency_id uuid references public.agencies(id),
  type text,
  title text,
  message text,
  priority text default 'Medium',
  related_table text,
  related_id text,
  read_at timestamptz,
  request_no text,
  agency_name text,
  response_status text default 'Pending',
  response_at timestamptz,
  rejection_reason text,
  sla_started_at timestamptz,
  sla_days integer,
  sla_due_at timestamptz,
  dedupe_key text
);

create unique index notification_events_company_dedupe_key_unique
  on public.notification_events(company_id, dedupe_key)
  where dedupe_key is not null;

create function public.current_log_actor()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', app_user.id,
    'auth_user_id', app_user.auth_user_id,
    'company_id', app_user.company_id,
    'agency_id', app_user.agency_id,
    'name', app_user.name,
    'email', app_user.email,
    'role', app_user.role
  )
  from public.users app_user
  where app_user.auth_user_id = auth.uid()
    and app_user.status = 'Active'
    and app_user.is_active is true
$$;

alter table public.visa_authorizations enable row level security;
create policy visa_authorizations_select_tenant_policy
  on public.visa_authorizations for select to authenticated using (true);
create policy visa_authorizations_insert_tenant_policy
  on public.visa_authorizations for insert to authenticated with check (true);
create policy visa_authorizations_update_tenant_policy
  on public.visa_authorizations for update to authenticated using (true) with check (true);
create policy visa_authorizations_delete_tenant_policy
  on public.visa_authorizations for delete to authenticated using (true);
`

let db
let migrationOne
let migrationTwo
let agencyActorId

async function setActor(authUserId) {
  await db.query("select set_config('request.jwt.claim.sub', $1::text, false)", [authUserId])
}

async function mutateAuthorization(action, authorizationId, input, idempotencyKey) {
  const result = await db.query(
    `select public.authorization_workflow_mutate(
      $1::text, $2::uuid, $3::jsonb, $4::text
    ) as result`,
    [action, authorizationId, JSON.stringify(input), idempotencyKey]
  )
  return result.rows[0].result
}

async function mutateNotification(operation, notificationId, payload = {}) {
  const result = await db.query(
    `select public.notification_event_mutate(
      $1::text, $2::bigint, $3::jsonb
    ) as result`,
    [operation, notificationId, JSON.stringify(payload)]
  )
  return result.rows[0].result
}

async function createAllocation(quantity = 10) {
  const result = await db.query(
    `insert into public.visa_allocations (
      company_id, allocated_qty, visa_no, request_no
    ) values ($1::uuid, $2::bigint, 'VISA-001', 'REQ-001')
    returning id`,
    [COMPANY_ONE, quantity]
  )
  return result.rows[0].id
}

function createInput(allocationId, authorizationNo) {
  return {
    visa_allocation_id: String(allocationId),
    agency_id: AGENCY_ONE,
    allocated_qty: 1,
    authorization_no: authorizationNo,
  }
}

describe('authorization workflow migrations on temporary PostgreSQL', () => {
  before(async () => {
    db = new PGlite()
    migrationOne = await readFile(
      new URL('../supabase/migrations/20260729000100_prelaunch_authorization_workflow.sql', import.meta.url),
      'utf8'
    )
    migrationTwo = await readFile(
      new URL('../supabase/migrations/20260729000110_prelaunch_workflow_atomic_rpcs.sql', import.meta.url),
      'utf8'
    )

    await db.exec(fixtureSql)
    await db.exec(`
      insert into public.companies (id, status) values
        ('${COMPANY_ONE}', 'Active'),
        ('${COMPANY_TWO}', 'Active');
      insert into public.agencies (id, name, status)
        values ('${AGENCY_ONE}', 'Agency One', 'Active');
      insert into public.users (
        auth_user_id, company_id, name, email, role, status, is_active
      ) values (
        '${COMPANY_ACTOR_AUTH}', '${COMPANY_ONE}', 'Company Actor',
        'company@example.invalid', 'Company Admin', 'Active', true
      );
      insert into public.users (
        auth_user_id, agency_id, name, email, role, status, is_active
      ) values (
        '${AGENCY_ACTOR_AUTH}', '${AGENCY_ONE}', 'Agency Actor',
        'agency@example.invalid', 'Agency', 'Active', true
      );
      insert into public.users (
        auth_user_id, company_id, name, email, role, status, is_active
      ) values (
        '${OTHER_RECIPIENT_AUTH}', '${COMPANY_ONE}', 'Other Recipient',
        'recipient@example.invalid', 'Company Admin', 'Active', true
      );
      insert into public.company_agency_access (company_id, agency_id, status) values
        ('${COMPANY_ONE}', '${AGENCY_ONE}', 'Active'),
        ('${COMPANY_TWO}', '${AGENCY_ONE}', 'Active');
    `)
    const agencyActor = await db.query(
      'select id from public.users where auth_user_id = $1::uuid',
      [AGENCY_ACTOR_AUTH]
    )
    agencyActorId = agencyActor.rows[0].id
  })

  after(async () => {
    await db.close()
  })

  test('migration one succeeds when visa_authorizations initially has no agency_id', async () => {
    const beforeColumn = await db.query(`
      select count(*)::integer as count
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'visa_authorizations'
        and column_name = 'agency_id'
    `)
    assert.equal(beforeColumn.rows[0].count, 0)

    await db.exec(`begin; ${migrationOne} commit;`)

    const afterColumn = await db.query(`
      select count(*)::integer as count
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'visa_authorizations'
        and column_name = 'agency_id'
    `)
    assert.equal(afterColumn.rows[0].count, 1)
    await db.exec(`begin; ${migrationTwo} commit;`)
  })

  test('authorization create without visa_id applies the database default', async () => {
    await setActor(COMPANY_ACTOR_AUTH)
    const allocationId = await createAllocation()
    const result = await mutateAuthorization(
      'create',
      null,
      createInput(allocationId, 'AUTH-DEFAULT'),
      '40000000-0000-4000-8000-000000000001'
    )
    assert.ok(result.authorization.visa_id)
    assert.equal(result.authorization.authorization_no, 'AUTH-DEFAULT')
  })

  test('same authorization operation and key return one row and one event', async () => {
    await setActor(COMPANY_ACTOR_AUTH)
    const allocationId = await createAllocation()
    const key = '40000000-0000-4000-8000-000000000002'
    const input = createInput(allocationId, 'AUTH-IDEMPOTENT')
    const first = await mutateAuthorization('create', null, input, key)
    const second = await mutateAuthorization('create', null, input, key)

    assert.equal(second.authorization.id, first.authorization.id)
    assert.equal(second.idempotent, true)
    const counts = await db.query(
      `select
        (select count(*)::integer from public.visa_authorizations
          where creation_idempotency_key = 'create:' || $1::text) as authorizations,
        (select count(*)::integer from public.authorization_events
          where authorization_id = $2::uuid) as events`,
      [key, first.authorization.id]
    )
    assert.deepEqual(counts.rows[0], { authorizations: 1, events: 1 })
  })

  test('same raw key with a different action does not return the create result', async () => {
    await setActor(COMPANY_ACTOR_AUTH)
    const allocationId = await createAllocation()
    const key = '40000000-0000-4000-8000-000000000003'
    const created = await mutateAuthorization(
      'create',
      null,
      createInput(allocationId, 'AUTH-ACTION-BINDING'),
      key
    )
    const sent = await mutateAuthorization('send', created.authorization.id, {}, key)

    assert.equal(sent.idempotent, false)
    assert.equal(sent.authorization.status, 'Sent to Agency')
    const events = await db.query(
      `select event_type, idempotency_key
       from public.authorization_events
       where authorization_id = $1::uuid
       order by id`,
      [created.authorization.id]
    )
    assert.deepEqual(
      events.rows.map((event) => event.event_type),
      ['Created', 'Sent']
    )
    assert.deepEqual(
      events.rows.map((event) => event.idempotency_key),
      [`create:${key}`, `send:${key}`]
    )
  })

  test('notification create with the same dedupe_key leaves one row', async () => {
    await setActor(COMPANY_ACTOR_AUTH)
    const payload = {
      type: 'CANDIDATE_UPDATED',
      dedupe_key: 'v1:CANDIDATE_UPDATED:stable-operation',
      related_table: 'candidates',
      related_id: 'candidate-1',
      title: 'Candidate updated',
      message: 'First delivery text',
    }
    const first = await mutateNotification('create', null, payload)
    const second = await mutateNotification('create', null, {
      ...payload,
      message: 'Retry delivery text changed',
      response_at: new Date().toISOString(),
    })

    assert.equal(second.id, first.id)
    const count = await db.query(
      `select count(*)::integer as count
       from public.notification_events
       where company_id = $1::uuid
         and dedupe_key like 'notification:create:CANDIDATE_UPDATED:%'`,
      [COMPANY_ONE]
    )
    assert.equal(count.rows[0].count, 1)
  })

  test('agency user cannot mutate another company notification in the same agency', async () => {
    await db.query(
      `insert into public.agency_company_user_access (
        user_id, company_id, agency_id, status
      ) values ($1::bigint, $2::uuid, $3::uuid, 'Active')`,
      [agencyActorId, COMPANY_ONE, AGENCY_ONE]
    )
    const rows = await db.query(
      `insert into public.notification_events (
        company_id, agency_id, recipient_role, type, title, message, status, dedupe_key
      ) values
        ($1::uuid, $3::uuid, 'Agency', 'CANDIDATE_UPDATED', 'Allowed', 'Allowed', 'Unread', 'tenant-one'),
        ($2::uuid, $3::uuid, 'Agency', 'CANDIDATE_UPDATED', 'Denied', 'Denied', 'Unread', 'tenant-two')
      returning id, company_id`,
      [COMPANY_ONE, COMPANY_TWO, AGENCY_ONE]
    )
    const allowedId = rows.rows.find((row) => row.company_id === COMPANY_ONE).id
    const deniedId = rows.rows.find((row) => row.company_id === COMPANY_TWO).id

    await setActor(AGENCY_ACTOR_AUTH)
    const eligibleBefore = await db.query(
      `select count(*)::integer as count
       from public.notification_events
       where company_id = $1::uuid
         and agency_id = $2::uuid
         and status <> 'Read'
         and (user_id is null or user_id = $3::uuid)
         and (recipient_role is null or recipient_role = 'Agency')`,
      [COMPANY_ONE, AGENCY_ONE, AGENCY_ACTOR_AUTH]
    )
    await assert.rejects(() => mutateNotification('mark_read', deniedId), /notification_access_denied/)
    await assert.rejects(() => mutateNotification('delete', deniedId), /notification_access_denied/)
    const markAll = await mutateNotification('mark_all_read', null)
    assert.equal(markAll.updated, eligibleBefore.rows[0].count)

    const state = await db.query(
      `select id, status from public.notification_events
       where id in ($1::bigint, $2::bigint) order by id`,
      [allowedId, deniedId]
    )
    assert.deepEqual(
      state.rows.map((row) => row.status),
      ['Read', 'Unread']
    )
  })

  test('non-recipient cannot update or delete another user notification', async () => {
    const inserted = await db.query(
      `insert into public.notification_events (
        company_id, user_id, type, title, message, status, dedupe_key
      ) values (
        $1::uuid, $2::uuid, 'CANDIDATE_UPDATED',
        'Private', 'Private', 'Unread', 'recipient-private'
      ) returning id`,
      [COMPANY_ONE, OTHER_RECIPIENT_AUTH]
    )
    await setActor(COMPANY_ACTOR_AUTH)
    await assert.rejects(
      () => mutateNotification('mark_read', inserted.rows[0].id),
      /notification_access_denied/
    )
    await assert.rejects(
      () => mutateNotification('delete', inserted.rows[0].id),
      /notification_access_denied/
    )
  })

  test('authorization with timeline events cannot be deleted', async () => {
    await setActor(COMPANY_ACTOR_AUTH)
    const allocationId = await createAllocation()
    const created = await mutateAuthorization(
      'create',
      null,
      createInput(allocationId, 'AUTH-IMMUTABLE'),
      '40000000-0000-4000-8000-000000000004'
    )

    await assert.rejects(
      () => db.query(
        'delete from public.visa_authorizations where id = $1::uuid',
        [created.authorization.id]
      ),
      /foreign key constraint/
    )
    const eventCount = await db.query(
      'select count(*)::integer as count from public.authorization_events where authorization_id = $1::uuid',
      [created.authorization.id]
    )
    assert.equal(eventCount.rows[0].count, 1)
  })
})
