import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { after, before, describe, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const COMPANY_A = "10000000-0000-4000-8000-000000000001";
const COMPANY_B = "10000000-0000-4000-8000-000000000002";
const RECRUITMENT_MANAGER = "20000000-0000-4000-8000-000000000001";
const COMPANY_ADMIN = "20000000-0000-4000-8000-000000000002";
const ADMIN = "20000000-0000-4000-8000-000000000003";
const UNAUTHORIZED_USER = "20000000-0000-4000-8000-000000000004";
const INACTIVE_MANAGER = "20000000-0000-4000-8000-000000000005";
const COMPANY_B_ADMIN = "20000000-0000-4000-8000-000000000006";

const fixtureSql = `
create schema auth;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.companies (
  id uuid primary key,
  name text not null,
  status text not null
);

create table public.agencies (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text,
  country text,
  status text,
  contact_person text,
  email text,
  phone text,
  updated_at timestamptz default now(),
  company_id uuid references public.companies(id)
);

create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  company_id uuid references public.companies(id),
  name text,
  email text,
  role text not null,
  status text not null,
  is_active boolean not null default true
);

create table public.company_agency_access (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id),
  agency_id uuid not null references public.agencies(id),
  status text not null default 'Active',
  can_view_requests boolean not null default true,
  can_upload_candidates boolean not null default true,
  can_update_candidates boolean not null default true,
  can_view_interviews boolean not null default true,
  created_at timestamptz not null default now(),
  unique (company_id, agency_id)
);

grant usage on schema public, auth to authenticated;
grant execute on function auth.uid() to authenticated;
grant select on table public.companies, public.users, public.agencies,
  public.company_agency_access to authenticated;

alter table public.agencies enable row level security;
alter table public.company_agency_access enable row level security;

create policy agencies_tenant_select
on public.agencies
for select to authenticated
using (
  exists (
    select 1
    from public.users as actor
    join public.company_agency_access as access
      on access.company_id = actor.company_id
     and access.agency_id = agencies.id
     and access.status <> 'Inactive'
    where actor.auth_user_id = auth.uid()
      and actor.status = 'Active'
      and actor.is_active is true
  )
);

create policy company_agency_access_tenant_select
on public.company_agency_access
for select to authenticated
using (
  company_id = (
    select actor.company_id
    from public.users as actor
    where actor.auth_user_id = auth.uid()
      and actor.status = 'Active'
      and actor.is_active is true
  )
);
`;

let db;
let migration;

async function setActor(authUserId) {
  await db.exec("reset role");
  await db.query(
    "select set_config('request.jwt.claim.sub', $1::text, false)",
    [authUserId]
  );
}

async function asAuthenticated(authUserId, callback) {
  await setActor(authUserId);
  await db.exec("set role authenticated");
  try {
    return await callback();
  } finally {
    await db.exec("reset role");
  }
}

async function createAgency(authUserId, payload) {
  return asAuthenticated(authUserId, async () => {
    const result = await db.query(
      "select public.company_agency_create($1::jsonb) as result",
      [JSON.stringify(payload)]
    );
    return result.rows[0].result;
  });
}

async function expectCreateError(authUserId, payload, code) {
  await assert.rejects(
    createAgency(authUserId, payload),
    (error) => String(error?.message || error).includes(code)
  );
}

describe("company_agency_create on temporary PostgreSQL", () => {
  before(async () => {
    db = new PGlite();
    migration = await readFile(
      new URL(
        "../supabase/migrations/20260730000100_add_company_agency_create_rpc.sql",
        import.meta.url
      ),
      "utf8"
    );

    await db.exec(fixtureSql);
    await db.exec(`
      insert into public.companies (id, name, status) values
        ('${COMPANY_A}', 'Company A', 'Active'),
        ('${COMPANY_B}', 'Company B', 'Active');

      insert into public.users (
        auth_user_id, company_id, name, email, role, status, is_active
      ) values
        ('${RECRUITMENT_MANAGER}', '${COMPANY_A}', 'RM', 'rm@example.test', 'Recruitment Manager', 'Active', true),
        ('${COMPANY_ADMIN}', '${COMPANY_A}', 'Company Admin', 'ca@example.test', 'Company Admin', 'Active', true),
        ('${ADMIN}', '${COMPANY_A}', 'Admin', 'admin@example.test', 'Admin', 'Active', true),
        ('${UNAUTHORIZED_USER}', '${COMPANY_A}', 'Officer', 'officer@example.test', 'Recruitment Officer', 'Active', true),
        ('${INACTIVE_MANAGER}', '${COMPANY_A}', 'Inactive RM', 'inactive@example.test', 'Recruitment Manager', 'Inactive', false),
        ('${COMPANY_B_ADMIN}', '${COMPANY_B}', 'Company B Admin', 'admin-b@example.test', 'Admin', 'Active', true);
    `);
    await db.exec(migration);
  });

  after(async () => {
    await db?.close();
  });

  test("active Recruitment Manager creates an agency linked to the actor company", async () => {
    const result = await createAgency(RECRUITMENT_MANAGER, {
      name: "RM Agency",
      country: "India",
      email: "rm-agency@example.test",
      status: "Active",
    });

    assert.equal(result.company_id, COMPANY_A);
    assert.equal(result.status, "Active");
    assert.equal(result.link_status, "Active");
    assert.equal(result.idempotent, false);

    const stored = await db.query(
      `select agency.company_id, access.company_id as linked_company_id
       from public.agencies agency
       join public.company_agency_access access on access.agency_id = agency.id
       where agency.id = $1::uuid`,
      [result.agency_id]
    );
    assert.deepEqual(stored.rows[0], {
      company_id: COMPANY_A,
      linked_company_id: COMPANY_A,
    });
  });

  test("Company Admin and Admin roles can create agencies", async () => {
    const companyAdminResult = await createAgency(COMPANY_ADMIN, {
      name: "Company Admin Agency",
      country: "Philippines",
      email: "company-admin-agency@example.test",
    });
    const adminResult = await createAgency(ADMIN, {
      name: "Admin Agency",
      country: "Pakistan",
      email: "admin-agency@example.test",
    });

    assert.equal(companyAdminResult.company_id, COMPANY_A);
    assert.equal(adminResult.company_id, COMPANY_A);
  });

  test("an unauthorized role is rejected", async () => {
    await expectCreateError(
      UNAUTHORIZED_USER,
      { name: "Unauthorized Agency", country: "India" },
      "COMPANY_AGENCY_CREATE_UNAUTHORIZED"
    );
  });

  test("an inactive user is rejected", async () => {
    await expectCreateError(
      INACTIVE_MANAGER,
      { name: "Inactive Agency", country: "India" },
      "COMPANY_AGENCY_CREATE_USER_INACTIVE"
    );
  });

  test("client supplied company_id is rejected", async () => {
    await expectCreateError(
      RECRUITMENT_MANAGER,
      {
        name: "Cross Tenant Payload",
        country: "India",
        company_id: COMPANY_B,
      },
      "COMPANY_AGENCY_CREATE_INVALID_FIELDS"
    );
  });

  test("Company A cannot create or link an agency for Company B", async () => {
    const companyBAgency = await createAgency(COMPANY_B_ADMIN, {
      name: "Company B Owned Agency",
      country: "Bangladesh",
      email: "company-b-owned@example.test",
    });

    await expectCreateError(
      RECRUITMENT_MANAGER,
      {
        name: "Company B Owned Agency",
        country: "Bangladesh",
        email: "company-b-owned@example.test",
      },
      "COMPANY_AGENCY_CREATE_ALREADY_EXISTS"
    );

    const links = await db.query(
      `select company_id
       from public.company_agency_access
       where agency_id = $1::uuid`,
      [companyBAgency.agency_id]
    );
    assert.deepEqual(links.rows.map((row) => row.company_id), [COMPANY_B]);
  });

  test("retrying the same logical agency is idempotent without another row", async () => {
    const payload = {
      name: "Idempotent Agency",
      country: "India",
      email: "idempotent@example.test",
    };
    const first = await createAgency(RECRUITMENT_MANAGER, payload);
    const second = await createAgency(RECRUITMENT_MANAGER, payload);

    assert.equal(second.agency_id, first.agency_id);
    assert.equal(second.idempotent, true);

    const count = await db.query(
      `select count(*)::integer as count
       from public.agencies
       where lower(email) = lower($1)`,
      [payload.email]
    );
    assert.equal(count.rows[0].count, 1);
  });

  test("the authorized tenant can select the agency after creation", async () => {
    const result = await createAgency(RECRUITMENT_MANAGER, {
      name: "Visible Agency",
      country: "India",
      email: "visible@example.test",
    });

    const visible = await asAuthenticated(RECRUITMENT_MANAGER, () =>
      db.query(
        "select id, name from public.agencies where id = $1::uuid",
        [result.agency_id]
      )
    );
    assert.equal(visible.rows.length, 1);
    assert.equal(visible.rows[0].name, "Visible Agency");
  });

  test("a user in another company cannot select the created agency", async () => {
    const result = await createAgency(RECRUITMENT_MANAGER, {
      name: "Company A Only Agency",
      country: "India",
      email: "company-a-only@example.test",
    });

    const hidden = await asAuthenticated(COMPANY_B_ADMIN, () =>
      db.query(
        "select id from public.agencies where id = $1::uuid",
        [result.agency_id]
      )
    );
    assert.equal(hidden.rows.length, 0);
  });

  test("authenticated has no direct INSERT privilege on protected agency tables", async () => {
    const privileges = await db.query(`
      select
        has_table_privilege('authenticated', 'public.agencies', 'INSERT') as agencies_insert,
        has_table_privilege('authenticated', 'public.company_agency_access', 'INSERT') as access_insert,
        has_table_privilege('authenticated', 'public.agencies', 'UPDATE') as agencies_update,
        has_table_privilege('authenticated', 'public.company_agency_access', 'UPDATE') as access_update,
        has_table_privilege('authenticated', 'public.agencies', 'DELETE') as agencies_delete,
        has_table_privilege('authenticated', 'public.company_agency_access', 'DELETE') as access_delete
    `);
    assert.deepEqual(privileges.rows[0], {
      agencies_insert: false,
      access_insert: false,
      agencies_update: false,
      access_update: false,
      agencies_delete: false,
      access_delete: false,
    });

    await asAuthenticated(RECRUITMENT_MANAGER, async () => {
      await assert.rejects(
        db.query(
          `insert into public.agencies (name, country, status)
           values ('Direct Insert', 'India', 'Active')`
        ),
        /permission denied for table agencies/
      );
    });
  });
});
