export const EXPANDED_TALENT_CAMPAIGNS = [
  {
    "slug": "sales-service-2026",
    "nameAr": "حملة المبيعات وخدمة العملاء",
    "nameEn": "Sales & Customer Service Campaign",
    "descriptionAr": "١٥ قالب مقابلة في المبيعات وخدمة العملاء: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Sales & Customer Service: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — المبيعات وخدمة العملاء",
    "badgeEn": "VisaFlow — Sales & Customer Service",
    "headlineAr": "اختبر جاهزيتك في المبيعات وخدمة العملاء.",
    "headlineEn": "Test your readiness in Sales & Customer Service.",
    "introAr": "اختر المسار والمستوى المناسبين. كل مقابلة تتضمن ٨ أسئلة بالعربية أو الإنجليزية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. Each interview has 8 questions in Arabic or English. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "supply-chain-2026",
    "nameAr": "حملة المشتريات وسلاسل الإمداد",
    "nameEn": "Procurement & Supply Chain Campaign",
    "descriptionAr": "١٥ قالب مقابلة في المشتريات وسلاسل الإمداد: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Procurement & Supply Chain: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — المشتريات وسلاسل الإمداد",
    "badgeEn": "VisaFlow — Procurement & Supply Chain",
    "headlineAr": "اختبر جاهزيتك في المشتريات وسلاسل الإمداد.",
    "headlineEn": "Test your readiness in Procurement & Supply Chain.",
    "introAr": "اختر المسار والمستوى المناسبين. كل مقابلة تتضمن ٨ أسئلة بالعربية أو الإنجليزية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. Each interview has 8 questions in Arabic or English. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "administration-operations-2026",
    "nameAr": "حملة الإدارة والتشغيل",
    "nameEn": "Administration & Operations Campaign",
    "descriptionAr": "١٥ قالب مقابلة في الإدارة والتشغيل: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Administration & Operations: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — الإدارة والتشغيل",
    "badgeEn": "VisaFlow — Administration & Operations",
    "headlineAr": "اختبر جاهزيتك في الإدارة والتشغيل.",
    "headlineEn": "Test your readiness in Administration & Operations.",
    "introAr": "اختر المسار والمستوى المناسبين. كل مقابلة تتضمن ٨ أسئلة بالعربية أو الإنجليزية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. Each interview has 8 questions in Arabic or English. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "safety-security-2026",
    "nameAr": "حملة السلامة والأمن",
    "nameEn": "Safety & Security Campaign",
    "descriptionAr": "١٥ قالب مقابلة في السلامة والأمن: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Safety & Security: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — السلامة والأمن",
    "badgeEn": "VisaFlow — Safety & Security",
    "headlineAr": "اختبر جاهزيتك في السلامة والأمن.",
    "headlineEn": "Test your readiness in Safety & Security.",
    "introAr": "اختر المسار والمستوى المناسبين. كل مقابلة تتضمن ٨ أسئلة بالعربية أو الإنجليزية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. Each interview has 8 questions in Arabic or English. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "marketing-ecommerce-2026",
    "nameAr": "حملة التسويق والتجارة الإلكترونية",
    "nameEn": "Marketing & E-commerce Campaign",
    "descriptionAr": "١٥ قالب مقابلة في التسويق والتجارة الإلكترونية: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Marketing & E-commerce: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — التسويق والتجارة الإلكترونية",
    "badgeEn": "VisaFlow — Marketing & E-commerce",
    "headlineAr": "اختبر جاهزيتك في التسويق والتجارة الإلكترونية.",
    "headlineEn": "Test your readiness in Marketing & E-commerce.",
    "introAr": "اختر المسار والمستوى المناسبين. كل مقابلة تتضمن ٨ أسئلة بالعربية أو الإنجليزية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. Each interview has 8 questions in Arabic or English. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "hospitality-restaurants-2026",
    "nameAr": "حملة الضيافة والمطاعم",
    "nameEn": "Hospitality & Restaurants Campaign",
    "descriptionAr": "١٥ قالب مقابلة في الضيافة والمطاعم: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Hospitality & Restaurants: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — الضيافة والمطاعم",
    "badgeEn": "VisaFlow — Hospitality & Restaurants",
    "headlineAr": "اختبر جاهزيتك في الضيافة والمطاعم.",
    "headlineEn": "Test your readiness in Hospitality & Restaurants.",
    "introAr": "اختر المسار والمستوى المناسبين. كل مقابلة تتضمن ٨ أسئلة بالعربية أو الإنجليزية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. Each interview has 8 questions in Arabic or English. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  }
];
