// Public catalog metadata only. Questions and scoring references remain in the database.
export const EXPANDED_INTERVIEW_CATALOG = [
  {
    "profession": "Sales Representative — Entry Level",
    "profession_ar": "مندوب مبيعات — مبتدئ",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "مندوب مبيعات — مبتدئ: تأهيل عميل محتمل وإعداد عرض مناسب. Sales Representative — Entry Level: qualify a prospect and prepare a suitable proposal.",
    "job_description": "مندوب مبيعات — مبتدئ: تأهيل عميل محتمل وإعداد عرض مناسب. Sales Representative — Entry Level: qualify a prospect and prepare a suitable proposal.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Sales Representative — Professional",
    "profession_ar": "مندوب مبيعات — ممارس",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "مندوب مبيعات — ممارس: تأهيل عميل محتمل وإعداد عرض مناسب. Sales Representative — Professional: qualify a prospect and prepare a suitable proposal.",
    "job_description": "مندوب مبيعات — ممارس: تأهيل عميل محتمل وإعداد عرض مناسب. Sales Representative — Professional: qualify a prospect and prepare a suitable proposal.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Sales Representative — Team Supervisor",
    "profession_ar": "مندوب مبيعات — مشرف فريق",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "مندوب مبيعات — مشرف فريق: تأهيل عميل محتمل وإعداد عرض مناسب. Sales Representative — Team Supervisor: qualify a prospect and prepare a suitable proposal.",
    "job_description": "مندوب مبيعات — مشرف فريق: تأهيل عميل محتمل وإعداد عرض مناسب. Sales Representative — Team Supervisor: qualify a prospect and prepare a suitable proposal.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Customer Service Agent — Entry Level",
    "profession_ar": "موظف خدمة عملاء — مبتدئ",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف خدمة عملاء — مبتدئ: فهم الشكوى وتسجيلها وإغلاقها مع العميل. Customer Service Agent — Entry Level: understand, log and close a customer complaint.",
    "job_description": "موظف خدمة عملاء — مبتدئ: فهم الشكوى وتسجيلها وإغلاقها مع العميل. Customer Service Agent — Entry Level: understand, log and close a customer complaint.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Customer Service Agent — Professional",
    "profession_ar": "موظف خدمة عملاء — ممارس",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف خدمة عملاء — ممارس: فهم الشكوى وتسجيلها وإغلاقها مع العميل. Customer Service Agent — Professional: understand, log and close a customer complaint.",
    "job_description": "موظف خدمة عملاء — ممارس: فهم الشكوى وتسجيلها وإغلاقها مع العميل. Customer Service Agent — Professional: understand, log and close a customer complaint.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Customer Service Agent — Team Supervisor",
    "profession_ar": "موظف خدمة عملاء — مشرف فريق",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف خدمة عملاء — مشرف فريق: فهم الشكوى وتسجيلها وإغلاقها مع العميل. Customer Service Agent — Team Supervisor: understand, log and close a customer complaint.",
    "job_description": "موظف خدمة عملاء — مشرف فريق: فهم الشكوى وتسجيلها وإغلاقها مع العميل. Customer Service Agent — Team Supervisor: understand, log and close a customer complaint.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Contact Center Agent — Entry Level",
    "profession_ar": "موظف مركز اتصال — مبتدئ",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف مركز اتصال — مبتدئ: إدارة مكالمة وتوثيق سبب الاتصال والإجراء. Contact Center Agent — Entry Level: handle a call and document its reason and action.",
    "job_description": "موظف مركز اتصال — مبتدئ: إدارة مكالمة وتوثيق سبب الاتصال والإجراء. Contact Center Agent — Entry Level: handle a call and document its reason and action.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Contact Center Agent — Professional",
    "profession_ar": "موظف مركز اتصال — ممارس",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف مركز اتصال — ممارس: إدارة مكالمة وتوثيق سبب الاتصال والإجراء. Contact Center Agent — Professional: handle a call and document its reason and action.",
    "job_description": "موظف مركز اتصال — ممارس: إدارة مكالمة وتوثيق سبب الاتصال والإجراء. Contact Center Agent — Professional: handle a call and document its reason and action.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Contact Center Agent — Team Supervisor",
    "profession_ar": "موظف مركز اتصال — مشرف فريق",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف مركز اتصال — مشرف فريق: إدارة مكالمة وتوثيق سبب الاتصال والإجراء. Contact Center Agent — Team Supervisor: handle a call and document its reason and action.",
    "job_description": "موظف مركز اتصال — مشرف فريق: إدارة مكالمة وتوثيق سبب الاتصال والإجراء. Contact Center Agent — Team Supervisor: handle a call and document its reason and action.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Account Executive — Entry Level",
    "profession_ar": "مسؤول حسابات عملاء — مبتدئ",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "مسؤول حسابات عملاء — مبتدئ: إعداد خطة متابعة لحساب تجاري. Account Executive — Entry Level: prepare a follow-up plan for a business account.",
    "job_description": "مسؤول حسابات عملاء — مبتدئ: إعداد خطة متابعة لحساب تجاري. Account Executive — Entry Level: prepare a follow-up plan for a business account.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Account Executive — Professional",
    "profession_ar": "مسؤول حسابات عملاء — ممارس",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "مسؤول حسابات عملاء — ممارس: إعداد خطة متابعة لحساب تجاري. Account Executive — Professional: prepare a follow-up plan for a business account.",
    "job_description": "مسؤول حسابات عملاء — ممارس: إعداد خطة متابعة لحساب تجاري. Account Executive — Professional: prepare a follow-up plan for a business account.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Account Executive — Team Supervisor",
    "profession_ar": "مسؤول حسابات عملاء — مشرف فريق",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "مسؤول حسابات عملاء — مشرف فريق: إعداد خطة متابعة لحساب تجاري. Account Executive — Team Supervisor: prepare a follow-up plan for a business account.",
    "job_description": "مسؤول حسابات عملاء — مشرف فريق: إعداد خطة متابعة لحساب تجاري. Account Executive — Team Supervisor: prepare a follow-up plan for a business account.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Retail Sales Associate — Entry Level",
    "profession_ar": "موظف مبيعات تجزئة — مبتدئ",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف مبيعات تجزئة — مبتدئ: مساعدة المتسوق واختيار منتج وتأكيد السعر. Retail Sales Associate — Entry Level: assist a shopper, select a product and confirm pricing.",
    "job_description": "موظف مبيعات تجزئة — مبتدئ: مساعدة المتسوق واختيار منتج وتأكيد السعر. Retail Sales Associate — Entry Level: assist a shopper, select a product and confirm pricing.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Retail Sales Associate — Professional",
    "profession_ar": "موظف مبيعات تجزئة — ممارس",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف مبيعات تجزئة — ممارس: مساعدة المتسوق واختيار منتج وتأكيد السعر. Retail Sales Associate — Professional: assist a shopper, select a product and confirm pricing.",
    "job_description": "موظف مبيعات تجزئة — ممارس: مساعدة المتسوق واختيار منتج وتأكيد السعر. Retail Sales Associate — Professional: assist a shopper, select a product and confirm pricing.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Retail Sales Associate — Team Supervisor",
    "profession_ar": "موظف مبيعات تجزئة — مشرف فريق",
    "category": "Sales & Customer Service",
    "library": "Sales & Customer Service",
    "focus": "موظف مبيعات تجزئة — مشرف فريق: مساعدة المتسوق واختيار منتج وتأكيد السعر. Retail Sales Associate — Team Supervisor: assist a shopper, select a product and confirm pricing.",
    "job_description": "موظف مبيعات تجزئة — مشرف فريق: مساعدة المتسوق واختيار منتج وتأكيد السعر. Retail Sales Associate — Team Supervisor: assist a shopper, select a product and confirm pricing.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Procurement Officer — Entry Level",
    "profession_ar": "موظف مشتريات — مبتدئ",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "موظف مشتريات — مبتدئ: مقارنة عروض موردين لطلب شراء. Procurement Officer — Entry Level: compare supplier quotations for a purchase request.",
    "job_description": "موظف مشتريات — مبتدئ: مقارنة عروض موردين لطلب شراء. Procurement Officer — Entry Level: compare supplier quotations for a purchase request.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Procurement Officer — Professional",
    "profession_ar": "موظف مشتريات — ممارس",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "موظف مشتريات — ممارس: مقارنة عروض موردين لطلب شراء. Procurement Officer — Professional: compare supplier quotations for a purchase request.",
    "job_description": "موظف مشتريات — ممارس: مقارنة عروض موردين لطلب شراء. Procurement Officer — Professional: compare supplier quotations for a purchase request.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Procurement Officer — Team Supervisor",
    "profession_ar": "موظف مشتريات — مشرف فريق",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "موظف مشتريات — مشرف فريق: مقارنة عروض موردين لطلب شراء. Procurement Officer — Team Supervisor: compare supplier quotations for a purchase request.",
    "job_description": "موظف مشتريات — مشرف فريق: مقارنة عروض موردين لطلب شراء. Procurement Officer — Team Supervisor: compare supplier quotations for a purchase request.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Warehouse Associate — Entry Level",
    "profession_ar": "موظف مستودع — مبتدئ",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "موظف مستودع — مبتدئ: استلام شحنة وتخزينها مع تسجيل الكميات. Warehouse Associate — Entry Level: receive, store and record an inbound shipment.",
    "job_description": "موظف مستودع — مبتدئ: استلام شحنة وتخزينها مع تسجيل الكميات. Warehouse Associate — Entry Level: receive, store and record an inbound shipment.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Warehouse Associate — Professional",
    "profession_ar": "موظف مستودع — ممارس",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "موظف مستودع — ممارس: استلام شحنة وتخزينها مع تسجيل الكميات. Warehouse Associate — Professional: receive, store and record an inbound shipment.",
    "job_description": "موظف مستودع — ممارس: استلام شحنة وتخزينها مع تسجيل الكميات. Warehouse Associate — Professional: receive, store and record an inbound shipment.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Warehouse Associate — Team Supervisor",
    "profession_ar": "موظف مستودع — مشرف فريق",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "موظف مستودع — مشرف فريق: استلام شحنة وتخزينها مع تسجيل الكميات. Warehouse Associate — Team Supervisor: receive, store and record an inbound shipment.",
    "job_description": "موظف مستودع — مشرف فريق: استلام شحنة وتخزينها مع تسجيل الكميات. Warehouse Associate — Team Supervisor: receive, store and record an inbound shipment.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Inventory Controller — Entry Level",
    "profession_ar": "مراقب مخزون — مبتدئ",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "مراقب مخزون — مبتدئ: تنفيذ جرد دوري وتسوية فروقه. Inventory Controller — Entry Level: perform cycle counting and investigate discrepancies.",
    "job_description": "مراقب مخزون — مبتدئ: تنفيذ جرد دوري وتسوية فروقه. Inventory Controller — Entry Level: perform cycle counting and investigate discrepancies.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Inventory Controller — Professional",
    "profession_ar": "مراقب مخزون — ممارس",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "مراقب مخزون — ممارس: تنفيذ جرد دوري وتسوية فروقه. Inventory Controller — Professional: perform cycle counting and investigate discrepancies.",
    "job_description": "مراقب مخزون — ممارس: تنفيذ جرد دوري وتسوية فروقه. Inventory Controller — Professional: perform cycle counting and investigate discrepancies.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Inventory Controller — Team Supervisor",
    "profession_ar": "مراقب مخزون — مشرف فريق",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "مراقب مخزون — مشرف فريق: تنفيذ جرد دوري وتسوية فروقه. Inventory Controller — Team Supervisor: perform cycle counting and investigate discrepancies.",
    "job_description": "مراقب مخزون — مشرف فريق: تنفيذ جرد دوري وتسوية فروقه. Inventory Controller — Team Supervisor: perform cycle counting and investigate discrepancies.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Logistics Coordinator — Entry Level",
    "profession_ar": "منسق لوجستيات — مبتدئ",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "منسق لوجستيات — مبتدئ: تنسيق تسليم طلبات ومتابعة إثبات الاستلام. Logistics Coordinator — Entry Level: coordinate deliveries and track proof of delivery.",
    "job_description": "منسق لوجستيات — مبتدئ: تنسيق تسليم طلبات ومتابعة إثبات الاستلام. Logistics Coordinator — Entry Level: coordinate deliveries and track proof of delivery.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Logistics Coordinator — Professional",
    "profession_ar": "منسق لوجستيات — ممارس",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "منسق لوجستيات — ممارس: تنسيق تسليم طلبات ومتابعة إثبات الاستلام. Logistics Coordinator — Professional: coordinate deliveries and track proof of delivery.",
    "job_description": "منسق لوجستيات — ممارس: تنسيق تسليم طلبات ومتابعة إثبات الاستلام. Logistics Coordinator — Professional: coordinate deliveries and track proof of delivery.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Logistics Coordinator — Team Supervisor",
    "profession_ar": "منسق لوجستيات — مشرف فريق",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "منسق لوجستيات — مشرف فريق: تنسيق تسليم طلبات ومتابعة إثبات الاستلام. Logistics Coordinator — Team Supervisor: coordinate deliveries and track proof of delivery.",
    "job_description": "منسق لوجستيات — مشرف فريق: تنسيق تسليم طلبات ومتابعة إثبات الاستلام. Logistics Coordinator — Team Supervisor: coordinate deliveries and track proof of delivery.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Shipping Coordinator — Entry Level",
    "profession_ar": "منسق شحن — مبتدئ",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "منسق شحن — مبتدئ: مراجعة مستندات الشحنة قبل تسليمها للناقل. Shipping Coordinator — Entry Level: check shipment documents before carrier handover.",
    "job_description": "منسق شحن — مبتدئ: مراجعة مستندات الشحنة قبل تسليمها للناقل. Shipping Coordinator — Entry Level: check shipment documents before carrier handover.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Shipping Coordinator — Professional",
    "profession_ar": "منسق شحن — ممارس",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "منسق شحن — ممارس: مراجعة مستندات الشحنة قبل تسليمها للناقل. Shipping Coordinator — Professional: check shipment documents before carrier handover.",
    "job_description": "منسق شحن — ممارس: مراجعة مستندات الشحنة قبل تسليمها للناقل. Shipping Coordinator — Professional: check shipment documents before carrier handover.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Shipping Coordinator — Team Supervisor",
    "profession_ar": "منسق شحن — مشرف فريق",
    "category": "Procurement & Supply Chain",
    "library": "Procurement & Supply Chain",
    "focus": "منسق شحن — مشرف فريق: مراجعة مستندات الشحنة قبل تسليمها للناقل. Shipping Coordinator — Team Supervisor: check shipment documents before carrier handover.",
    "job_description": "منسق شحن — مشرف فريق: مراجعة مستندات الشحنة قبل تسليمها للناقل. Shipping Coordinator — Team Supervisor: check shipment documents before carrier handover.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Administrative Assistant — Entry Level",
    "profession_ar": "مساعد إداري — مبتدئ",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "مساعد إداري — مبتدئ: تنظيم موعد واجتماع ومتابعة إجراءاته. Administrative Assistant — Entry Level: organize a meeting and follow up its actions.",
    "job_description": "مساعد إداري — مبتدئ: تنظيم موعد واجتماع ومتابعة إجراءاته. Administrative Assistant — Entry Level: organize a meeting and follow up its actions.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Administrative Assistant — Professional",
    "profession_ar": "مساعد إداري — ممارس",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "مساعد إداري — ممارس: تنظيم موعد واجتماع ومتابعة إجراءاته. Administrative Assistant — Professional: organize a meeting and follow up its actions.",
    "job_description": "مساعد إداري — ممارس: تنظيم موعد واجتماع ومتابعة إجراءاته. Administrative Assistant — Professional: organize a meeting and follow up its actions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Administrative Assistant — Team Supervisor",
    "profession_ar": "مساعد إداري — مشرف فريق",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "مساعد إداري — مشرف فريق: تنظيم موعد واجتماع ومتابعة إجراءاته. Administrative Assistant — Team Supervisor: organize a meeting and follow up its actions.",
    "job_description": "مساعد إداري — مشرف فريق: تنظيم موعد واجتماع ومتابعة إجراءاته. Administrative Assistant — Team Supervisor: organize a meeting and follow up its actions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Operations Coordinator — Entry Level",
    "profession_ar": "منسق عمليات — مبتدئ",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "منسق عمليات — مبتدئ: تسليم مهام تشغيلية بين ورديتين. Operations Coordinator — Entry Level: handover operational tasks between shifts.",
    "job_description": "منسق عمليات — مبتدئ: تسليم مهام تشغيلية بين ورديتين. Operations Coordinator — Entry Level: handover operational tasks between shifts.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Operations Coordinator — Professional",
    "profession_ar": "منسق عمليات — ممارس",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "منسق عمليات — ممارس: تسليم مهام تشغيلية بين ورديتين. Operations Coordinator — Professional: handover operational tasks between shifts.",
    "job_description": "منسق عمليات — ممارس: تسليم مهام تشغيلية بين ورديتين. Operations Coordinator — Professional: handover operational tasks between shifts.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Operations Coordinator — Team Supervisor",
    "profession_ar": "منسق عمليات — مشرف فريق",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "منسق عمليات — مشرف فريق: تسليم مهام تشغيلية بين ورديتين. Operations Coordinator — Team Supervisor: handover operational tasks between shifts.",
    "job_description": "منسق عمليات — مشرف فريق: تسليم مهام تشغيلية بين ورديتين. Operations Coordinator — Team Supervisor: handover operational tasks between shifts.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Document Controller — Entry Level",
    "profession_ar": "مراقب وثائق — مبتدئ",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "مراقب وثائق — مبتدئ: إصدار وثيقة محدثة وضبط نسخها. Document Controller — Entry Level: issue an updated document and control its versions.",
    "job_description": "مراقب وثائق — مبتدئ: إصدار وثيقة محدثة وضبط نسخها. Document Controller — Entry Level: issue an updated document and control its versions.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Document Controller — Professional",
    "profession_ar": "مراقب وثائق — ممارس",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "مراقب وثائق — ممارس: إصدار وثيقة محدثة وضبط نسخها. Document Controller — Professional: issue an updated document and control its versions.",
    "job_description": "مراقب وثائق — ممارس: إصدار وثيقة محدثة وضبط نسخها. Document Controller — Professional: issue an updated document and control its versions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Document Controller — Team Supervisor",
    "profession_ar": "مراقب وثائق — مشرف فريق",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "مراقب وثائق — مشرف فريق: إصدار وثيقة محدثة وضبط نسخها. Document Controller — Team Supervisor: issue an updated document and control its versions.",
    "job_description": "مراقب وثائق — مشرف فريق: إصدار وثيقة محدثة وضبط نسخها. Document Controller — Team Supervisor: issue an updated document and control its versions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Office Administrator — Entry Level",
    "profession_ar": "إداري مكتب — مبتدئ",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "إداري مكتب — مبتدئ: تنسيق خدمات المكتب والطلبات اليومية. Office Administrator — Entry Level: coordinate office services and daily requests.",
    "job_description": "إداري مكتب — مبتدئ: تنسيق خدمات المكتب والطلبات اليومية. Office Administrator — Entry Level: coordinate office services and daily requests.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Office Administrator — Professional",
    "profession_ar": "إداري مكتب — ممارس",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "إداري مكتب — ممارس: تنسيق خدمات المكتب والطلبات اليومية. Office Administrator — Professional: coordinate office services and daily requests.",
    "job_description": "إداري مكتب — ممارس: تنسيق خدمات المكتب والطلبات اليومية. Office Administrator — Professional: coordinate office services and daily requests.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Office Administrator — Team Supervisor",
    "profession_ar": "إداري مكتب — مشرف فريق",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "إداري مكتب — مشرف فريق: تنسيق خدمات المكتب والطلبات اليومية. Office Administrator — Team Supervisor: coordinate office services and daily requests.",
    "job_description": "إداري مكتب — مشرف فريق: تنسيق خدمات المكتب والطلبات اليومية. Office Administrator — Team Supervisor: coordinate office services and daily requests.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Receptionist — Entry Level",
    "profession_ar": "موظف استقبال — مبتدئ",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "موظف استقبال — مبتدئ: استقبال زائر والتنسيق مع المضيف. Receptionist — Entry Level: receive a visitor and coordinate with the host.",
    "job_description": "موظف استقبال — مبتدئ: استقبال زائر والتنسيق مع المضيف. Receptionist — Entry Level: receive a visitor and coordinate with the host.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Receptionist — Professional",
    "profession_ar": "موظف استقبال — ممارس",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "موظف استقبال — ممارس: استقبال زائر والتنسيق مع المضيف. Receptionist — Professional: receive a visitor and coordinate with the host.",
    "job_description": "موظف استقبال — ممارس: استقبال زائر والتنسيق مع المضيف. Receptionist — Professional: receive a visitor and coordinate with the host.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Receptionist — Team Supervisor",
    "profession_ar": "موظف استقبال — مشرف فريق",
    "category": "Administration & Operations",
    "library": "Administration & Operations",
    "focus": "موظف استقبال — مشرف فريق: استقبال زائر والتنسيق مع المضيف. Receptionist — Team Supervisor: receive a visitor and coordinate with the host.",
    "job_description": "موظف استقبال — مشرف فريق: استقبال زائر والتنسيق مع المضيف. Receptionist — Team Supervisor: receive a visitor and coordinate with the host.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Safety Officer — Entry Level",
    "profession_ar": "مسؤول سلامة — مبتدئ",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "مسؤول سلامة — مبتدئ: رصد خطر ورفعه وفق إجراءات الموقع. Safety Officer — Entry Level: identify a hazard and report it under site procedures.",
    "job_description": "مسؤول سلامة — مبتدئ: رصد خطر ورفعه وفق إجراءات الموقع. Safety Officer — Entry Level: identify a hazard and report it under site procedures.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Safety Officer — Professional",
    "profession_ar": "مسؤول سلامة — ممارس",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "مسؤول سلامة — ممارس: رصد خطر ورفعه وفق إجراءات الموقع. Safety Officer — Professional: identify a hazard and report it under site procedures.",
    "job_description": "مسؤول سلامة — ممارس: رصد خطر ورفعه وفق إجراءات الموقع. Safety Officer — Professional: identify a hazard and report it under site procedures.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Safety Officer — Team Supervisor",
    "profession_ar": "مسؤول سلامة — مشرف فريق",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "مسؤول سلامة — مشرف فريق: رصد خطر ورفعه وفق إجراءات الموقع. Safety Officer — Team Supervisor: identify a hazard and report it under site procedures.",
    "job_description": "مسؤول سلامة — مشرف فريق: رصد خطر ورفعه وفق إجراءات الموقع. Safety Officer — Team Supervisor: identify a hazard and report it under site procedures.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Security Guard — Entry Level",
    "profession_ar": "حارس أمن — مبتدئ",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "حارس أمن — مبتدئ: التحقق من تصريح دخول وتسجيل الزيارة. Security Guard — Entry Level: verify access authorization and record a visit.",
    "job_description": "حارس أمن — مبتدئ: التحقق من تصريح دخول وتسجيل الزيارة. Security Guard — Entry Level: verify access authorization and record a visit.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Security Guard — Professional",
    "profession_ar": "حارس أمن — ممارس",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "حارس أمن — ممارس: التحقق من تصريح دخول وتسجيل الزيارة. Security Guard — Professional: verify access authorization and record a visit.",
    "job_description": "حارس أمن — ممارس: التحقق من تصريح دخول وتسجيل الزيارة. Security Guard — Professional: verify access authorization and record a visit.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Security Guard — Team Supervisor",
    "profession_ar": "حارس أمن — مشرف فريق",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "حارس أمن — مشرف فريق: التحقق من تصريح دخول وتسجيل الزيارة. Security Guard — Team Supervisor: verify access authorization and record a visit.",
    "job_description": "حارس أمن — مشرف فريق: التحقق من تصريح دخول وتسجيل الزيارة. Security Guard — Team Supervisor: verify access authorization and record a visit.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Security Control Room Operator — Entry Level",
    "profession_ar": "مشغل غرفة تحكم أمنية — مبتدئ",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "مشغل غرفة تحكم أمنية — مبتدئ: استلام تنبيه وتوثيق التصعيد والمتابعة. Security Control Room Operator — Entry Level: receive an alert and log escalation and follow-up.",
    "job_description": "مشغل غرفة تحكم أمنية — مبتدئ: استلام تنبيه وتوثيق التصعيد والمتابعة. Security Control Room Operator — Entry Level: receive an alert and log escalation and follow-up.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Security Control Room Operator — Professional",
    "profession_ar": "مشغل غرفة تحكم أمنية — ممارس",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "مشغل غرفة تحكم أمنية — ممارس: استلام تنبيه وتوثيق التصعيد والمتابعة. Security Control Room Operator — Professional: receive an alert and log escalation and follow-up.",
    "job_description": "مشغل غرفة تحكم أمنية — ممارس: استلام تنبيه وتوثيق التصعيد والمتابعة. Security Control Room Operator — Professional: receive an alert and log escalation and follow-up.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Security Control Room Operator — Team Supervisor",
    "profession_ar": "مشغل غرفة تحكم أمنية — مشرف فريق",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "مشغل غرفة تحكم أمنية — مشرف فريق: استلام تنبيه وتوثيق التصعيد والمتابعة. Security Control Room Operator — Team Supervisor: receive an alert and log escalation and follow-up.",
    "job_description": "مشغل غرفة تحكم أمنية — مشرف فريق: استلام تنبيه وتوثيق التصعيد والمتابعة. Security Control Room Operator — Team Supervisor: receive an alert and log escalation and follow-up.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Emergency Preparedness Coordinator — Entry Level",
    "profession_ar": "منسق جاهزية الطوارئ — مبتدئ",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "منسق جاهزية الطوارئ — مبتدئ: تنظيم تمرين إخلاء مع الجهات المسؤولة. Emergency Preparedness Coordinator — Entry Level: coordinate an evacuation drill with responsible teams.",
    "job_description": "منسق جاهزية الطوارئ — مبتدئ: تنظيم تمرين إخلاء مع الجهات المسؤولة. Emergency Preparedness Coordinator — Entry Level: coordinate an evacuation drill with responsible teams.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Emergency Preparedness Coordinator — Professional",
    "profession_ar": "منسق جاهزية الطوارئ — ممارس",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "منسق جاهزية الطوارئ — ممارس: تنظيم تمرين إخلاء مع الجهات المسؤولة. Emergency Preparedness Coordinator — Professional: coordinate an evacuation drill with responsible teams.",
    "job_description": "منسق جاهزية الطوارئ — ممارس: تنظيم تمرين إخلاء مع الجهات المسؤولة. Emergency Preparedness Coordinator — Professional: coordinate an evacuation drill with responsible teams.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Emergency Preparedness Coordinator — Team Supervisor",
    "profession_ar": "منسق جاهزية الطوارئ — مشرف فريق",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "منسق جاهزية الطوارئ — مشرف فريق: تنظيم تمرين إخلاء مع الجهات المسؤولة. Emergency Preparedness Coordinator — Team Supervisor: coordinate an evacuation drill with responsible teams.",
    "job_description": "منسق جاهزية الطوارئ — مشرف فريق: تنظيم تمرين إخلاء مع الجهات المسؤولة. Emergency Preparedness Coordinator — Team Supervisor: coordinate an evacuation drill with responsible teams.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Safety Inspection Coordinator — Entry Level",
    "profession_ar": "منسق تفتيش سلامة — مبتدئ",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "منسق تفتيش سلامة — مبتدئ: متابعة قائمة تفتيش وإغلاق الملاحظات. Safety Inspection Coordinator — Entry Level: track an inspection checklist and close findings.",
    "job_description": "منسق تفتيش سلامة — مبتدئ: متابعة قائمة تفتيش وإغلاق الملاحظات. Safety Inspection Coordinator — Entry Level: track an inspection checklist and close findings.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Safety Inspection Coordinator — Professional",
    "profession_ar": "منسق تفتيش سلامة — ممارس",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "منسق تفتيش سلامة — ممارس: متابعة قائمة تفتيش وإغلاق الملاحظات. Safety Inspection Coordinator — Professional: track an inspection checklist and close findings.",
    "job_description": "منسق تفتيش سلامة — ممارس: متابعة قائمة تفتيش وإغلاق الملاحظات. Safety Inspection Coordinator — Professional: track an inspection checklist and close findings.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Safety Inspection Coordinator — Team Supervisor",
    "profession_ar": "منسق تفتيش سلامة — مشرف فريق",
    "category": "Safety & Security",
    "library": "Safety & Security",
    "focus": "منسق تفتيش سلامة — مشرف فريق: متابعة قائمة تفتيش وإغلاق الملاحظات. Safety Inspection Coordinator — Team Supervisor: track an inspection checklist and close findings.",
    "job_description": "منسق تفتيش سلامة — مشرف فريق: متابعة قائمة تفتيش وإغلاق الملاحظات. Safety Inspection Coordinator — Team Supervisor: track an inspection checklist and close findings.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Digital Marketing Specialist — Entry Level",
    "profession_ar": "متخصص تسويق رقمي — مبتدئ",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص تسويق رقمي — مبتدئ: إعداد خطة قناة تسويقية وقياس نتيجتها. Digital Marketing Specialist — Entry Level: plan a marketing channel and measure its outcome.",
    "job_description": "متخصص تسويق رقمي — مبتدئ: إعداد خطة قناة تسويقية وقياس نتيجتها. Digital Marketing Specialist — Entry Level: plan a marketing channel and measure its outcome.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Digital Marketing Specialist — Professional",
    "profession_ar": "متخصص تسويق رقمي — ممارس",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص تسويق رقمي — ممارس: إعداد خطة قناة تسويقية وقياس نتيجتها. Digital Marketing Specialist — Professional: plan a marketing channel and measure its outcome.",
    "job_description": "متخصص تسويق رقمي — ممارس: إعداد خطة قناة تسويقية وقياس نتيجتها. Digital Marketing Specialist — Professional: plan a marketing channel and measure its outcome.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Digital Marketing Specialist — Team Supervisor",
    "profession_ar": "متخصص تسويق رقمي — مشرف فريق",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص تسويق رقمي — مشرف فريق: إعداد خطة قناة تسويقية وقياس نتيجتها. Digital Marketing Specialist — Team Supervisor: plan a marketing channel and measure its outcome.",
    "job_description": "متخصص تسويق رقمي — مشرف فريق: إعداد خطة قناة تسويقية وقياس نتيجتها. Digital Marketing Specialist — Team Supervisor: plan a marketing channel and measure its outcome.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Social Media Specialist — Entry Level",
    "profession_ar": "متخصص تواصل اجتماعي — مبتدئ",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص تواصل اجتماعي — مبتدئ: إعداد جدول محتوى وإدارة التفاعل. Social Media Specialist — Entry Level: prepare a content calendar and manage engagement.",
    "job_description": "متخصص تواصل اجتماعي — مبتدئ: إعداد جدول محتوى وإدارة التفاعل. Social Media Specialist — Entry Level: prepare a content calendar and manage engagement.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Social Media Specialist — Professional",
    "profession_ar": "متخصص تواصل اجتماعي — ممارس",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص تواصل اجتماعي — ممارس: إعداد جدول محتوى وإدارة التفاعل. Social Media Specialist — Professional: prepare a content calendar and manage engagement.",
    "job_description": "متخصص تواصل اجتماعي — ممارس: إعداد جدول محتوى وإدارة التفاعل. Social Media Specialist — Professional: prepare a content calendar and manage engagement.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Social Media Specialist — Team Supervisor",
    "profession_ar": "متخصص تواصل اجتماعي — مشرف فريق",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص تواصل اجتماعي — مشرف فريق: إعداد جدول محتوى وإدارة التفاعل. Social Media Specialist — Team Supervisor: prepare a content calendar and manage engagement.",
    "job_description": "متخصص تواصل اجتماعي — مشرف فريق: إعداد جدول محتوى وإدارة التفاعل. Social Media Specialist — Team Supervisor: prepare a content calendar and manage engagement.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Content Writer — Entry Level",
    "profession_ar": "كاتب محتوى — مبتدئ",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "كاتب محتوى — مبتدئ: تحويل موجز إلى نص مناسب للجمهور. Content Writer — Entry Level: turn a brief into audience-appropriate copy.",
    "job_description": "كاتب محتوى — مبتدئ: تحويل موجز إلى نص مناسب للجمهور. Content Writer — Entry Level: turn a brief into audience-appropriate copy.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Content Writer — Professional",
    "profession_ar": "كاتب محتوى — ممارس",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "كاتب محتوى — ممارس: تحويل موجز إلى نص مناسب للجمهور. Content Writer — Professional: turn a brief into audience-appropriate copy.",
    "job_description": "كاتب محتوى — ممارس: تحويل موجز إلى نص مناسب للجمهور. Content Writer — Professional: turn a brief into audience-appropriate copy.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Content Writer — Team Supervisor",
    "profession_ar": "كاتب محتوى — مشرف فريق",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "كاتب محتوى — مشرف فريق: تحويل موجز إلى نص مناسب للجمهور. Content Writer — Team Supervisor: turn a brief into audience-appropriate copy.",
    "job_description": "كاتب محتوى — مشرف فريق: تحويل موجز إلى نص مناسب للجمهور. Content Writer — Team Supervisor: turn a brief into audience-appropriate copy.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "E-commerce Coordinator — Entry Level",
    "profession_ar": "منسق تجارة إلكترونية — مبتدئ",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "منسق تجارة إلكترونية — مبتدئ: نشر صفحة منتج ومتابعة الطلب. E-commerce Coordinator — Entry Level: publish a product page and follow an order.",
    "job_description": "منسق تجارة إلكترونية — مبتدئ: نشر صفحة منتج ومتابعة الطلب. E-commerce Coordinator — Entry Level: publish a product page and follow an order.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "E-commerce Coordinator — Professional",
    "profession_ar": "منسق تجارة إلكترونية — ممارس",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "منسق تجارة إلكترونية — ممارس: نشر صفحة منتج ومتابعة الطلب. E-commerce Coordinator — Professional: publish a product page and follow an order.",
    "job_description": "منسق تجارة إلكترونية — ممارس: نشر صفحة منتج ومتابعة الطلب. E-commerce Coordinator — Professional: publish a product page and follow an order.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "E-commerce Coordinator — Team Supervisor",
    "profession_ar": "منسق تجارة إلكترونية — مشرف فريق",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "منسق تجارة إلكترونية — مشرف فريق: نشر صفحة منتج ومتابعة الطلب. E-commerce Coordinator — Team Supervisor: publish a product page and follow an order.",
    "job_description": "منسق تجارة إلكترونية — مشرف فريق: نشر صفحة منتج ومتابعة الطلب. E-commerce Coordinator — Team Supervisor: publish a product page and follow an order.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Paid Media Specialist — Entry Level",
    "profession_ar": "متخصص إعلانات مدفوعة — مبتدئ",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص إعلانات مدفوعة — مبتدئ: إعداد تجربة إعلانية بميزانية محددة. Paid Media Specialist — Entry Level: set up an advertising experiment with a fixed budget.",
    "job_description": "متخصص إعلانات مدفوعة — مبتدئ: إعداد تجربة إعلانية بميزانية محددة. Paid Media Specialist — Entry Level: set up an advertising experiment with a fixed budget.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Paid Media Specialist — Professional",
    "profession_ar": "متخصص إعلانات مدفوعة — ممارس",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص إعلانات مدفوعة — ممارس: إعداد تجربة إعلانية بميزانية محددة. Paid Media Specialist — Professional: set up an advertising experiment with a fixed budget.",
    "job_description": "متخصص إعلانات مدفوعة — ممارس: إعداد تجربة إعلانية بميزانية محددة. Paid Media Specialist — Professional: set up an advertising experiment with a fixed budget.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Paid Media Specialist — Team Supervisor",
    "profession_ar": "متخصص إعلانات مدفوعة — مشرف فريق",
    "category": "Marketing & E-commerce",
    "library": "Marketing & E-commerce",
    "focus": "متخصص إعلانات مدفوعة — مشرف فريق: إعداد تجربة إعلانية بميزانية محددة. Paid Media Specialist — Team Supervisor: set up an advertising experiment with a fixed budget.",
    "job_description": "متخصص إعلانات مدفوعة — مشرف فريق: إعداد تجربة إعلانية بميزانية محددة. Paid Media Specialist — Team Supervisor: set up an advertising experiment with a fixed budget.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Hotel Front Desk Agent — Entry Level",
    "profession_ar": "موظف استقبال فندق — مبتدئ",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف استقبال فندق — مبتدئ: إتمام إجراءات وصول ضيف وتسليم الغرفة. Hotel Front Desk Agent — Entry Level: complete guest check-in and room handover.",
    "job_description": "موظف استقبال فندق — مبتدئ: إتمام إجراءات وصول ضيف وتسليم الغرفة. Hotel Front Desk Agent — Entry Level: complete guest check-in and room handover.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Hotel Front Desk Agent — Professional",
    "profession_ar": "موظف استقبال فندق — ممارس",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف استقبال فندق — ممارس: إتمام إجراءات وصول ضيف وتسليم الغرفة. Hotel Front Desk Agent — Professional: complete guest check-in and room handover.",
    "job_description": "موظف استقبال فندق — ممارس: إتمام إجراءات وصول ضيف وتسليم الغرفة. Hotel Front Desk Agent — Professional: complete guest check-in and room handover.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Hotel Front Desk Agent — Team Supervisor",
    "profession_ar": "موظف استقبال فندق — مشرف فريق",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف استقبال فندق — مشرف فريق: إتمام إجراءات وصول ضيف وتسليم الغرفة. Hotel Front Desk Agent — Team Supervisor: complete guest check-in and room handover.",
    "job_description": "موظف استقبال فندق — مشرف فريق: إتمام إجراءات وصول ضيف وتسليم الغرفة. Hotel Front Desk Agent — Team Supervisor: complete guest check-in and room handover.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Restaurant Service Associate — Entry Level",
    "profession_ar": "موظف خدمة مطعم — مبتدئ",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف خدمة مطعم — مبتدئ: استلام طلب وتأكيده وتسليمه للضيف. Restaurant Service Associate — Entry Level: take, confirm and deliver a guest order.",
    "job_description": "موظف خدمة مطعم — مبتدئ: استلام طلب وتأكيده وتسليمه للضيف. Restaurant Service Associate — Entry Level: take, confirm and deliver a guest order.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Restaurant Service Associate — Professional",
    "profession_ar": "موظف خدمة مطعم — ممارس",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف خدمة مطعم — ممارس: استلام طلب وتأكيده وتسليمه للضيف. Restaurant Service Associate — Professional: take, confirm and deliver a guest order.",
    "job_description": "موظف خدمة مطعم — ممارس: استلام طلب وتأكيده وتسليمه للضيف. Restaurant Service Associate — Professional: take, confirm and deliver a guest order.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Restaurant Service Associate — Team Supervisor",
    "profession_ar": "موظف خدمة مطعم — مشرف فريق",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف خدمة مطعم — مشرف فريق: استلام طلب وتأكيده وتسليمه للضيف. Restaurant Service Associate — Team Supervisor: take, confirm and deliver a guest order.",
    "job_description": "موظف خدمة مطعم — مشرف فريق: استلام طلب وتأكيده وتسليمه للضيف. Restaurant Service Associate — Team Supervisor: take, confirm and deliver a guest order.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Housekeeping Associate — Entry Level",
    "profession_ar": "موظف تدبير فندقي — مبتدئ",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف تدبير فندقي — مبتدئ: تجهيز غرفة والتحقق من جاهزيتها. Housekeeping Associate — Entry Level: prepare a room and verify readiness.",
    "job_description": "موظف تدبير فندقي — مبتدئ: تجهيز غرفة والتحقق من جاهزيتها. Housekeeping Associate — Entry Level: prepare a room and verify readiness.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Housekeeping Associate — Professional",
    "profession_ar": "موظف تدبير فندقي — ممارس",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف تدبير فندقي — ممارس: تجهيز غرفة والتحقق من جاهزيتها. Housekeeping Associate — Professional: prepare a room and verify readiness.",
    "job_description": "موظف تدبير فندقي — ممارس: تجهيز غرفة والتحقق من جاهزيتها. Housekeeping Associate — Professional: prepare a room and verify readiness.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Housekeeping Associate — Team Supervisor",
    "profession_ar": "موظف تدبير فندقي — مشرف فريق",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف تدبير فندقي — مشرف فريق: تجهيز غرفة والتحقق من جاهزيتها. Housekeeping Associate — Team Supervisor: prepare a room and verify readiness.",
    "job_description": "موظف تدبير فندقي — مشرف فريق: تجهيز غرفة والتحقق من جاهزيتها. Housekeeping Associate — Team Supervisor: prepare a room and verify readiness.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Reservations Agent — Entry Level",
    "profession_ar": "موظف حجوزات — مبتدئ",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف حجوزات — مبتدئ: إنشاء حجز وتأكيد تفاصيله للضيف. Reservations Agent — Entry Level: create a reservation and confirm its details.",
    "job_description": "موظف حجوزات — مبتدئ: إنشاء حجز وتأكيد تفاصيله للضيف. Reservations Agent — Entry Level: create a reservation and confirm its details.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Reservations Agent — Professional",
    "profession_ar": "موظف حجوزات — ممارس",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف حجوزات — ممارس: إنشاء حجز وتأكيد تفاصيله للضيف. Reservations Agent — Professional: create a reservation and confirm its details.",
    "job_description": "موظف حجوزات — ممارس: إنشاء حجز وتأكيد تفاصيله للضيف. Reservations Agent — Professional: create a reservation and confirm its details.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Reservations Agent — Team Supervisor",
    "profession_ar": "موظف حجوزات — مشرف فريق",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "موظف حجوزات — مشرف فريق: إنشاء حجز وتأكيد تفاصيله للضيف. Reservations Agent — Team Supervisor: create a reservation and confirm its details.",
    "job_description": "موظف حجوزات — مشرف فريق: إنشاء حجز وتأكيد تفاصيله للضيف. Reservations Agent — Team Supervisor: create a reservation and confirm its details.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Barista — Entry Level",
    "profession_ar": "باريستا — مبتدئ",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "باريستا — مبتدئ: تحضير طلب مشروب وفق الوصفة المعتمدة. Barista — Entry Level: prepare a beverage to the approved recipe.",
    "job_description": "باريستا — مبتدئ: تحضير طلب مشروب وفق الوصفة المعتمدة. Barista — Entry Level: prepare a beverage to the approved recipe.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Barista — Professional",
    "profession_ar": "باريستا — ممارس",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "باريستا — ممارس: تحضير طلب مشروب وفق الوصفة المعتمدة. Barista — Professional: prepare a beverage to the approved recipe.",
    "job_description": "باريستا — ممارس: تحضير طلب مشروب وفق الوصفة المعتمدة. Barista — Professional: prepare a beverage to the approved recipe.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Barista — Team Supervisor",
    "profession_ar": "باريستا — مشرف فريق",
    "category": "Hospitality & Restaurants",
    "library": "Hospitality & Restaurants",
    "focus": "باريستا — مشرف فريق: تحضير طلب مشروب وفق الوصفة المعتمدة. Barista — Team Supervisor: prepare a beverage to the approved recipe.",
    "job_description": "باريستا — مشرف فريق: تحضير طلب مشروب وفق الوصفة المعتمدة. Barista — Team Supervisor: prepare a beverage to the approved recipe.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  }
];
