// Public catalog metadata only. Questions and scoring references remain in the database.
export const FIELD_INTERVIEW_CATALOG = [
  {
    "profession": "Automotive Mechanic — Entry Level",
    "profession_ar": "ميكانيكي مركبات — مبتدئ",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "ميكانيكي مركبات — مبتدئ: فحص شكوى مركبة وتوثيق التشخيص قبل الإصلاح. Automotive Mechanic — Entry Level: inspect a vehicle complaint and document diagnosis before repair.",
    "job_description": "ميكانيكي مركبات — مبتدئ: فحص شكوى مركبة وتوثيق التشخيص قبل الإصلاح. Automotive Mechanic — Entry Level: inspect a vehicle complaint and document diagnosis before repair.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Automotive Mechanic — Professional",
    "profession_ar": "ميكانيكي مركبات — ممارس",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "ميكانيكي مركبات — ممارس: فحص شكوى مركبة وتوثيق التشخيص قبل الإصلاح. Automotive Mechanic — Professional: inspect a vehicle complaint and document diagnosis before repair.",
    "job_description": "ميكانيكي مركبات — ممارس: فحص شكوى مركبة وتوثيق التشخيص قبل الإصلاح. Automotive Mechanic — Professional: inspect a vehicle complaint and document diagnosis before repair.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Automotive Mechanic — Team Supervisor",
    "profession_ar": "ميكانيكي مركبات — مشرف فريق",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "ميكانيكي مركبات — مشرف فريق: فحص شكوى مركبة وتوثيق التشخيص قبل الإصلاح. Automotive Mechanic — Team Supervisor: inspect a vehicle complaint and document diagnosis before repair.",
    "job_description": "ميكانيكي مركبات — مشرف فريق: فحص شكوى مركبة وتوثيق التشخيص قبل الإصلاح. Automotive Mechanic — Team Supervisor: inspect a vehicle complaint and document diagnosis before repair.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Diesel Equipment Technician — Entry Level",
    "profession_ar": "فني معدات ديزل — مبتدئ",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني معدات ديزل — مبتدئ: تخطيط فحص معدة ديزل وصيانتها حسب تعليمات المصنع. Diesel Equipment Technician — Entry Level: plan inspection and maintenance of diesel equipment using manufacturer instructions.",
    "job_description": "فني معدات ديزل — مبتدئ: تخطيط فحص معدة ديزل وصيانتها حسب تعليمات المصنع. Diesel Equipment Technician — Entry Level: plan inspection and maintenance of diesel equipment using manufacturer instructions.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Diesel Equipment Technician — Professional",
    "profession_ar": "فني معدات ديزل — ممارس",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني معدات ديزل — ممارس: تخطيط فحص معدة ديزل وصيانتها حسب تعليمات المصنع. Diesel Equipment Technician — Professional: plan inspection and maintenance of diesel equipment using manufacturer instructions.",
    "job_description": "فني معدات ديزل — ممارس: تخطيط فحص معدة ديزل وصيانتها حسب تعليمات المصنع. Diesel Equipment Technician — Professional: plan inspection and maintenance of diesel equipment using manufacturer instructions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Diesel Equipment Technician — Team Supervisor",
    "profession_ar": "فني معدات ديزل — مشرف فريق",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني معدات ديزل — مشرف فريق: تخطيط فحص معدة ديزل وصيانتها حسب تعليمات المصنع. Diesel Equipment Technician — Team Supervisor: plan inspection and maintenance of diesel equipment using manufacturer instructions.",
    "job_description": "فني معدات ديزل — مشرف فريق: تخطيط فحص معدة ديزل وصيانتها حسب تعليمات المصنع. Diesel Equipment Technician — Team Supervisor: plan inspection and maintenance of diesel equipment using manufacturer instructions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Instrumentation Calibration Technician — Entry Level",
    "profession_ar": "فني معايرة أجهزة قياس — مبتدئ",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني معايرة أجهزة قياس — مبتدئ: معايرة جهاز وتوثيق التتبع والنتائج. Instrumentation Calibration Technician — Entry Level: calibrate an instrument and document traceability and results.",
    "job_description": "فني معايرة أجهزة قياس — مبتدئ: معايرة جهاز وتوثيق التتبع والنتائج. Instrumentation Calibration Technician — Entry Level: calibrate an instrument and document traceability and results.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Instrumentation Calibration Technician — Professional",
    "profession_ar": "فني معايرة أجهزة قياس — ممارس",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني معايرة أجهزة قياس — ممارس: معايرة جهاز وتوثيق التتبع والنتائج. Instrumentation Calibration Technician — Professional: calibrate an instrument and document traceability and results.",
    "job_description": "فني معايرة أجهزة قياس — ممارس: معايرة جهاز وتوثيق التتبع والنتائج. Instrumentation Calibration Technician — Professional: calibrate an instrument and document traceability and results.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Instrumentation Calibration Technician — Team Supervisor",
    "profession_ar": "فني معايرة أجهزة قياس — مشرف فريق",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني معايرة أجهزة قياس — مشرف فريق: معايرة جهاز وتوثيق التتبع والنتائج. Instrumentation Calibration Technician — Team Supervisor: calibrate an instrument and document traceability and results.",
    "job_description": "فني معايرة أجهزة قياس — مشرف فريق: معايرة جهاز وتوثيق التتبع والنتائج. Instrumentation Calibration Technician — Team Supervisor: calibrate an instrument and document traceability and results.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Welding Fabricator — Entry Level",
    "profession_ar": "لحام ومصنّع معدني — مبتدئ",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "لحام ومصنّع معدني — مبتدئ: تجهيز وصلة لحام وفق الرسم والإجراء المعتمد. Welding Fabricator — Entry Level: prepare a welded joint to the approved drawing and procedure.",
    "job_description": "لحام ومصنّع معدني — مبتدئ: تجهيز وصلة لحام وفق الرسم والإجراء المعتمد. Welding Fabricator — Entry Level: prepare a welded joint to the approved drawing and procedure.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Welding Fabricator — Professional",
    "profession_ar": "لحام ومصنّع معدني — ممارس",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "لحام ومصنّع معدني — ممارس: تجهيز وصلة لحام وفق الرسم والإجراء المعتمد. Welding Fabricator — Professional: prepare a welded joint to the approved drawing and procedure.",
    "job_description": "لحام ومصنّع معدني — ممارس: تجهيز وصلة لحام وفق الرسم والإجراء المعتمد. Welding Fabricator — Professional: prepare a welded joint to the approved drawing and procedure.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Welding Fabricator — Team Supervisor",
    "profession_ar": "لحام ومصنّع معدني — مشرف فريق",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "لحام ومصنّع معدني — مشرف فريق: تجهيز وصلة لحام وفق الرسم والإجراء المعتمد. Welding Fabricator — Team Supervisor: prepare a welded joint to the approved drawing and procedure.",
    "job_description": "لحام ومصنّع معدني — مشرف فريق: تجهيز وصلة لحام وفق الرسم والإجراء المعتمد. Welding Fabricator — Team Supervisor: prepare a welded joint to the approved drawing and procedure.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Elevator Maintenance Technician — Entry Level",
    "profession_ar": "فني صيانة مصاعد — مبتدئ",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني صيانة مصاعد — مبتدئ: تنفيذ صيانة مصعد ضمن التأهيل والإجراءات المعتمدة. Elevator Maintenance Technician — Entry Level: perform elevator maintenance within qualification and approved procedures.",
    "job_description": "فني صيانة مصاعد — مبتدئ: تنفيذ صيانة مصعد ضمن التأهيل والإجراءات المعتمدة. Elevator Maintenance Technician — Entry Level: perform elevator maintenance within qualification and approved procedures.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Elevator Maintenance Technician — Professional",
    "profession_ar": "فني صيانة مصاعد — ممارس",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني صيانة مصاعد — ممارس: تنفيذ صيانة مصعد ضمن التأهيل والإجراءات المعتمدة. Elevator Maintenance Technician — Professional: perform elevator maintenance within qualification and approved procedures.",
    "job_description": "فني صيانة مصاعد — ممارس: تنفيذ صيانة مصعد ضمن التأهيل والإجراءات المعتمدة. Elevator Maintenance Technician — Professional: perform elevator maintenance within qualification and approved procedures.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Elevator Maintenance Technician — Team Supervisor",
    "profession_ar": "فني صيانة مصاعد — مشرف فريق",
    "category": "Field Technical & Maintenance",
    "library": "Field Technical & Maintenance",
    "focus": "فني صيانة مصاعد — مشرف فريق: تنفيذ صيانة مصعد ضمن التأهيل والإجراءات المعتمدة. Elevator Maintenance Technician — Team Supervisor: perform elevator maintenance within qualification and approved procedures.",
    "job_description": "فني صيانة مصاعد — مشرف فريق: تنفيذ صيانة مصعد ضمن التأهيل والإجراءات المعتمدة. Elevator Maintenance Technician — Team Supervisor: perform elevator maintenance within qualification and approved procedures.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Formwork Carpenter — Entry Level",
    "profession_ar": "نجار شدات — مبتدئ",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "نجار شدات — مبتدئ: تركيب شدات طبقًا للرسم المعتمد ونقاط الفحص. Formwork Carpenter — Entry Level: assemble formwork to approved drawings and inspection points.",
    "job_description": "نجار شدات — مبتدئ: تركيب شدات طبقًا للرسم المعتمد ونقاط الفحص. Formwork Carpenter — Entry Level: assemble formwork to approved drawings and inspection points.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Formwork Carpenter — Professional",
    "profession_ar": "نجار شدات — ممارس",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "نجار شدات — ممارس: تركيب شدات طبقًا للرسم المعتمد ونقاط الفحص. Formwork Carpenter — Professional: assemble formwork to approved drawings and inspection points.",
    "job_description": "نجار شدات — ممارس: تركيب شدات طبقًا للرسم المعتمد ونقاط الفحص. Formwork Carpenter — Professional: assemble formwork to approved drawings and inspection points.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Formwork Carpenter — Team Supervisor",
    "profession_ar": "نجار شدات — مشرف فريق",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "نجار شدات — مشرف فريق: تركيب شدات طبقًا للرسم المعتمد ونقاط الفحص. Formwork Carpenter — Team Supervisor: assemble formwork to approved drawings and inspection points.",
    "job_description": "نجار شدات — مشرف فريق: تركيب شدات طبقًا للرسم المعتمد ونقاط الفحص. Formwork Carpenter — Team Supervisor: assemble formwork to approved drawings and inspection points.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Steel Fixer — Entry Level",
    "profession_ar": "حداد تسليح — مبتدئ",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "حداد تسليح — مبتدئ: قراءة جدول حديد وتركيب التسليح وفق الرسم. Steel Fixer — Entry Level: read a bar schedule and fix reinforcement to the drawing.",
    "job_description": "حداد تسليح — مبتدئ: قراءة جدول حديد وتركيب التسليح وفق الرسم. Steel Fixer — Entry Level: read a bar schedule and fix reinforcement to the drawing.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Steel Fixer — Professional",
    "profession_ar": "حداد تسليح — ممارس",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "حداد تسليح — ممارس: قراءة جدول حديد وتركيب التسليح وفق الرسم. Steel Fixer — Professional: read a bar schedule and fix reinforcement to the drawing.",
    "job_description": "حداد تسليح — ممارس: قراءة جدول حديد وتركيب التسليح وفق الرسم. Steel Fixer — Professional: read a bar schedule and fix reinforcement to the drawing.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Steel Fixer — Team Supervisor",
    "profession_ar": "حداد تسليح — مشرف فريق",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "حداد تسليح — مشرف فريق: قراءة جدول حديد وتركيب التسليح وفق الرسم. Steel Fixer — Team Supervisor: read a bar schedule and fix reinforcement to the drawing.",
    "job_description": "حداد تسليح — مشرف فريق: قراءة جدول حديد وتركيب التسليح وفق الرسم. Steel Fixer — Team Supervisor: read a bar schedule and fix reinforcement to the drawing.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Masonry Worker — Entry Level",
    "profession_ar": "بنّاء — مبتدئ",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "بنّاء — مبتدئ: تنفيذ مبانٍ مع التحقق من الأبعاد والاستقامة. Masonry Worker — Entry Level: execute masonry and verify dimensions and alignment.",
    "job_description": "بنّاء — مبتدئ: تنفيذ مبانٍ مع التحقق من الأبعاد والاستقامة. Masonry Worker — Entry Level: execute masonry and verify dimensions and alignment.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Masonry Worker — Professional",
    "profession_ar": "بنّاء — ممارس",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "بنّاء — ممارس: تنفيذ مبانٍ مع التحقق من الأبعاد والاستقامة. Masonry Worker — Professional: execute masonry and verify dimensions and alignment.",
    "job_description": "بنّاء — ممارس: تنفيذ مبانٍ مع التحقق من الأبعاد والاستقامة. Masonry Worker — Professional: execute masonry and verify dimensions and alignment.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Masonry Worker — Team Supervisor",
    "profession_ar": "بنّاء — مشرف فريق",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "بنّاء — مشرف فريق: تنفيذ مبانٍ مع التحقق من الأبعاد والاستقامة. Masonry Worker — Team Supervisor: execute masonry and verify dimensions and alignment.",
    "job_description": "بنّاء — مشرف فريق: تنفيذ مبانٍ مع التحقق من الأبعاد والاستقامة. Masonry Worker — Team Supervisor: execute masonry and verify dimensions and alignment.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Land Survey Technician — Entry Level",
    "profession_ar": "فني مساحة — مبتدئ",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "فني مساحة — مبتدئ: تنفيذ قراءة منسوب وتوثيق نقاط الضبط. Land Survey Technician — Entry Level: take a level measurement and document control points.",
    "job_description": "فني مساحة — مبتدئ: تنفيذ قراءة منسوب وتوثيق نقاط الضبط. Land Survey Technician — Entry Level: take a level measurement and document control points.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Land Survey Technician — Professional",
    "profession_ar": "فني مساحة — ممارس",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "فني مساحة — ممارس: تنفيذ قراءة منسوب وتوثيق نقاط الضبط. Land Survey Technician — Professional: take a level measurement and document control points.",
    "job_description": "فني مساحة — ممارس: تنفيذ قراءة منسوب وتوثيق نقاط الضبط. Land Survey Technician — Professional: take a level measurement and document control points.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Land Survey Technician — Team Supervisor",
    "profession_ar": "فني مساحة — مشرف فريق",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "فني مساحة — مشرف فريق: تنفيذ قراءة منسوب وتوثيق نقاط الضبط. Land Survey Technician — Team Supervisor: take a level measurement and document control points.",
    "job_description": "فني مساحة — مشرف فريق: تنفيذ قراءة منسوب وتوثيق نقاط الضبط. Land Survey Technician — Team Supervisor: take a level measurement and document control points.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Scaffolding Erector — Entry Level",
    "profession_ar": "عامل تركيب سقالات — مبتدئ",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "عامل تركيب سقالات — مبتدئ: تجهيز سقالة للعمل وفق التصميم والفحص المعتمد. Scaffolding Erector — Entry Level: prepare scaffolding under approved design and inspection.",
    "job_description": "عامل تركيب سقالات — مبتدئ: تجهيز سقالة للعمل وفق التصميم والفحص المعتمد. Scaffolding Erector — Entry Level: prepare scaffolding under approved design and inspection.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Scaffolding Erector — Professional",
    "profession_ar": "عامل تركيب سقالات — ممارس",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "عامل تركيب سقالات — ممارس: تجهيز سقالة للعمل وفق التصميم والفحص المعتمد. Scaffolding Erector — Professional: prepare scaffolding under approved design and inspection.",
    "job_description": "عامل تركيب سقالات — ممارس: تجهيز سقالة للعمل وفق التصميم والفحص المعتمد. Scaffolding Erector — Professional: prepare scaffolding under approved design and inspection.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Scaffolding Erector — Team Supervisor",
    "profession_ar": "عامل تركيب سقالات — مشرف فريق",
    "category": "Construction Trades",
    "library": "Construction Trades",
    "focus": "عامل تركيب سقالات — مشرف فريق: تجهيز سقالة للعمل وفق التصميم والفحص المعتمد. Scaffolding Erector — Team Supervisor: prepare scaffolding under approved design and inspection.",
    "job_description": "عامل تركيب سقالات — مشرف فريق: تجهيز سقالة للعمل وفق التصميم والفحص المعتمد. Scaffolding Erector — Team Supervisor: prepare scaffolding under approved design and inspection.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Light Vehicle Driver — Entry Level",
    "profession_ar": "سائق مركبة خفيفة — مبتدئ",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق مركبة خفيفة — مبتدئ: الاستعداد لرحلة وتسليم المركبة وتوثيق الاستثناءات. Light Vehicle Driver — Entry Level: prepare for a trip, hand over the vehicle and document exceptions.",
    "job_description": "سائق مركبة خفيفة — مبتدئ: الاستعداد لرحلة وتسليم المركبة وتوثيق الاستثناءات. Light Vehicle Driver — Entry Level: prepare for a trip, hand over the vehicle and document exceptions.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Light Vehicle Driver — Professional",
    "profession_ar": "سائق مركبة خفيفة — ممارس",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق مركبة خفيفة — ممارس: الاستعداد لرحلة وتسليم المركبة وتوثيق الاستثناءات. Light Vehicle Driver — Professional: prepare for a trip, hand over the vehicle and document exceptions.",
    "job_description": "سائق مركبة خفيفة — ممارس: الاستعداد لرحلة وتسليم المركبة وتوثيق الاستثناءات. Light Vehicle Driver — Professional: prepare for a trip, hand over the vehicle and document exceptions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Light Vehicle Driver — Team Supervisor",
    "profession_ar": "سائق مركبة خفيفة — مشرف فريق",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق مركبة خفيفة — مشرف فريق: الاستعداد لرحلة وتسليم المركبة وتوثيق الاستثناءات. Light Vehicle Driver — Team Supervisor: prepare for a trip, hand over the vehicle and document exceptions.",
    "job_description": "سائق مركبة خفيفة — مشرف فريق: الاستعداد لرحلة وتسليم المركبة وتوثيق الاستثناءات. Light Vehicle Driver — Team Supervisor: prepare for a trip, hand over the vehicle and document exceptions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Heavy Truck Driver — Entry Level",
    "profession_ar": "سائق شاحنة ثقيلة — مبتدئ",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق شاحنة ثقيلة — مبتدئ: التحقق من جاهزية رحلة شحن وحمولتها. Heavy Truck Driver — Entry Level: verify readiness for a freight journey and its load.",
    "job_description": "سائق شاحنة ثقيلة — مبتدئ: التحقق من جاهزية رحلة شحن وحمولتها. Heavy Truck Driver — Entry Level: verify readiness for a freight journey and its load.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Heavy Truck Driver — Professional",
    "profession_ar": "سائق شاحنة ثقيلة — ممارس",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق شاحنة ثقيلة — ممارس: التحقق من جاهزية رحلة شحن وحمولتها. Heavy Truck Driver — Professional: verify readiness for a freight journey and its load.",
    "job_description": "سائق شاحنة ثقيلة — ممارس: التحقق من جاهزية رحلة شحن وحمولتها. Heavy Truck Driver — Professional: verify readiness for a freight journey and its load.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Heavy Truck Driver — Team Supervisor",
    "profession_ar": "سائق شاحنة ثقيلة — مشرف فريق",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق شاحنة ثقيلة — مشرف فريق: التحقق من جاهزية رحلة شحن وحمولتها. Heavy Truck Driver — Team Supervisor: verify readiness for a freight journey and its load.",
    "job_description": "سائق شاحنة ثقيلة — مشرف فريق: التحقق من جاهزية رحلة شحن وحمولتها. Heavy Truck Driver — Team Supervisor: verify readiness for a freight journey and its load.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Bus Driver — Entry Level",
    "profession_ar": "سائق حافلة — مبتدئ",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق حافلة — مبتدئ: تنظيم رحلة ركاب والتحقق من جاهزية الحافلة. Bus Driver — Entry Level: organize a passenger trip and verify bus readiness.",
    "job_description": "سائق حافلة — مبتدئ: تنظيم رحلة ركاب والتحقق من جاهزية الحافلة. Bus Driver — Entry Level: organize a passenger trip and verify bus readiness.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Bus Driver — Professional",
    "profession_ar": "سائق حافلة — ممارس",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق حافلة — ممارس: تنظيم رحلة ركاب والتحقق من جاهزية الحافلة. Bus Driver — Professional: organize a passenger trip and verify bus readiness.",
    "job_description": "سائق حافلة — ممارس: تنظيم رحلة ركاب والتحقق من جاهزية الحافلة. Bus Driver — Professional: organize a passenger trip and verify bus readiness.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Bus Driver — Team Supervisor",
    "profession_ar": "سائق حافلة — مشرف فريق",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "سائق حافلة — مشرف فريق: تنظيم رحلة ركاب والتحقق من جاهزية الحافلة. Bus Driver — Team Supervisor: organize a passenger trip and verify bus readiness.",
    "job_description": "سائق حافلة — مشرف فريق: تنظيم رحلة ركاب والتحقق من جاهزية الحافلة. Bus Driver — Team Supervisor: organize a passenger trip and verify bus readiness.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Forklift Operator — Entry Level",
    "profession_ar": "مشغل رافعة شوكية — مبتدئ",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "مشغل رافعة شوكية — مبتدئ: فحص مهمة مناولة وتنفيذها ضمن التأهيل والحدود. Forklift Operator — Entry Level: assess and perform a handling task within qualification and limits.",
    "job_description": "مشغل رافعة شوكية — مبتدئ: فحص مهمة مناولة وتنفيذها ضمن التأهيل والحدود. Forklift Operator — Entry Level: assess and perform a handling task within qualification and limits.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Forklift Operator — Professional",
    "profession_ar": "مشغل رافعة شوكية — ممارس",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "مشغل رافعة شوكية — ممارس: فحص مهمة مناولة وتنفيذها ضمن التأهيل والحدود. Forklift Operator — Professional: assess and perform a handling task within qualification and limits.",
    "job_description": "مشغل رافعة شوكية — ممارس: فحص مهمة مناولة وتنفيذها ضمن التأهيل والحدود. Forklift Operator — Professional: assess and perform a handling task within qualification and limits.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Forklift Operator — Team Supervisor",
    "profession_ar": "مشغل رافعة شوكية — مشرف فريق",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "مشغل رافعة شوكية — مشرف فريق: فحص مهمة مناولة وتنفيذها ضمن التأهيل والحدود. Forklift Operator — Team Supervisor: assess and perform a handling task within qualification and limits.",
    "job_description": "مشغل رافعة شوكية — مشرف فريق: فحص مهمة مناولة وتنفيذها ضمن التأهيل والحدود. Forklift Operator — Team Supervisor: assess and perform a handling task within qualification and limits.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Fleet Dispatcher — Entry Level",
    "profession_ar": "منسق حركة أسطول — مبتدئ",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "منسق حركة أسطول — مبتدئ: توزيع رحلات على مركبات وسائقين جاهزين. Fleet Dispatcher — Entry Level: assign trips to available suitable vehicles and drivers.",
    "job_description": "منسق حركة أسطول — مبتدئ: توزيع رحلات على مركبات وسائقين جاهزين. Fleet Dispatcher — Entry Level: assign trips to available suitable vehicles and drivers.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Fleet Dispatcher — Professional",
    "profession_ar": "منسق حركة أسطول — ممارس",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "منسق حركة أسطول — ممارس: توزيع رحلات على مركبات وسائقين جاهزين. Fleet Dispatcher — Professional: assign trips to available suitable vehicles and drivers.",
    "job_description": "منسق حركة أسطول — ممارس: توزيع رحلات على مركبات وسائقين جاهزين. Fleet Dispatcher — Professional: assign trips to available suitable vehicles and drivers.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Fleet Dispatcher — Team Supervisor",
    "profession_ar": "منسق حركة أسطول — مشرف فريق",
    "category": "Transport & Equipment",
    "library": "Transport & Equipment",
    "focus": "منسق حركة أسطول — مشرف فريق: توزيع رحلات على مركبات وسائقين جاهزين. Fleet Dispatcher — Team Supervisor: assign trips to available suitable vehicles and drivers.",
    "job_description": "منسق حركة أسطول — مشرف فريق: توزيع رحلات على مركبات وسائقين جاهزين. Fleet Dispatcher — Team Supervisor: assign trips to available suitable vehicles and drivers.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Production Line Operator — Entry Level",
    "profession_ar": "مشغل خط إنتاج — مبتدئ",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل خط إنتاج — مبتدئ: تشغيل أمر إنتاج وفق العمل القياسي والفحص. Production Line Operator — Entry Level: execute a production order using standard work and checks.",
    "job_description": "مشغل خط إنتاج — مبتدئ: تشغيل أمر إنتاج وفق العمل القياسي والفحص. Production Line Operator — Entry Level: execute a production order using standard work and checks.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Production Line Operator — Professional",
    "profession_ar": "مشغل خط إنتاج — ممارس",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل خط إنتاج — ممارس: تشغيل أمر إنتاج وفق العمل القياسي والفحص. Production Line Operator — Professional: execute a production order using standard work and checks.",
    "job_description": "مشغل خط إنتاج — ممارس: تشغيل أمر إنتاج وفق العمل القياسي والفحص. Production Line Operator — Professional: execute a production order using standard work and checks.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Production Line Operator — Team Supervisor",
    "profession_ar": "مشغل خط إنتاج — مشرف فريق",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل خط إنتاج — مشرف فريق: تشغيل أمر إنتاج وفق العمل القياسي والفحص. Production Line Operator — Team Supervisor: execute a production order using standard work and checks.",
    "job_description": "مشغل خط إنتاج — مشرف فريق: تشغيل أمر إنتاج وفق العمل القياسي والفحص. Production Line Operator — Team Supervisor: execute a production order using standard work and checks.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "CNC Machine Operator — Entry Level",
    "profession_ar": "مشغل ماكينة CNC — مبتدئ",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل ماكينة CNC — مبتدئ: تهيئة أمر تشغيل وفحص القطعة الأولى. CNC Machine Operator — Entry Level: prepare a machining job and inspect the first piece.",
    "job_description": "مشغل ماكينة CNC — مبتدئ: تهيئة أمر تشغيل وفحص القطعة الأولى. CNC Machine Operator — Entry Level: prepare a machining job and inspect the first piece.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "CNC Machine Operator — Professional",
    "profession_ar": "مشغل ماكينة CNC — ممارس",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل ماكينة CNC — ممارس: تهيئة أمر تشغيل وفحص القطعة الأولى. CNC Machine Operator — Professional: prepare a machining job and inspect the first piece.",
    "job_description": "مشغل ماكينة CNC — ممارس: تهيئة أمر تشغيل وفحص القطعة الأولى. CNC Machine Operator — Professional: prepare a machining job and inspect the first piece.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "CNC Machine Operator — Team Supervisor",
    "profession_ar": "مشغل ماكينة CNC — مشرف فريق",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل ماكينة CNC — مشرف فريق: تهيئة أمر تشغيل وفحص القطعة الأولى. CNC Machine Operator — Team Supervisor: prepare a machining job and inspect the first piece.",
    "job_description": "مشغل ماكينة CNC — مشرف فريق: تهيئة أمر تشغيل وفحص القطعة الأولى. CNC Machine Operator — Team Supervisor: prepare a machining job and inspect the first piece.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Production Planner — Entry Level",
    "profession_ar": "مخطط إنتاج — مبتدئ",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مخطط إنتاج — مبتدئ: إعداد جدول إنتاج بناء على الطلب والطاقة والمواد. Production Planner — Entry Level: plan production using demand, capacity and material availability.",
    "job_description": "مخطط إنتاج — مبتدئ: إعداد جدول إنتاج بناء على الطلب والطاقة والمواد. Production Planner — Entry Level: plan production using demand, capacity and material availability.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Production Planner — Professional",
    "profession_ar": "مخطط إنتاج — ممارس",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مخطط إنتاج — ممارس: إعداد جدول إنتاج بناء على الطلب والطاقة والمواد. Production Planner — Professional: plan production using demand, capacity and material availability.",
    "job_description": "مخطط إنتاج — ممارس: إعداد جدول إنتاج بناء على الطلب والطاقة والمواد. Production Planner — Professional: plan production using demand, capacity and material availability.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Production Planner — Team Supervisor",
    "profession_ar": "مخطط إنتاج — مشرف فريق",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مخطط إنتاج — مشرف فريق: إعداد جدول إنتاج بناء على الطلب والطاقة والمواد. Production Planner — Team Supervisor: plan production using demand, capacity and material availability.",
    "job_description": "مخطط إنتاج — مشرف فريق: إعداد جدول إنتاج بناء على الطلب والطاقة والمواد. Production Planner — Team Supervisor: plan production using demand, capacity and material availability.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Packaging Machine Operator — Entry Level",
    "profession_ar": "مشغل ماكينة تعبئة وتغليف — مبتدئ",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل ماكينة تعبئة وتغليف — مبتدئ: تعبئة منتج والتحقق من البطاقة ورقم التشغيلة. Packaging Machine Operator — Entry Level: package product and verify label and batch identification.",
    "job_description": "مشغل ماكينة تعبئة وتغليف — مبتدئ: تعبئة منتج والتحقق من البطاقة ورقم التشغيلة. Packaging Machine Operator — Entry Level: package product and verify label and batch identification.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Packaging Machine Operator — Professional",
    "profession_ar": "مشغل ماكينة تعبئة وتغليف — ممارس",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل ماكينة تعبئة وتغليف — ممارس: تعبئة منتج والتحقق من البطاقة ورقم التشغيلة. Packaging Machine Operator — Professional: package product and verify label and batch identification.",
    "job_description": "مشغل ماكينة تعبئة وتغليف — ممارس: تعبئة منتج والتحقق من البطاقة ورقم التشغيلة. Packaging Machine Operator — Professional: package product and verify label and batch identification.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Packaging Machine Operator — Team Supervisor",
    "profession_ar": "مشغل ماكينة تعبئة وتغليف — مشرف فريق",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "مشغل ماكينة تعبئة وتغليف — مشرف فريق: تعبئة منتج والتحقق من البطاقة ورقم التشغيلة. Packaging Machine Operator — Team Supervisor: package product and verify label and batch identification.",
    "job_description": "مشغل ماكينة تعبئة وتغليف — مشرف فريق: تعبئة منتج والتحقق من البطاقة ورقم التشغيلة. Packaging Machine Operator — Team Supervisor: package product and verify label and batch identification.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Machine Setup Technician — Entry Level",
    "profession_ar": "فني إعداد ماكينات إنتاج — مبتدئ",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "فني إعداد ماكينات إنتاج — مبتدئ: تغيير إعداد ماكينة والتحقق من جاهزية التشغيل. Machine Setup Technician — Entry Level: change a machine setup and verify production readiness.",
    "job_description": "فني إعداد ماكينات إنتاج — مبتدئ: تغيير إعداد ماكينة والتحقق من جاهزية التشغيل. Machine Setup Technician — Entry Level: change a machine setup and verify production readiness.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Machine Setup Technician — Professional",
    "profession_ar": "فني إعداد ماكينات إنتاج — ممارس",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "فني إعداد ماكينات إنتاج — ممارس: تغيير إعداد ماكينة والتحقق من جاهزية التشغيل. Machine Setup Technician — Professional: change a machine setup and verify production readiness.",
    "job_description": "فني إعداد ماكينات إنتاج — ممارس: تغيير إعداد ماكينة والتحقق من جاهزية التشغيل. Machine Setup Technician — Professional: change a machine setup and verify production readiness.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Machine Setup Technician — Team Supervisor",
    "profession_ar": "فني إعداد ماكينات إنتاج — مشرف فريق",
    "category": "Manufacturing & Production",
    "library": "Manufacturing & Production",
    "focus": "فني إعداد ماكينات إنتاج — مشرف فريق: تغيير إعداد ماكينة والتحقق من جاهزية التشغيل. Machine Setup Technician — Team Supervisor: change a machine setup and verify production readiness.",
    "job_description": "فني إعداد ماكينات إنتاج — مشرف فريق: تغيير إعداد ماكينة والتحقق من جاهزية التشغيل. Machine Setup Technician — Team Supervisor: change a machine setup and verify production readiness.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Industrial Cleaning Worker — Entry Level",
    "profession_ar": "عامل نظافة صناعية — مبتدئ",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل نظافة صناعية — مبتدئ: تنفيذ تنظيف منطقة عمل وفق خطة ومواد معتمدة. Industrial Cleaning Worker — Entry Level: clean a work area using approved plans and products.",
    "job_description": "عامل نظافة صناعية — مبتدئ: تنفيذ تنظيف منطقة عمل وفق خطة ومواد معتمدة. Industrial Cleaning Worker — Entry Level: clean a work area using approved plans and products.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Industrial Cleaning Worker — Professional",
    "profession_ar": "عامل نظافة صناعية — ممارس",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل نظافة صناعية — ممارس: تنفيذ تنظيف منطقة عمل وفق خطة ومواد معتمدة. Industrial Cleaning Worker — Professional: clean a work area using approved plans and products.",
    "job_description": "عامل نظافة صناعية — ممارس: تنفيذ تنظيف منطقة عمل وفق خطة ومواد معتمدة. Industrial Cleaning Worker — Professional: clean a work area using approved plans and products.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Industrial Cleaning Worker — Team Supervisor",
    "profession_ar": "عامل نظافة صناعية — مشرف فريق",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل نظافة صناعية — مشرف فريق: تنفيذ تنظيف منطقة عمل وفق خطة ومواد معتمدة. Industrial Cleaning Worker — Team Supervisor: clean a work area using approved plans and products.",
    "job_description": "عامل نظافة صناعية — مشرف فريق: تنفيذ تنظيف منطقة عمل وفق خطة ومواد معتمدة. Industrial Cleaning Worker — Team Supervisor: clean a work area using approved plans and products.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Laundry Operator — Entry Level",
    "profession_ar": "مشغل مغسلة — مبتدئ",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "مشغل مغسلة — مبتدئ: فرز وتشغيل وتسليم حمولة غسيل حسب التعليمات. Laundry Operator — Entry Level: sort, process and release a laundry load under instructions.",
    "job_description": "مشغل مغسلة — مبتدئ: فرز وتشغيل وتسليم حمولة غسيل حسب التعليمات. Laundry Operator — Entry Level: sort, process and release a laundry load under instructions.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Laundry Operator — Professional",
    "profession_ar": "مشغل مغسلة — ممارس",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "مشغل مغسلة — ممارس: فرز وتشغيل وتسليم حمولة غسيل حسب التعليمات. Laundry Operator — Professional: sort, process and release a laundry load under instructions.",
    "job_description": "مشغل مغسلة — ممارس: فرز وتشغيل وتسليم حمولة غسيل حسب التعليمات. Laundry Operator — Professional: sort, process and release a laundry load under instructions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Laundry Operator — Team Supervisor",
    "profession_ar": "مشغل مغسلة — مشرف فريق",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "مشغل مغسلة — مشرف فريق: فرز وتشغيل وتسليم حمولة غسيل حسب التعليمات. Laundry Operator — Team Supervisor: sort, process and release a laundry load under instructions.",
    "job_description": "مشغل مغسلة — مشرف فريق: فرز وتشغيل وتسليم حمولة غسيل حسب التعليمات. Laundry Operator — Team Supervisor: sort, process and release a laundry load under instructions.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Catering Service Worker — Entry Level",
    "profession_ar": "عامل إعاشة — مبتدئ",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل إعاشة — مبتدئ: تجهيز وتوزيع وجبات جماعية مع التتبع. Catering Service Worker — Entry Level: prepare and distribute bulk meals with traceability.",
    "job_description": "عامل إعاشة — مبتدئ: تجهيز وتوزيع وجبات جماعية مع التتبع. Catering Service Worker — Entry Level: prepare and distribute bulk meals with traceability.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Catering Service Worker — Professional",
    "profession_ar": "عامل إعاشة — ممارس",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل إعاشة — ممارس: تجهيز وتوزيع وجبات جماعية مع التتبع. Catering Service Worker — Professional: prepare and distribute bulk meals with traceability.",
    "job_description": "عامل إعاشة — ممارس: تجهيز وتوزيع وجبات جماعية مع التتبع. Catering Service Worker — Professional: prepare and distribute bulk meals with traceability.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Catering Service Worker — Team Supervisor",
    "profession_ar": "عامل إعاشة — مشرف فريق",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل إعاشة — مشرف فريق: تجهيز وتوزيع وجبات جماعية مع التتبع. Catering Service Worker — Team Supervisor: prepare and distribute bulk meals with traceability.",
    "job_description": "عامل إعاشة — مشرف فريق: تجهيز وتوزيع وجبات جماعية مع التتبع. Catering Service Worker — Team Supervisor: prepare and distribute bulk meals with traceability.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Worker Accommodation Coordinator — Entry Level",
    "profession_ar": "منسق سكن عمال — مبتدئ",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "منسق سكن عمال — مبتدئ: تنسيق إشغال سكن ومتابعة بلاغات خدماته. Worker Accommodation Coordinator — Entry Level: coordinate accommodation occupancy and service requests.",
    "job_description": "منسق سكن عمال — مبتدئ: تنسيق إشغال سكن ومتابعة بلاغات خدماته. Worker Accommodation Coordinator — Entry Level: coordinate accommodation occupancy and service requests.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Worker Accommodation Coordinator — Professional",
    "profession_ar": "منسق سكن عمال — ممارس",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "منسق سكن عمال — ممارس: تنسيق إشغال سكن ومتابعة بلاغات خدماته. Worker Accommodation Coordinator — Professional: coordinate accommodation occupancy and service requests.",
    "job_description": "منسق سكن عمال — ممارس: تنسيق إشغال سكن ومتابعة بلاغات خدماته. Worker Accommodation Coordinator — Professional: coordinate accommodation occupancy and service requests.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Worker Accommodation Coordinator — Team Supervisor",
    "profession_ar": "منسق سكن عمال — مشرف فريق",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "منسق سكن عمال — مشرف فريق: تنسيق إشغال سكن ومتابعة بلاغات خدماته. Worker Accommodation Coordinator — Team Supervisor: coordinate accommodation occupancy and service requests.",
    "job_description": "منسق سكن عمال — مشرف فريق: تنسيق إشغال سكن ومتابعة بلاغات خدماته. Worker Accommodation Coordinator — Team Supervisor: coordinate accommodation occupancy and service requests.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Waste Collection Worker — Entry Level",
    "profession_ar": "عامل جمع وفرز نفايات — مبتدئ",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل جمع وفرز نفايات — مبتدئ: جمع وفرز نفايات وفق التصنيف والإجراءات المعتمدة. Waste Collection Worker — Entry Level: collect and segregate waste under approved classification and procedures.",
    "job_description": "عامل جمع وفرز نفايات — مبتدئ: جمع وفرز نفايات وفق التصنيف والإجراءات المعتمدة. Waste Collection Worker — Entry Level: collect and segregate waste under approved classification and procedures.",
    "years_experience": "Entry level; no employment history required",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Basic",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Waste Collection Worker — Professional",
    "profession_ar": "عامل جمع وفرز نفايات — ممارس",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل جمع وفرز نفايات — ممارس: جمع وفرز نفايات وفق التصنيف والإجراءات المعتمدة. Waste Collection Worker — Professional: collect and segregate waste under approved classification and procedures.",
    "job_description": "عامل جمع وفرز نفايات — ممارس: جمع وفرز نفايات وفق التصنيف والإجراءات المعتمدة. Waste Collection Worker — Professional: collect and segregate waste under approved classification and procedures.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Medium",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  },
  {
    "profession": "Waste Collection Worker — Team Supervisor",
    "profession_ar": "عامل جمع وفرز نفايات — مشرف فريق",
    "category": "Support Services",
    "library": "Support Services",
    "focus": "عامل جمع وفرز نفايات — مشرف فريق: جمع وفرز نفايات وفق التصنيف والإجراءات المعتمدة. Waste Collection Worker — Team Supervisor: collect and segregate waste under approved classification and procedures.",
    "job_description": "عامل جمع وفرز نفايات — مشرف فريق: جمع وفرز نفايات وفق التصنيف والإجراءات المعتمدة. Waste Collection Worker — Team Supervisor: collect and segregate waste under approved classification and procedures.",
    "years_experience": "Assessed by demonstrated competence",
    "qualifications": "Relevant job skills; assess employer-specific requirements separately.",
    "certifications": "Only where required for the actual role; this interview is not a license or certification.",
    "difficulty": "Advanced",
    "question_count": 8,
    "passing_score": 70,
    "source_type": "Ready Template"
  }
];
