export const FIELD_TALENT_CAMPAIGNS = [
  {
    "slug": "technical-maintenance-2026",
    "nameAr": "حملة الفنيون والصيانة",
    "nameEn": "Field Technical & Maintenance Campaign",
    "descriptionAr": "23 قالب مقابلة في الفنيون والصيانة: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "23 interview templates in Field Technical & Maintenance: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — الفنيون والصيانة",
    "badgeEn": "VisaFlow — Field Technical & Maintenance",
    "headlineAr": "اختبر جاهزيتك في الفنيون والصيانة.",
    "headlineEn": "Test your readiness in Field Technical & Maintenance.",
    "introAr": "اختر المسار والمستوى المناسبين. القوالب الجديدة تتضمن ٨ أسئلة بالعربية أو الإنجليزية، وتحتفظ القوالب السابقة بأسئلتها الأصلية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. New templates have 8 questions in Arabic or English; existing templates retain their original questions. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "construction-trades-2026",
    "nameAr": "حملة المقاولات والمهن الميدانية",
    "nameEn": "Construction Trades Campaign",
    "descriptionAr": "15 قالب مقابلة في المقاولات والمهن الميدانية: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Construction Trades: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — المقاولات والمهن الميدانية",
    "badgeEn": "VisaFlow — Construction Trades",
    "headlineAr": "اختبر جاهزيتك في المقاولات والمهن الميدانية.",
    "headlineEn": "Test your readiness in Construction Trades.",
    "introAr": "اختر المسار والمستوى المناسبين. القوالب الجديدة تتضمن ٨ أسئلة بالعربية أو الإنجليزية، وتحتفظ القوالب السابقة بأسئلتها الأصلية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. New templates have 8 questions in Arabic or English; existing templates retain their original questions. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "transport-equipment-2026",
    "nameAr": "حملة النقل والمعدات",
    "nameEn": "Transport & Equipment Campaign",
    "descriptionAr": "15 قالب مقابلة في النقل والمعدات: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Transport & Equipment: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — النقل والمعدات",
    "badgeEn": "VisaFlow — Transport & Equipment",
    "headlineAr": "اختبر جاهزيتك في النقل والمعدات.",
    "headlineEn": "Test your readiness in Transport & Equipment.",
    "introAr": "اختر المسار والمستوى المناسبين. القوالب الجديدة تتضمن ٨ أسئلة بالعربية أو الإنجليزية، وتحتفظ القوالب السابقة بأسئلتها الأصلية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. New templates have 8 questions in Arabic or English; existing templates retain their original questions. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "manufacturing-production-2026",
    "nameAr": "حملة التصنيع والإنتاج",
    "nameEn": "Manufacturing & Production Campaign",
    "descriptionAr": "15 قالب مقابلة في التصنيع والإنتاج: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Manufacturing & Production: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — التصنيع والإنتاج",
    "badgeEn": "VisaFlow — Manufacturing & Production",
    "headlineAr": "اختبر جاهزيتك في التصنيع والإنتاج.",
    "headlineEn": "Test your readiness in Manufacturing & Production.",
    "introAr": "اختر المسار والمستوى المناسبين. القوالب الجديدة تتضمن ٨ أسئلة بالعربية أو الإنجليزية، وتحتفظ القوالب السابقة بأسئلتها الأصلية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. New templates have 8 questions in Arabic or English; existing templates retain their original questions. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  },
  {
    "slug": "support-services-2026",
    "nameAr": "حملة الخدمات المساندة",
    "nameEn": "Support Services Campaign",
    "descriptionAr": "15 قالب مقابلة في الخدمات المساندة: مبتدئ، ممارس ومشرف فريق.",
    "descriptionEn": "15 interview templates in Support Services: entry level, professional and team supervisor.",
    "professionLabelAr": "اختر المسار والمستوى الوظيفي",
    "professionLabelEn": "Select your role and level",
    "badgeAr": "VisaFlow — الخدمات المساندة",
    "badgeEn": "VisaFlow — Support Services",
    "headlineAr": "اختبر جاهزيتك في الخدمات المساندة.",
    "headlineEn": "Test your readiness in Support Services.",
    "introAr": "اختر المسار والمستوى المناسبين. القوالب الجديدة تتضمن ٨ أسئلة بالعربية أو الإنجليزية، وتحتفظ القوالب السابقة بأسئلتها الأصلية. تقبل أمثلة الدراسة والتدريب للمبتدئين. مشاركة السيرة وبيانات التواصل مع الشركات مطلوبة؛ مشاركة النتيجة اختيارية. المقابلة لا تضمن التوظيف ولا تمنح ترخيصًا مهنيًا.",
    "introEn": "Choose the appropriate role and level. New templates have 8 questions in Arabic or English; existing templates retain their original questions. Study and training examples are welcome at entry level. CV and contact sharing with employers are required; result sharing is optional. This interview does not guarantee employment or confer a professional license."
  }
];
