import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Building2, CheckCircle2, Clock3, Copy, LogOut, MailPlus, MapPinned, RefreshCw, ShieldCheck, Wallet, XCircle } from 'lucide-react'
import { getHousingSupabaseClient } from './housingSupabase.js'
import './housingOwner.css'

const today = () => new Date().toISOString().slice(0, 10)
const afterDays = (days) => { const value = new Date(); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10) }
const emptyReview = () => ({ plan: 'Standard', start: today(), end: afterDays(30), users: 10, sites: 10, amount: 0 })
const emptyInvite = () => ({ companyName: '', domain: '', adminName: '', adminEmail: '', phone: '', plan: 'Standard', start: today(), end: afterDays(365), users: 10, sites: 10, amount: 0 })

function OwnerLogin({ onLogin, busy, error }) {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  return <main className="housing-owner-login" dir="rtl"><form onSubmit={(event) => { event.preventDefault(); onLogin(email, password) }}>
    <span className="housing-owner-mark"><ShieldCheck size={30} /></span><h1>مركز إدارة سكن</h1><p>لوحة مستقلة لإدارة الشركات والاشتراكات والدعوات.</p>
    <label>البريد الإلكتروني<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label>
    <label>كلمة المرور<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>
    {error && <div className="housing-owner-error">{error}</div>}<button disabled={busy}>{busy ? 'جاري الدخول...' : 'تسجيل الدخول'}</button>
    <a href="/housing">العودة إلى منصة السكنات</a>
  </form></main>
}

function StatCard({ icon: Icon, label, value, note }) { return <article><Icon /><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</article> }

export default function HousingOwnerApp() {
  const client = useMemo(() => getHousingSupabaseClient(), [])
  const [state, setState] = useState({ loading: true, session: null, owner: null, error: '' })
  const [dashboard, setDashboard] = useState({ stats: {}, requests: [], companies: [] })
  const [page, setPage] = useState('dashboard')
  const [selected, setSelected] = useState(null)
  const [review, setReview] = useState(emptyReview())
  const [invite, setInvite] = useState(emptyInvite())
  const [inviteUrl, setInviteUrl] = useState('')
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')

  const load = async () => {
    setState((value) => ({ ...value, loading: true, error: '' }))
    const { data: { session } } = await client.auth.getSession()
    if (!session) return setState({ loading: false, session: null, owner: null, error: '' })
    const { data: context, error: contextError } = await client.rpc('housing_owner_context')
    if (contextError) return setState({ loading: false, session, owner: null, error: 'هذا الحساب غير مصرح له بالدخول إلى مركز إدارة سكن.' })
    const { data, error } = await client.rpc('housing_owner_dashboard')
    if (error) return setState({ loading: false, session, owner: context?.owner, error: error.message })
    setDashboard(data || { stats: {}, requests: [], companies: [] }); setState({ loading: false, session, owner: context?.owner, error: '' })
  }

  useEffect(() => { load(); const { data } = client.auth.onAuthStateChange(() => setTimeout(load, 0)); return () => data?.subscription?.unsubscribe() }, [client])
  const login = async (email, password) => { setBusy(true); setState((value) => ({ ...value, error: '' })); const { error } = await client.auth.signInWithPassword({ email, password }); if (error) setState({ loading: false, session: null, owner: null, error: 'بيانات الدخول غير صحيحة.' }); setBusy(false) }
  const logout = async () => { await client.auth.signOut(); window.location.assign('/housing-owner') }
  const openReview = (request) => { setSelected(request); setReview({ ...emptyReview(), plan: request.requested_plan || 'Standard', users: request.expected_users || 10, sites: request.expected_sites || 1 }); setMessage('') }
  const approve = async () => { setBusy(true); setMessage(''); const { data, error } = await client.rpc('housing_owner_review_request', { p_request_id: selected.id, p_action: 'Approve', p_plan: review.plan, p_subscription_start: review.start, p_subscription_end: review.end, p_users_limit: Number(review.users), p_sites_limit: Number(review.sites), p_monthly_amount: Number(review.amount), p_rejection_reason: null }); if (error) setMessage(error.message); else { setInviteUrl(data.invite_url); setMessage('تم اعتماد الشركة وإنشاء دعوة المدير بنجاح.'); setSelected(null); await load() } setBusy(false) }
  const reject = async (request) => { const reason = window.prompt('سبب الرفض (اختياري):', ''); if (reason === null) return; setBusy(true); const { error } = await client.rpc('housing_owner_review_request', { p_request_id: request.id, p_action: 'Reject', p_plan: 'Standard', p_rejection_reason: reason }); if (error) setMessage(error.message); else await load(); setBusy(false) }
  const setCompanyStatus = async (company, status) => { setBusy(true); const { error } = await client.rpc('housing_owner_set_company_status', { p_company_id: company.id, p_status: status }); if (error) setMessage(error.message); else await load(); setBusy(false) }
  const createDirectInvitation = async (event) => { event.preventDefault(); setBusy(true); setMessage(''); setInviteUrl(''); const { data, error } = await client.rpc('housing_owner_create_direct_invitation', { p_company_name: invite.companyName, p_domain: invite.domain || null, p_admin_name: invite.adminName, p_admin_email: invite.adminEmail, p_phone: invite.phone || null, p_plan: invite.plan, p_subscription_start: invite.start, p_subscription_end: invite.end, p_users_limit: Number(invite.users), p_sites_limit: Number(invite.sites), p_monthly_amount: Number(invite.amount) }); if (error) setMessage(error.message); else { setInviteUrl(data.invite_url); setMessage('تم إنشاء الشركة والاشتراك ودعوة المدير بنجاح. أُضيف البريد إلى طابور الإرسال.'); setInvite(emptyInvite()); await load() } setBusy(false) }
  const copyInvite = async () => { if (inviteUrl) { await navigator.clipboard.writeText(inviteUrl); setMessage('تم نسخ رابط الدعوة.') } }

  if (state.loading) return <div className="housing-owner-loading">جاري تحميل مركز إدارة سكن...</div>
  if (!state.session || !state.owner) return <OwnerLogin onLogin={login} busy={busy} error={state.error} />
  const stats = dashboard.stats || {}
  const requests = dashboard.requests || []
  const companies = dashboard.companies || []
  const nav = [
    ['dashboard', 'لوحة التحكم', BarChart3], ['requests', 'طلبات الاشتراك', Clock3], ['companies', 'الشركات والاشتراكات', Building2], ['invite', 'دعوة شركة مباشرة', MailPlus],
  ]
  const titles = { dashboard: ['لوحة التحكم', 'نظرة تنفيذية على منتج سكن والشركات والاشتراكات.'], requests: ['طلبات الاشتراك', 'راجع طلبات الشركات واعتمدها قبل إنشاء مساحة العمل.'], companies: ['الشركات والاشتراكات', 'تحكم في الخطط والسعات وحالة الوصول إلى منصة سكن.'], invite: ['دعوة شركة مباشرة', 'أنشئ الشركة والاشتراك وأرسل دعوة مديرها دون انتظار طلب تسجيل.'] }

  const RequestsPanel = ({ compact = false }) => <section className="housing-owner-panel"><div className="housing-owner-panel-head"><div><h2>{compact ? 'أحدث طلبات الاشتراك' : 'طلبات الاشتراك'}</h2><p>لا يتم إنشاء أي شركة أو حساب قبل اعتمادك.</p></div>{compact && <button className="text-action" onClick={() => setPage('requests')}>عرض الكل</button>}</div><div className="housing-owner-table"><table><thead><tr><th>الشركة</th><th>مدير الحساب</th><th>الطلب</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{(compact ? requests.slice(0, 5) : requests).map((request) => <tr key={request.id}><td><strong>{request.company_name}</strong><small>{request.email}<br />{request.phone || '-'}</small></td><td>{request.admin_name}</td><td>{request.requested_plan}<small>{request.expected_users} مستخدم · {request.expected_sites} سكن</small></td><td><span className={`housing-owner-status ${request.status.toLowerCase()}`}>{request.status}</span></td><td>{request.status === 'Pending' ? <div className="housing-owner-actions"><button onClick={() => openReview(request)}><CheckCircle2 size={15} /> اعتماد</button><button className="danger" onClick={() => reject(request)}><XCircle size={15} /> رفض</button></div> : '—'}</td></tr>)}{!requests.length && <tr><td colSpan="5">لا توجد طلبات حتى الآن.</td></tr>}</tbody></table></div></section>
  const CompaniesPanel = ({ compact = false }) => <section className="housing-owner-panel"><div className="housing-owner-panel-head"><div><h2>{compact ? 'أحدث الشركات' : 'الشركات والاشتراكات'}</h2><p>التحكم في وصول كل شركة إلى منتج سكن.</p></div>{compact && <button className="text-action" onClick={() => setPage('companies')}>عرض الكل</button>}</div><div className="housing-owner-company-grid">{(compact ? companies.slice(0, 4) : companies).map((company) => <article key={company.id}><header><div><h3>{company.name}</h3><span>{company.primary_admin_email || '-'}</span></div><span className={`housing-owner-status ${String(company.status).toLowerCase()}`}>{company.status}</span></header><div><span>الخطة<strong>{company.plan}</strong></span><span>المستخدمون<strong>{company.users_limit}</strong></span><span>السكنات<strong>{company.sites}/{company.sites_limit}</strong></span><span>المقيمون<strong>{company.residents}</strong></span></div><footer><span>{Number(company.monthly_amount || 0).toLocaleString()} ر.س شهريًا</span>{company.status === 'Active' ? <button className="danger" onClick={() => setCompanyStatus(company, 'Suspended')}>إيقاف</button> : <button onClick={() => setCompanyStatus(company, 'Active')}>تفعيل</button>}</footer></article>)}{!companies.length && <div className="housing-owner-empty">لا توجد شركات حتى الآن.</div>}</div></section>

  return <main className="housing-owner-app" dir="rtl">
    <aside><div className="housing-owner-logo"><Building2 size={25} /><div><strong>مركز إدارة سكن</strong><span>SAKAN MANAGEMENT CENTER</span></div></div><nav>{nav.map(([key, label, Icon]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => setPage(key)}><Icon size={19} />{label}{key === 'requests' && stats.pending_requests > 0 && <b>{stats.pending_requests}</b>}</button>)}</nav><div className="housing-owner-account"><strong>{state.owner.full_name}</strong><span>{state.owner.email}</span><button onClick={logout}><LogOut size={17} /> خروج</button></div></aside>
    <section className="housing-owner-content"><header><div><p>SAKAN MANAGEMENT CENTER</p><h1>{titles[page][0]}</h1><span>{titles[page][1]}</span></div><div className="housing-owner-header-actions">{page !== 'invite' && <button className="primary" onClick={() => setPage('invite')}><MailPlus size={17} /> دعوة شركة</button>}<button onClick={load}><RefreshCw size={17} /> تحديث</button></div></header>
      {message && <div className={message.includes('بنجاح') || message.includes('نسخ') ? 'housing-owner-message' : 'housing-owner-message error'}><span>{message}</span>{inviteUrl && <button onClick={copyInvite}><Copy size={16} /> نسخ الرابط</button>}</div>}
      {inviteUrl && <div className="housing-owner-invite-result"><strong>رابط دعوة المدير</strong><code dir="ltr">{inviteUrl}</code><button onClick={copyInvite}><Copy size={16} /> نسخ</button></div>}
      {page === 'dashboard' && <><div className="housing-owner-stats"><StatCard icon={Clock3} label="طلبات معلقة" value={stats.pending_requests || 0} note="بانتظار المراجعة" /><StatCard icon={Building2} label="شركات نشطة" value={stats.active_companies || 0} note={`${stats.suspended_companies || 0} شركة موقوفة`} /><StatCard icon={MapPinned} label="إجمالي السكنات" value={stats.total_sites || 0} note={`${stats.active_residents || 0} مقيم حاليًا`} /><StatCard icon={Wallet} label="الإيراد الشهري" value={`${Number(stats.monthly_revenue || 0).toLocaleString()} ر.س`} note={`${stats.expiring_subscriptions || 0} اشتراك ينتهي خلال 30 يومًا`} /></div><div className="housing-owner-quick-actions"><button onClick={() => setPage('invite')}><MailPlus /><span><strong>دعوة شركة مباشرة</strong><small>أنشئ اشتراكًا ورابط دخول للمدير</small></span></button><button onClick={() => setPage('requests')}><Clock3 /><span><strong>مراجعة الطلبات</strong><small>{stats.pending_requests || 0} طلب بانتظار قرارك</small></span></button><button onClick={() => setPage('companies')}><Building2 /><span><strong>إدارة الشركات</strong><small>الخطط والسعات وحالة الاشتراك</small></span></button></div><RequestsPanel compact /><CompaniesPanel compact /></>}
      {page === 'requests' && <RequestsPanel />}
      {page === 'companies' && <CompaniesPanel />}
      {page === 'invite' && <section className="housing-owner-panel housing-owner-invite-panel"><div className="housing-owner-panel-head"><div><h2>بيانات الشركة والاشتراك</h2><p>سيُنشئ النظام الشركة ثم دعوة المدير، ويضع رسالة البريد في طابور الإرسال.</p></div></div><form onSubmit={createDirectInvitation} className="housing-owner-direct-form"><div className="housing-owner-form-grid"><label>اسم الشركة *<input required minLength="2" value={invite.companyName} onChange={(event) => setInvite((value) => ({ ...value, companyName: event.target.value }))} /></label><label>نطاق الشركة<input dir="ltr" placeholder="company.sa" value={invite.domain} onChange={(event) => setInvite((value) => ({ ...value, domain: event.target.value }))} /></label><label>اسم المدير الأساسي *<input required minLength="2" value={invite.adminName} onChange={(event) => setInvite((value) => ({ ...value, adminName: event.target.value }))} /></label><label>بريد المدير *<input required type="email" dir="ltr" value={invite.adminEmail} onChange={(event) => setInvite((value) => ({ ...value, adminEmail: event.target.value }))} /></label><label>رقم الجوال<input dir="ltr" value={invite.phone} onChange={(event) => setInvite((value) => ({ ...value, phone: event.target.value }))} /></label><label>الخطة<select value={invite.plan} onChange={(event) => setInvite((value) => ({ ...value, plan: event.target.value }))}><option>Starter</option><option>Standard</option><option>Enterprise</option></select></label><label>عدد المستخدمين<input required type="number" min="1" value={invite.users} onChange={(event) => setInvite((value) => ({ ...value, users: event.target.value }))} /></label><label>عدد السكنات<input required type="number" min="1" value={invite.sites} onChange={(event) => setInvite((value) => ({ ...value, sites: event.target.value }))} /></label><label>بداية الاشتراك<input required type="date" value={invite.start} onChange={(event) => setInvite((value) => ({ ...value, start: event.target.value }))} /></label><label>نهاية الاشتراك<input required type="date" value={invite.end} onChange={(event) => setInvite((value) => ({ ...value, end: event.target.value }))} /></label><label className="wide">القيمة الشهرية (ر.س)<input required type="number" min="0" step="0.01" value={invite.amount} onChange={(event) => setInvite((value) => ({ ...value, amount: event.target.value }))} /></label></div><footer><button className="primary" disabled={busy}><MailPlus size={18} />{busy ? 'جاري إنشاء الدعوة...' : 'إنشاء الشركة وإرسال الدعوة'}</button></footer></form></section>}
    </section>
    {selected && <div className="housing-owner-modal-backdrop"><form className="housing-owner-modal" onSubmit={(event) => { event.preventDefault(); approve() }}><header><div><h2>اعتماد {selected.company_name}</h2><p>سيُنشئ النظام الشركة ودعوة مديرها بعد الحفظ.</p></div><button type="button" onClick={() => setSelected(null)}>×</button></header><div className="housing-owner-form-grid"><label>الخطة<select value={review.plan} onChange={(event) => setReview((value) => ({ ...value, plan: event.target.value }))}><option>Starter</option><option>Standard</option><option>Enterprise</option></select></label><label>عدد المستخدمين<input type="number" min="1" value={review.users} onChange={(event) => setReview((value) => ({ ...value, users: event.target.value }))} /></label><label>عدد السكنات<input type="number" min="1" value={review.sites} onChange={(event) => setReview((value) => ({ ...value, sites: event.target.value }))} /></label><label>القيمة الشهرية<input type="number" min="0" value={review.amount} onChange={(event) => setReview((value) => ({ ...value, amount: event.target.value }))} /></label><label>بداية الاشتراك<input type="date" required value={review.start} onChange={(event) => setReview((value) => ({ ...value, start: event.target.value }))} /></label><label>نهاية الاشتراك<input type="date" required value={review.end} onChange={(event) => setReview((value) => ({ ...value, end: event.target.value }))} /></label></div><footer><button type="button" onClick={() => setSelected(null)}>إلغاء</button><button className="primary" disabled={busy}>{busy ? 'جاري الاعتماد...' : 'اعتماد وإنشاء الدعوة'}</button></footer></form></div>}
  </main>
}
