import { CheckCircle2, Copy, LoaderCircle, Plus, ShieldCheck, UserCog, UserX, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { createHousingUserInvitation, listHousingInvitations, listHousingUsers, revokeHousingUserInvitation, updateHousingUserAccess } from './housingService.mjs'
import { useHousingLanguage } from './housingI18n.jsx'

const ROLES = ['Admin','Housing Manager','Housing Supervisor','Maintenance','Finance','Viewer']
const ROLE_MATRIX = {
  Admin: ['all'],
  'Housing Manager': ['housing','occupancy','maintenance','inspections','assets','safety','operations','welfare','finance','reports'],
  'Housing Supervisor': ['housing','occupancy','maintenance','inspections','assets','safety','operations','welfare','reports'],
  Maintenance: ['housing','maintenance','assets','reports'],
  Finance: ['housing','finance','reports'],
  Viewer: ['read'],
}

function SiteChecks({ sites, selected, onChange, disabled }) {
  return <div className="housing-site-scope">{sites.map((site)=><label key={site.id}><input type="checkbox" disabled={disabled} checked={selected.includes(site.id)} onChange={(event)=>onChange(event.target.checked?[...selected,site.id]:selected.filter((id)=>id!==site.id))}/><span>{site.code} · {site.name}</span></label>)}</div>
}

function UserAccessRow({ user, sites, currentUserId, onSave, saving, language }) {
  const [role,setRole]=useState(user.role);const[status,setStatus]=useState(user.status);const[siteIds,setSiteIds]=useState((user.site_scopes||[]).map((item)=>item.site_id));const broad=['Admin','Housing Manager','Finance','Viewer'].includes(role)
  return <article className="housing-user-card"><div className="housing-user-identity"><span>{user.full_name?.slice(0,1)?.toUpperCase()}</span><div><strong>{user.full_name}</strong><small>{user.email}</small></div><b className={status==='Active'?'active':'inactive'}>{status}</b></div><div className="housing-user-controls"><label><span>{language==='ar'?'الدور':'Role'}</span><select value={role} disabled={user.id===currentUserId} onChange={(event)=>setRole(event.target.value)}>{ROLES.map((item)=><option key={item}>{item}</option>)}</select></label><label><span>{language==='ar'?'الحالة':'Status'}</span><select value={status} disabled={user.id===currentUserId} onChange={(event)=>setStatus(event.target.value)}><option>Active</option><option>Inactive</option></select></label></div><div><small className="housing-scope-label">{broad?(language==='ar'?'الوصول إلى جميع السكنات':'Access to all housing sites'):(language==='ar'?'السكنات المسموح بها':'Allowed housing sites')}</small>{!broad&&<SiteChecks sites={sites} selected={siteIds} onChange={setSiteIds}/>}</div><button className="housing-primary-button" disabled={saving||user.id===currentUserId} onClick={()=>onSave({profileId:user.id,role,status,siteIds:broad?[]:siteIds})}>{saving?<LoaderCircle className="housing-spin" size={16}/>:<UserCog size={16}/>} {language==='ar'?'حفظ الصلاحيات':'Save Access'}</button></article>
}

function InviteModal({ sites, onClose, onInvite, saving }) {
  const {language}=useHousingLanguage();const[form,setForm]=useState({fullName:'',email:'',role:'Housing Supervisor',siteIds:[]});const broad=['Admin','Housing Manager','Finance','Viewer'].includes(form.role);const update=(key)=>(event)=>setForm((value)=>({...value,[key]:event.target.value}))
  return <div className="housing-modal-backdrop" onMouseDown={onClose}><div className="housing-modal" onMouseDown={(event)=>event.stopPropagation()}><header><div><h2>{language==='ar'?'دعوة مستخدم':'Invite User'}</h2><p>{language==='ar'?'أنشئ رابط دعوة وحدد الدور ونطاق السكنات':'Create an invitation link and assign access'}</p></div><button onClick={onClose}><X size={20}/></button></header><form onSubmit={(event)=>{event.preventDefault();onInvite({...form,siteIds:broad?[]:form.siteIds})}}><div className="housing-form-grid"><label><span>{language==='ar'?'الاسم الكامل':'Full Name'}</span><input required value={form.fullName} onChange={update('fullName')}/></label><label><span>{language==='ar'?'البريد الإلكتروني':'Email'}</span><input required type="email" value={form.email} onChange={update('email')}/></label><label className="full"><span>{language==='ar'?'الدور':'Role'}</span><select value={form.role} onChange={update('role')}>{ROLES.map((role)=><option key={role}>{role}</option>)}</select></label>{!broad&&<label className="full"><span>{language==='ar'?'السكنات المسموح بها':'Allowed Housing Sites'}</span><SiteChecks sites={sites} selected={form.siteIds} onChange={(siteIds)=>setForm((value)=>({...value,siteIds}))}/></label>}</div><footer><button type="button" className="housing-secondary-button" onClick={onClose}>{language==='ar'?'إلغاء':'Cancel'}</button><button className="housing-primary-button" disabled={saving}>{saving?<LoaderCircle className="housing-spin" size={16}/>:<Plus size={16}/>} {language==='ar'?'إنشاء الدعوة':'Create Invitation'}</button></footer></form></div></div>
}

export function HousingSettingsPage({ client, sites, currentProfile }) {
  const {language,t}=useHousingLanguage();const isAdmin=currentProfile?.role==='Admin';const[users,setUsers]=useState([]);const[invitations,setInvitations]=useState([]);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[inviteOpen,setInviteOpen]=useState(false);const[copied,setCopied]=useState('')
  const load=useCallback(async()=>{if(!client||!isAdmin)return;setLoading(true);setError('');try{const [nextUsers,nextInvites]=await Promise.all([listHousingUsers(client),listHousingInvitations(client)]);setUsers(nextUsers);setInvitations(nextInvites)}catch(reason){setError(reason.message)}finally{setLoading(false)}},[client,isAdmin])
  useEffect(()=>{load()},[load])
  const invite=async(input)=>{setSaving(true);setError('');try{const result=await createHousingUserInvitation(client,input);setInviteOpen(false);await load();const url=`${window.location.origin}/housing?invite=${result.token}`;await navigator.clipboard.writeText(url);setCopied(language==='ar'?'تم إنشاء الدعوة ونسخ الرابط':'Invitation created and link copied')}catch(reason){setError(reason.message)}finally{setSaving(false)}}
  const saveUser=async(input)=>{setSaving(true);setError('');try{await updateHousingUserAccess(client,input);await load();setCopied(language==='ar'?'تم تحديث الصلاحيات':'Access updated')}catch(reason){setError(reason.message)}finally{setSaving(false)}}
  const copyInvite=async(invitation)=>{await navigator.clipboard.writeText(`${window.location.origin}/housing?invite=${invitation.token}`);setCopied(language==='ar'?'تم نسخ رابط الدعوة':'Invitation link copied')}
  const revoke=async(id)=>{setSaving(true);try{await revokeHousingUserInvitation(client,id);await load()}catch(reason){setError(reason.message)}finally{setSaving(false)}}
  return <div className="housing-settings-stack"><section className="housing-panel housing-role-matrix"><div className="housing-panel-head"><div><h2>{language==='ar'?'الأدوار والصلاحيات':'Roles & Permissions'}</h2><p>{language==='ar'?'صلاحيات النظام ونطاق الوصول':'System permissions and access scope'}</p></div>{isAdmin&&<button className="housing-primary-button" onClick={()=>setInviteOpen(true)}><Plus size={17}/>{language==='ar'?'دعوة مستخدم':'Invite User'}</button>}</div><div className="housing-role-grid">{ROLES.map((role)=><article key={role}><ShieldCheck size={19}/><strong>{role}</strong><p>{ROLE_MATRIX[role].join(' · ')}</p></article>)}</div></section>
    {!isAdmin&&<section className="housing-panel housing-inline-empty"><UserX size={26}/><strong>{language==='ar'?'إدارة المستخدمين متاحة لمدير النظام فقط':'User management is available to administrators only'}</strong></section>}
    {isAdmin&&<><section className="housing-panel"><div className="housing-panel-head"><div><h2>{language==='ar'?'مستخدمو المنصة':'Platform Users'}</h2><p>{t('liveData')}</p></div>{loading&&<LoaderCircle className="housing-spin" size={18}/>}</div>{error&&<div className="housing-access-message error">{error}</div>}<div className="housing-users-grid">{users.map((user)=><UserAccessRow key={user.id} user={user} sites={sites} currentUserId={currentProfile.id} onSave={saveUser} saving={saving} language={language}/>)}</div></section>
      <section className="housing-panel housing-table-panel"><div className="housing-panel-head"><div><h2>{language==='ar'?'الدعوات':'Invitations'}</h2><p>{language==='ar'?'صالحة لمدة 7 أيام':'Valid for 7 days'}</p></div></div><div className="housing-table-wrap"><table><thead><tr><th>{language==='ar'?'المستخدم':'User'}</th><th>{language==='ar'?'الدور':'Role'}</th><th>{language==='ar'?'الحالة':'Status'}</th><th>{language==='ar'?'الانتهاء':'Expires'}</th><th>{language==='ar'?'الإجراء':'Action'}</th></tr></thead><tbody>{invitations.map((item)=><tr key={item.id}><td><strong>{item.full_name}</strong><small>{item.email}</small></td><td>{item.role}</td><td>{item.status}</td><td>{new Date(item.expires_at).toLocaleDateString(language==='ar'?'ar-SA':'en-US')}</td><td>{item.status==='Pending'&&<div className="housing-invite-actions"><button onClick={()=>copyInvite(item)}><Copy size={15}/>{language==='ar'?'نسخ الرابط':'Copy Link'}</button><button onClick={()=>revoke(item.id)}><UserX size={15}/>{language==='ar'?'إلغاء':'Revoke'}</button></div>}</td></tr>)}</tbody></table></div></section></>}
    {copied&&<div className="housing-access-message"><CheckCircle2 size={16}/>{copied}</div>}{inviteOpen&&<InviteModal sites={sites} onClose={()=>setInviteOpen(false)} onInvite={invite} saving={saving}/>}</div>
}
