import { AlertTriangle, BellRing, CalendarClock, CheckCircle2, ChevronLeft, ClipboardCheck, Clock3, Languages, LoaderCircle, MessageSquareText, PackageCheck, ShieldCheck, Shirt, Sparkles, TriangleAlert, Upload, Users, Utensils } from 'lucide-react'
import { calculateLegalCapacity, canAssignToRoom } from './housingCompliance.mjs'
import { useHousingLanguage } from './housingI18n.jsx'
import { useState } from 'react'
import { HousingDetailsModal } from './HousingRecordModal.jsx'

function Stat({ icon: Icon,label,value,detail,tone='blue' }) { return <article className="housing-advanced-stat"><span className={tone}><Icon size={20}/></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article> }

export function ComplianceDashboard({ data={licenses:[],hseReports:[],alerts:[]} ,onAcknowledge,onUploadAttachment }) {
  const {language,t}=useHousingLanguage(); const b=(ar,en)=>language==='ar'?ar:en
  const [selectedLicense,setSelectedLicense]=useState(null)
  const [uploadingReportId,setUploadingReportId]=useState('')
  const [uploadError,setUploadError]=useState('')
  const licenses=data.licenses||[]; const reports=data.hseReports||[]; const alerts=data.alerts||[]; const openAlerts=alerts.filter((item)=>item.status==='Open')
  const upload=async(report,file,input)=>{if(!file||!onUploadAttachment)return;setUploadingReportId(report.id);setUploadError('');try{await onUploadAttachment(report,file)}catch(reason){setUploadError(reason?.message||b('تعذر رفع المرفق','Unable to upload attachment'))}finally{setUploadingReportId('');input.value=''}}
  return <div className="housing-advanced-stack">
    <section className="housing-advanced-stats"><Stat icon={ShieldCheck} label={b('نسبة الامتثال','Compliance rate')} value={openAlerts.length?'تحت المراجعة / Review':'100%'} detail={t('liveData')} tone="green"/><Stat icon={BellRing} label={b('التراخيص','Licenses')} value={licenses.length} detail={b('مرتبطة بقاعدة البيانات','Live database records')} tone="amber"/><Stat icon={ClipboardCheck} label={b('تقارير HSE','HSE reports')} value={reports.length} detail={b('نماذج رقمية ومرفقات','Digital checklists and attachments')} tone="blue"/><Stat icon={TriangleAlert} label={t('complianceAlerts')} value={openAlerts.length} detail={t('warningOnly')} tone="red"/></section>
    <section className="housing-advanced-grid"><article className="housing-panel"><div className="housing-panel-head"><div><h2>{b('متتبع التراخيص والسجلات','License & Record Tracker')}</h2><p>{t('liveData')}</p></div></div><div className="housing-license-list">{licenses.length===0?<p>{t('noRecords')}</p>:licenses.map((license)=><div key={license.id}><span className={`housing-license-icon ${license.status==='Expired'?'red':'amber'}`}><CalendarClock size={18}/></span><div><strong>{license.license_type}</strong><small>{license.site?.name} · {license.license_number}</small></div><div className="housing-license-date"><b>{license.expiry_date}</b><small>{license.status}</small></div><button onClick={()=>setSelectedLicense(license)} aria-label={t('details')}><ChevronLeft size={18}/></button></div>)}</div></article>
      <article className="housing-panel"><div className="housing-panel-head"><div><h2>{b('فحوصات السلامة HSE','HSE Safety Checks')}</h2><p>{b(`جميع النتائج من قاعدة البيانات · ${reports.length} سجل`,`All live database results · ${reports.length} records`)}</p></div></div>{uploadError&&<div className="housing-inline-error">{uploadError}</div>}<div className="housing-checklist">{reports.length===0?<p>{t('noRecords')}</p>:reports.map((report)=><div key={report.id}>{report.critical_findings?<AlertTriangle className="warn" size={19}/>:<CheckCircle2 className="ok" size={19}/>}<span>{report.report_no} · {report.site?.name}</span><b className={report.critical_findings?'warn':'ok'}>{report.score??'—'}%</b><label className="housing-hse-upload" title={b('رفع صورة أو ملف PDF','Upload image or PDF')}>{uploadingReportId===report.id?<LoaderCircle className="housing-spin" size={14}/>:<Upload size={14}/>}<em>{report.attachments?.length||0}</em><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={Boolean(uploadingReportId)} onChange={(event)=>upload(report,event.target.files?.[0],event.target)}/></label></div>)}</div></article></section>
    <section className="housing-panel housing-rule-banner"><ShieldCheck size={25}/><div><h3>{b('تنبيه معيار المساحة مفعّل','Area threshold alerts are enabled')}</h3><p>{b('كل عامل يحتاج 4 م². يسمح النظام بالتسكين ويسجل تنبيهًا قابلًا للمراجعة عند التجاوز.','Each worker requires 4 m². Assignment remains allowed and an auditable alert is recorded when exceeded.')}</p></div><strong>{t('areaPerWorker')}</strong></section>
    <section className="housing-panel"><div className="housing-panel-head"><div><h2>{t('complianceAlerts')}</h2><p>{t('warningOnly')}</p></div></div><div className="housing-live-alerts">{alerts.length===0?<p>{t('noRecords')}</p>:alerts.map((alert)=><div key={alert.id}><AlertTriangle size={18}/><div><strong>{alert.title}</strong><small>{alert.site?.name} · {alert.room?.room_number} · {alert.employee?.full_name}</small></div><span>{alert.details?.occupants_after_assignment}/{alert.details?.legal_capacity}</span>{alert.status==='Open'&&onAcknowledge?<button onClick={()=>onAcknowledge(alert.id)}>{b('تم الاطلاع','Acknowledge')}</button>:<b>{alert.status}</b>}</div>)}</div></section>
    {selectedLicense&&<HousingDetailsModal title={selectedLicense.license_type} rows={[{label:b('رقم الترخيص','License Number'),value:selectedLicense.license_number},{label:t('housing'),value:selectedLicense.site?.name},{label:b('جهة الإصدار','Issuing Authority'),value:selectedLicense.issuing_authority},{label:b('تاريخ الإصدار','Issue Date'),value:selectedLicense.issue_date},{label:b('تاريخ الانتهاء','Expiry Date'),value:selectedLicense.expiry_date},{label:b('الحالة','Status'),value:selectedLicense.status}]} onClose={()=>setSelectedLicense(null)}/>}
  </div>
}

const sampleRooms=[{room:'A-204',site:'سكن النخيل',project:'مشروع المترو',shift:'Day',language:'ar / ur',area:24,beds:6,occupied:4},{room:'B-112',site:'سكن النخيل',project:'مشروع المترو',shift:'Night',language:'hi / en',area:20,beds:6,occupied:5}]
export function SmartOccupancyPage({data={rooms:[],assignments:[]}}) {
  const {language,t}=useHousingLanguage();const b=(ar,en)=>language==='ar'?ar:en
  const source=data.rooms?.length?data.rooms.map((room)=>({room:room.room_number,site:room.site?.name||'—',project:room.preferred_project_id?'Project':'Any',shift:room.allowed_shift,language:room.preferred_language||b('مرنة','Flexible'),area:Number(room.area_sqm),beds:room.beds?.length||room.capacity,occupied:data.assignments.filter((item)=>item.room_id===room.id).length})):sampleRooms
  const available=source.reduce((sum,item)=>sum+Math.max(0,item.beds-item.occupied),0)
  return <div className="housing-advanced-stack"><section className="housing-advanced-stats"><Stat icon={Users} label={t('activeResidents')} value={data.assignments?.length||0} detail={t('liveData')} tone="blue"/><Stat icon={Sparkles} label={t('availableBeds')} value={available} detail={b('حسب المشروع والوردية','By project and shift')} tone="green"/><Stat icon={Clock3} label={b('غرف بنوبات محددة','Shift-aligned rooms')} value={source.filter((item)=>item.shift!=='Any').length} detail={b('نهاري / ليلي','Day / Night')} tone="purple"/><Stat icon={AlertTriangle} label={t('complianceAlerts')} value={data.alerts?.filter((a)=>a.status==='Open').length||0} detail={t('warningOnly')} tone="amber"/></section><section className="housing-panel"><div className="housing-panel-head"><div><h2>{b('مطابقة الغرف الذكية','Smart Room Matching')}</h2><p>{b('المساحة والمشروع والوردية واللغة','Area, project, shift and language')}</p></div></div><div className="housing-smart-grid">{source.map((item)=>{const legal=calculateLegalCapacity({areaSqm:item.area,configuredCapacity:item.beds,minimumAreaPerPersonSqm:4});const decision=canAssignToRoom({areaSqm:item.area,configuredCapacity:item.beds,minimumAreaPerPersonSqm:4,currentOccupants:item.occupied});return <article key={`${item.site}-${item.room}`} className={decision.compliant?'':'blocked'}><header><div><strong>{item.room}</strong><span>{item.site}</span></div><b>{item.occupied}/{legal}</b></header><p><PackageCheck size={15}/>{item.project}</p><p><Clock3 size={15}/>{item.shift}</p><p><Languages size={15}/>{item.language}</p><div className="housing-smart-capacity"><span>{item.area} m²</span><span>{t('legalCapacity')} {legal}</span></div><footer>{decision.compliant?<><CheckCircle2 size={17}/>{b('متاح ومتوافق','Available & compliant')}</>:<><TriangleAlert size={17}/>{b('متاح مع تنبيه','Available with warning')}</>}</footer></article>})}</div></section></div>
}

export function CateringLaundryPage({data={operations:[]}}){const{language,t}=useHousingLanguage();const b=(ar,en)=>language==='ar'?ar:en;const[selected,setSelected]=useState(null);const operations=data.operations||[];return <div className="housing-advanced-stack"><section className="housing-advanced-stats"><Stat icon={Utensils} label={b('جداول الوجبات','Meal schedules')} value={operations.filter((o)=>['Breakfast','Lunch','Dinner'].includes(o.operation_type)).length} detail={t('liveData')} tone="green"/><Stat icon={Shirt} label={b('جداول المغاسل','Laundry schedules')} value={operations.filter((o)=>o.operation_type?.includes('Laundry')).length} detail={t('liveData')} tone="blue"/><Stat icon={Clock3} label={b('إجمالي الجداول','Total schedules')} value={operations.length} detail={b('حسب السعة التشغيلية','Capacity-based')} tone="amber"/></section><section className="housing-operation-grid">{operations.length===0?<article className="housing-panel"><p>{t('noRecords')}</p></article>:operations.map((slot)=>{const Icon=slot.operation_type?.includes('Laundry')?Shirt:Utensils;return <article className="housing-panel" key={slot.id}><span className="green"><Icon size={23}/></span><div><h3>{slot.operation_type}</h3><p>{slot.schedule_date} · {slot.slot_start}—{slot.slot_end}</p><small>{slot.site?.name} · {slot.planned_people}/{slot.slot_capacity}</small></div><button onClick={()=>setSelected(slot)}>{t('details')}<ChevronLeft size={16}/></button></article>})}</section>{selected&&<HousingDetailsModal title={selected.operation_type} rows={[{label:t('housing'),value:selected.site?.name},{label:b('التاريخ','Date'),value:selected.schedule_date},{label:b('البداية','Start'),value:selected.slot_start},{label:b('النهاية','End'),value:selected.slot_end},{label:b('العدد المخطط','Planned People'),value:selected.planned_people},{label:t('capacity'),value:selected.slot_capacity},{label:b('الحالة','Status'),value:selected.status}]} onClose={()=>setSelected(null)}/>}</div>}

export function WelfarePage({data={surveys:[],incidents:[]}}){const{language,t}=useHousingLanguage();const b=(ar,en)=>language==='ar'?ar:en;const surveys=data.surveys||[];const incidents=data.incidents||[];const responses=surveys.flatMap((s)=>s.responses||[]);const avg=responses.length?(responses.reduce((sum,r)=>sum+Number(r.overall_score||0),0)/responses.length).toFixed(1):'—';return <div className="housing-advanced-stack"><section className="housing-advanced-stats"><Stat icon={MessageSquareText} label={b('مؤشر الرضا','Satisfaction score')} value={avg==='—'?avg:`${avg}/5`} detail={`${responses.length} ${b('استجابة','responses')}`} tone="green"/><Stat icon={Languages} label={b('الاستبيانات','Surveys')} value={surveys.length} detail={b('متعددة اللغات','Multilingual')} tone="blue"/><Stat icon={AlertTriangle} label={b('المخالفات','Incidents')} value={incidents.length} detail={t('liveData')} tone="amber"/></section><section className="housing-advanced-grid"><article className="housing-panel"><div className="housing-panel-head"><div><h2>{b('استبيانات الرفاهية','Welfare Surveys')}</h2><p>{t('liveData')}</p></div></div><div className="housing-welfare-incidents">{surveys.length===0?<p>{t('noRecords')}</p>:surveys.map((survey)=><div key={survey.id}><span className="green"><MessageSquareText size={17}/></span><div><strong>{survey.title}</strong><small>{survey.site?.name} · {(survey.languages||[]).join(', ')}</small></div><b>{survey.status}</b></div>)}</div></article><article className="housing-panel"><div className="housing-panel-head"><div><h2>{b('المخالفات المرتبطة بالعامل','Worker-linked Incidents')}</h2><p>{t('liveData')}</p></div></div><div className="housing-welfare-incidents">{incidents.length===0?<p>{t('noRecords')}</p>:incidents.map((incident)=><div key={incident.id}><span className="amber"><AlertTriangle size={17}/></span><div><strong>{incident.incident_type}</strong><small>{incident.employee?.full_name} · {incident.site?.name}</small></div><b>{incident.status}</b></div>)}</div></article></section></div>}
