import { useMemo, useState } from 'react'
import { Car, DoorOpen, PackageOpen, ShieldCheck } from 'lucide-react'
import { transitionHousingGateRecord } from './housingService.mjs'
import { useHousingLanguage } from './housingI18n.jsx'

const config={
  Visitor:{table:'housing_gate_visitors',prefix:'VIS',fields:[['visitor_name','Visitor name'],['organization','Organization'],['purpose','Purpose'],['host_name','Host name'],['vehicle_plate','Vehicle plate']]},
  Delivery:{table:'housing_gate_deliveries',prefix:'DEL',fields:[['supplier_name','Supplier'],['driver_name','Driver name'],['vehicle_plate','Vehicle plate'],['quantity','Quantity'],['unit','Unit']]},
  Pass:{table:'housing_gate_passes',prefix:'PASS',fields:[['item_description','Item / asset description'],['quantity','Quantity'],['reason','Reason'],['destination','Destination'],['approved_by_name','Approver name']]},
}
export default function HousingSecurityPage({data,onCreate,client,canManage,onRefresh,saving}){
 const {language}=useHousingLanguage();const ar=language==='ar';const [kind,setKind]=useState('Visitor');const [siteId,setSiteId]=useState('');const [values,setValues]=useState({});const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const visitors=data.gateVisitors||[],deliveries=data.gateDeliveries||[],passes=data.gatePasses||[]
 const overdue=useMemo(()=>passes.filter(x=>x.status==='Checked Out'&&x.expected_return_at&&new Date(x.expected_return_at)<new Date()).length,[passes])
 const submit=async(e)=>{e.preventDefault();setError('');const c=config[kind];const no=`${c.prefix}-${Date.now().toString().slice(-8)}`;let payload={...values,site_id:siteId};if(kind==='Visitor')payload={...payload,visit_no:no,status:'Checked In'};if(kind==='Delivery')payload={...payload,delivery_no:no,delivery_type:values.delivery_type||'Other',status:'On Site'};if(kind==='Pass')payload={...payload,pass_no:no,status:'Draft',quantity:Number(values.quantity||1),expected_return_at:values.expected_return_at||null};try{await onCreate(c.table,payload);setValues({})}catch(reason){setError(reason.message)}}
 const transition=async(entity,id,action)=>{setBusy(true);setError('');try{await transitionHousingGateRecord(client,entity,id,action);await onRefresh()}catch(reason){setError(reason.message)}finally{setBusy(false)}}
 return <div className="housing-security-stack"><section className="housing-advanced-stats">
  <article className="housing-advanced-stat"><span className="green"><DoorOpen/></span><div><small>{ar?'زوار داخل السكن':'Visitors on site'}</small><strong>{visitors.filter(x=>x.status==='Checked In').length}</strong><p>{ar?'بانتظار تسجيل الخروج':'Awaiting checkout'}</p></div></article>
  <article className="housing-advanced-stat"><span className="blue"><Car/></span><div><small>{ar?'مركبات التوصيل':'Deliveries on site'}</small><strong>{deliveries.filter(x=>x.status==='On Site').length}</strong><p>{ar?'تموين ومياه وخدمات':'Catering, water and services'}</p></div></article>
  <article className="housing-advanced-stat"><span className="purple"><PackageOpen/></span><div><small>{ar?'تصاريح أصول مفتوحة':'Open asset passes'}</small><strong>{passes.filter(x=>['Approved','Checked Out'].includes(x.status)).length}</strong><p>{ar?'أصول خارج السكن':'Assets outside site'}</p></div></article>
  <article className="housing-advanced-stat"><span className="red"><ShieldCheck/></span><div><small>{ar?'متأخر عن الإرجاع':'Overdue returns'}</small><strong>{overdue}</strong><p>{ar?'يتطلب متابعة أمنية':'Security follow-up'}</p></div></article>
 </section>{canManage&&<form className="housing-panel housing-gate-form" onSubmit={submit}><header className="housing-panel-header"><div><h2>{ar?'تسجيل حركة بوابة':'New gate record'}</h2><p>{ar?'زائر أو مركبة توصيل أو تصريح إخراج أصل':'Visitor, delivery vehicle or asset gate pass'}</p></div></header>
  <select value={kind} onChange={e=>{setKind(e.target.value);setValues({})}}><option value="Visitor">{ar?'زائر':'Visitor'}</option><option value="Delivery">{ar?'توصيل / تريلا':'Delivery'}</option><option value="Pass">{ar?'تصريح إخراج أصل':'Asset gate pass'}</option></select>
  <select required value={siteId} onChange={e=>setSiteId(e.target.value)}><option value="">{ar?'اختر السكن':'Select site'}</option>{data.sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
  {kind==='Delivery'&&<select value={values.delivery_type||'Other'} onChange={e=>setValues({...values,delivery_type:e.target.value})}>{['Catering','Water Tanker','Sewage Tanker','Laundry','Materials','Other'].map(x=><option key={x}>{x}</option>)}</select>}
  {config[kind].fields.map(([name,label],i)=><input key={name} required={[0,kind==='Visitor'?2:kind==='Pass'?2:-1].includes(i)} type={name==='quantity'?'number':'text'} min={name==='quantity'?'0.001':undefined} value={values[name]||''} onChange={e=>setValues({...values,[name]:e.target.value})} placeholder={label}/>) }
  {kind==='Pass'&&<input type="datetime-local" value={values.expected_return_at||''} onChange={e=>setValues({...values,expected_return_at:e.target.value})}/>} {error&&<p className="housing-inline-error full">{error}</p>}<button className="housing-primary-button full" disabled={saving}>{ar?'حفظ السجل':'Save record'}</button>
 </form>}
 <GateList title={ar?'الزوار':'Visitors'} rows={visitors} columns={['visit_no','visitor_name','organization','entry_at','status']} ar={ar} action={x=>x.status==='Checked In'&&canManage?<button disabled={busy} onClick={()=>transition('Visitor',x.id,'Checkout')}>{ar?'تسجيل خروج':'Checkout'}</button>:null}/>
 <GateList title={ar?'مركبات وخدمات التوصيل':'Deliveries'} rows={deliveries} columns={['delivery_no','delivery_type','supplier_name','arrived_at','status']} ar={ar} action={x=>x.status==='On Site'&&canManage?<button disabled={busy} onClick={()=>transition('Delivery',x.id,'Depart')}>{ar?'مغادرة':'Depart'}</button>:null}/>
 <GateList title={ar?'تصاريح إخراج الأصول':'Asset gate passes'} rows={passes} columns={['pass_no','item_description','destination','expected_return_at','status']} ar={ar} action={x=>!canManage?null:x.status==='Draft'?<button onClick={()=>transition('Pass',x.id,'Approve')}>{ar?'اعتماد':'Approve'}</button>:x.status==='Approved'?<button onClick={()=>transition('Pass',x.id,'Checkout')}>{ar?'إخراج':'Checkout'}</button>:x.status==='Checked Out'?<button onClick={()=>transition('Pass',x.id,'Return')}>{ar?'إرجاع':'Return'}</button>:null}/>
 </div>
}
function GateList({title,rows,columns,action}){return <section className="housing-panel"><header className="housing-panel-header"><div><h2>{title}</h2><p>{rows.length} records</p></div></header><div className="housing-table-wrap"><table><thead><tr>{columns.map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{columns.map(key=><td key={key}>{key.endsWith('_at')&&row[key]?new Date(row[key]).toLocaleString():row[key]||'—'}</td>)}<td className="housing-gate-action">{action(row)}</td></tr>)}</tbody></table>{!rows.length&&<p className="housing-empty-copy">No records yet.</p>}</div></section>}
