import { useMemo, useState } from 'react'
import { AlertTriangle, BedDouble, Building2, CheckCircle2, ChevronLeft, Filter, Home, MapPin, MoreHorizontal, Plus, Search, ShieldCheck, Users, X } from 'lucide-react'
import { googleMapsUrl } from './housingCompliance.mjs'
import { useHousingLanguage } from './housingI18n.jsx'
import { HousingDetailsModal, HousingRecordModal } from './HousingRecordModal.jsx'

function Status({ value }) {
  const tone = ['Active','Available','Occupied','Acknowledged'].includes(value) ? 'green' : ['Full','Open','Renewal Due'].includes(value) ? 'amber' : 'blue'
  return <span className={`housing-status ${tone}`}><i />{value}</span>
}

function Metric({ icon: Icon, label, value, detail, tone }) {
  return <article className="housing-metric-card"><div className={`housing-icon-box ${tone}`}><Icon size={21} /></div><div className="housing-metric-copy"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>
}

export function LiveDashboard({ data, goTo }) {
  const { language, t } = useHousingLanguage()
  const totalBeds = data.rooms.reduce((sum, room) => sum + (room.beds?.length || 0), 0)
  const availableBeds = data.rooms.reduce((sum, room) => sum + (room.beds || []).filter((bed) => bed.status === 'Available').length, 0)
  const occupancy = totalBeds ? Math.round((data.assignments.length / totalBeds) * 100) : 0
  return <>
    <section className="housing-metrics-grid">
      <Metric icon={Building2} label={t('sitesCount')} value={data.sites.length} detail={t('liveData')} tone="blue" />
      <Metric icon={BedDouble} label={t('availableBeds')} value={availableBeds} detail={`${totalBeds} ${language === 'ar' ? 'إجمالي الأسرّة' : 'total beds'}`} tone="purple" />
      <Metric icon={Users} label={t('activeResidents')} value={data.assignments.length} detail={`${occupancy}% ${language === 'ar' ? 'إشغال' : 'occupancy'}`} tone="green" />
      <Metric icon={AlertTriangle} label={t('complianceAlerts')} value={data.alerts.filter((alert) => alert.status === 'Open').length} detail={`${t('warningOnly')} · ${t('areaPerWorker')}`} tone="amber" />
    </section>
    <section className="housing-dashboard-grid">
      <article className="housing-panel"><div className="housing-panel-head"><div><h2>{language === 'ar' ? 'الإشغال الفعلي حسب السكن' : 'Live occupancy by site'}</h2><p>{t('liveData')}</p></div><button className="housing-text-button" onClick={() => goTo('housing')}>{language === 'ar' ? 'عرض الكل' : 'View all'} <ChevronLeft size={16} /></button></div><div className="housing-occupancy-list">{data.sites.length === 0 ? <p>{t('noRecords')}</p> : data.sites.map((site) => { const occupied = data.assignments.filter((assignment) => assignment.site_id === site.id).length; const siteBeds = data.rooms.filter((room) => room.site_id === site.id).reduce((sum, room) => sum + (room.beds?.length || 0), 0); const percentage = siteBeds ? Math.round(occupied/siteBeds*100) : 0; return <div className="housing-occupancy-row" key={site.id}><div className="housing-building-avatar teal"><Building2 size={19} /></div><div className="housing-occupancy-info"><div><strong>{site.name}</strong><span>{site.city} · {site.code}</span></div><div className="housing-progress"><i style={{width:`${percentage}%`}} /></div></div><div className="housing-occupancy-value"><strong>{percentage}%</strong><span>{occupied}/{siteBeds}</span></div></div> })}</div></article>
      <article className="housing-panel"><div className="housing-panel-head"><div><h2>{t('complianceAlerts')}</h2><p>{t('areaPerWorker')} · {data.alerts.length} {language==='ar'?'سجل':'records'}</p></div></div><div className="housing-live-alerts compact">{data.alerts.map((alert) => <div key={alert.id}><AlertTriangle size={17} /><div><strong>{alert.title}</strong><small>{alert.site?.name} · {alert.room?.room_number}</small></div><span>{alert.status}</span></div>)}{data.alerts.length === 0 && <p>{t('noRecords')}</p>}</div></article>
    </section>
  </>
}

export function LiveHousingList({ data, onAdd }) {
  const { language, t } = useHousingLanguage()
  const [query,setQuery] = useState('')
  const [activeOnly,setActiveOnly] = useState(false)
  const [selectedSite,setSelectedSite] = useState(null)
  const sites = data.sites.filter((site) => (!activeOnly||site.status==='Active')&&`${site.name} ${site.city} ${site.code}`.toLowerCase().includes(query.toLowerCase()))
  const siteHierarchy=selectedSite?{
    buildings:(data.buildings||[]).filter((row)=>row.site_id===selectedSite.id),
    floors:(data.floors||[]).filter((row)=>row.site_id===selectedSite.id),
    apartments:(data.apartments||[]).filter((row)=>row.site_id===selectedSite.id),
    rooms:(data.rooms||[]).filter((row)=>row.site_id===selectedSite.id),
    alerts:(data.alerts||[]).filter((row)=>row.site_id===selectedSite.id&&row.status==='Open'),
  }:null
  const details=selectedSite?[{label:t('code'),value:selectedSite.code},{label:t('name'),value:selectedSite.name},{label:t('city'),value:selectedSite.city},{label:t('address'),value:selectedSite.address},{label:t('capacity'),value:selectedSite.capacity},{label:language==='ar'?'المباني':'Buildings',value:siteHierarchy.buildings.length},{label:language==='ar'?'الأدوار':'Floors',value:siteHierarchy.floors.length},{label:language==='ar'?'الشقق':'Apartments',value:siteHierarchy.apartments.length},{label:language==='ar'?'الغرف':'Rooms',value:siteHierarchy.rooms.length},{label:language==='ar'?'تنبيهات امتثال مفتوحة':'Open compliance alerts',value:siteHierarchy.alerts.length},{label:language==='ar'?'النوع':'Type',value:selectedSite.housing_type},{label:language==='ar'?'الحالة':'Status',value:selectedSite.status},{label:t('latitude'),value:selectedSite.latitude},{label:t('longitude'),value:selectedSite.longitude}]:[]
  return <><section className="housing-panel housing-list-panel"><div className="housing-toolbar"><div className="housing-search housing-search-wide"><Search size={18}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={language==='ar'?'ابحث باسم السكن أو المدينة':'Search by site or city'} /></div><button className={`housing-secondary-button ${activeOnly?'active':''}`} onClick={()=>setActiveOnly((value)=>!value)} aria-pressed={activeOnly}><Filter size={17}/>{activeOnly?(language==='ar'?'النشطة فقط':'Active only'):(language==='ar'?'تصفية':'Filter')}</button><button className="housing-primary-button" onClick={onAdd}><Plus size={18}/>{t('addHousing')}</button></div><div className="housing-cards-grid">{sites.map((site) => { const siteRooms=data.rooms.filter((room)=>room.site_id===site.id); const beds=siteRooms.flatMap((room)=>room.beds||[]); const occupied=beds.filter((bed)=>bed.status==='Occupied').length; const percentage=beds.length?Math.round(occupied/beds.length*100):0; const mapUrl=googleMapsUrl(site.latitude,site.longitude); return <article className="housing-property-card" key={site.id}><div className="housing-property-cover teal"><Building2 size={31}/><Status value={site.status}/><button onClick={()=>setSelectedSite(site)} aria-label={t('details')}><MoreHorizontal size={20}/></button></div><div className="housing-property-body"><div className="housing-property-title"><div><h3>{site.name}</h3><span>{site.code}</span></div><strong>{percentage}%<small> {language==='ar'?'إشغال':'occupied'}</small></strong></div><p><MapPin size={15}/>{site.city}{site.district?` · ${site.district}`:''}</p>{mapUrl&&<a className="housing-map-link" href={mapUrl} target="_blank" rel="noreferrer"><MapPin size={15}/>{t('openMaps')}</a>}<div className="housing-progress"><i style={{width:`${percentage}%`}}/></div><div className="housing-property-stats"><span><BedDouble size={16}/><b>{occupied}</b> {t('occupied')}</span><span><Home size={16}/><b>{beds.length-occupied}</b> {t('statusAvailable')}</span></div><footer><span>{site.latitude&&site.longitude?`${site.latitude}, ${site.longitude}`:t('location')}</span><button onClick={()=>setSelectedSite(site)}>{t('details')} <ChevronLeft size={15}/></button></footer></div></article>})}{sites.length===0&&<div className="housing-inline-empty"><Building2 size={28}/><span>{t('noRecords')}</span></div>}</div></section>{selectedSite&&<HousingDetailsModal title={selectedSite.name} rows={details} onClose={()=>setSelectedSite(null)}/>}</>
}

export function LiveDataTable({ type, data }) {
  const { language, t } = useHousingLanguage()
  const [query,setQuery] = useState('')
  const isRooms=type==='rooms'
  const rows=useMemo(()=>isRooms?data.rooms:data.assignments,[isRooms,data])
  const filtered=rows.filter((row)=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))
  return <section className="housing-panel housing-table-panel"><div className="housing-toolbar"><div className="housing-search housing-search-wide"><Search size={18}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={language==='ar'?'بحث في السجلات...':'Search records...'} /></div></div><div className="housing-table-wrap"><table><thead><tr>{isRooms?<><th>{language==='ar'?'الغرفة':'Room'}</th><th>{t('housing')}</th><th>{language==='ar'?'الدور/الشقة':'Floor/Apartment'}</th><th>{language==='ar'?'المساحة':'Area'}</th><th>{t('legalCapacity')}</th><th>{language==='ar'?'الأسرّة':'Beds'}</th><th>{language==='ar'?'الوردية':'Shift'}</th><th>{language==='ar'?'الحالة':'Status'}</th></>:<><th>{language==='ar'?'العامل':'Worker'}</th><th>{t('housing')}</th><th>{language==='ar'?'الغرفة/السرير':'Room/Bed'}</th><th>{language==='ar'?'الوردية':'Shift'}</th><th>{language==='ar'?'تاريخ التسكين':'Start date'}</th><th>{language==='ar'?'الامتثال':'Compliance'}</th></>}</tr></thead><tbody>{filtered.map((row)=>isRooms?<tr key={row.id}><td><strong>{row.room_number}</strong><small>{row.building?.name}</small></td><td>{row.site?.name}</td><td>{row.apartment?.floor?.floor_number||row.floor_number} / {row.apartment?.apartment_number||'—'}</td><td>{row.area_sqm} m²</td><td><strong>{row.legal_capacity}</strong> · {row.minimum_area_per_person_sqm} m²</td><td>{(row.beds||[]).filter((bed)=>bed.status==='Occupied').length}/{row.beds?.length||0}</td><td>{row.allowed_shift}</td><td><Status value={row.status}/></td></tr>:<tr key={row.id}><td><strong>{row.employee?.full_name}</strong><small>{row.employee?.employee_no}</small></td><td>{row.site?.name}</td><td>{row.room?.room_number} / {row.bed?.bed_number}</td><td>{row.employee?.work_shift}</td><td>{row.start_date}</td><td>{row.compliance_snapshot?.warning_issued?<span className="housing-test-warning"><AlertTriangle size={15}/>{t('warningOnly')}</span>:<span className="housing-test-ok"><CheckCircle2 size={15}/>{language==='ar'?'متوافق':'Compliant'}</span>}</td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="housing-inline-empty">{t('noRecords')}</div>}</section>
}

export function LiveAllocations({ data, goTo }) {
  const { language, t }=useHousingLanguage()
  return <><section className="housing-action-grid"><button onClick={()=>goTo('test-center')}><span className="green"><Plus size={23}/></span><div><strong>{t('newAssignment')}</strong><small>{language==='ar'?'اختبار التسكين على بيانات Supabase':'Test a live Supabase assignment'}</small></div><ChevronLeft size={20}/></button><button onClick={()=>goTo('test-center')}><span className="amber"><ShieldCheck size={23}/></span><div><strong>{t('complianceAlerts')}</strong><small>{t('warningOnly')} · {t('areaPerWorker')}</small></div><ChevronLeft size={20}/></button></section><LiveDataTable type="residents" data={data}/></>
}

export function LiveAddHousingModal({ onClose,onSave,saving }) {
  const {language,t}=useHousingLanguage()
  const [form,setForm]=useState({code:'',name:'',city:'',capacity:'0',address:'',latitude:'',longitude:'',housing_type:'Workers',ownership_type:'Rented',status:'Active'})
  const update=(key)=>(event)=>setForm((current)=>({...current,[key]:event.target.value}))
  return <div className="housing-modal-backdrop" onMouseDown={onClose}><div className="housing-modal" onMouseDown={(event)=>event.stopPropagation()}><header><div><h2>{t('addHousing')}</h2><p>{t('liveData')}</p></div><button onClick={onClose}><X size={20}/></button></header><form onSubmit={(event)=>{event.preventDefault();onSave(form)}}><div className="housing-form-grid"><label><span>{t('code')}</span><input required value={form.code} onChange={update('code')} placeholder="H-001"/></label><label><span>{t('name')}</span><input required value={form.name} onChange={update('name')}/></label><label><span>{t('city')}</span><input required value={form.city} onChange={update('city')}/></label><label><span>{t('capacity')}</span><input type="number" min="0" value={form.capacity} onChange={update('capacity')}/></label><label className="full"><span>{t('address')}</span><textarea rows="2" value={form.address} onChange={update('address')}/></label><label><span>{t('latitude')}</span><input type="number" step="any" min="-90" max="90" value={form.latitude} onChange={update('latitude')} placeholder="24.7136"/></label><label><span>{t('longitude')}</span><input type="number" step="any" min="-180" max="180" value={form.longitude} onChange={update('longitude')} placeholder="46.6753"/></label></div><footer><button type="button" className="housing-secondary-button" onClick={onClose}>{t('cancel')}</button><button className="housing-primary-button" disabled={saving}>{saving?(language==='ar'?'جاري الحفظ...':'Saving...'):t('save')}</button></footer></form></div></div>
}

export function LiveUtilities({data,onCreate,saving}){
  const{language,t}=useHousingLanguage();const[modalOpen,setModalOpen]=useState(false);const accounts=data.utilityAccounts||[];const bills=data.utilityBills||[];const due=bills.filter((bill)=>['Due','Partially Paid','Overdue'].includes(bill.status));const total=due.reduce((sum,bill)=>sum+Number(bill.total_amount||0)-Number(bill.paid_amount||0),0)
  const fields=[{key:'site_id',ar:'السكن',en:'Housing',type:'select',options:(data.sites||[]).map((site)=>({value:site.id,label:`${site.code} · ${site.name}`})),required:true},{key:'utility_type',ar:'نوع الخدمة',en:'Utility Type',type:'select',options:['Electricity','Water','Gas','Internet','Other'].map((value)=>({value,label:value})),required:true},{key:'provider_name',ar:'مقدم الخدمة',en:'Provider',required:true},{key:'account_number',ar:'رقم الحساب',en:'Account Number',required:true},{key:'meter_number',ar:'رقم العداد',en:'Meter Number'},{key:'integration_mode',ar:'طريقة الربط',en:'Integration',type:'select',options:['Manual','Excel','PDF','API','Open Banking'].map((value)=>({value,label:value})),required:true}]
  const save=async(input)=>{await onCreate('housing_utility_accounts',input);setModalOpen(false)}
  return <><section className="housing-metrics-grid"><Metric icon={Building2} label={language==='ar'?'حسابات الخدمات':'Utility accounts'} value={accounts.length} detail={t('liveData')} tone="blue"/><Metric icon={AlertTriangle} label={language==='ar'?'فواتير مستحقة':'Bills due'} value={due.length} detail={`${total.toLocaleString()} SAR`} tone="amber"/></section><section className="housing-panel housing-table-panel"><div className="housing-panel-head"><div><h2>{language==='ar'?'الكهرباء والمياه':'Electricity & Water'}</h2><p>{t('liveData')}</p></div><button className="housing-primary-button" onClick={()=>setModalOpen(true)}><Plus size={17}/>{language==='ar'?'إضافة حساب':'Add Account'}</button></div><div className="housing-table-wrap"><table><thead><tr><th>{language==='ar'?'الخدمة':'Utility'}</th><th>{language==='ar'?'المزود':'Provider'}</th><th>{language==='ar'?'رقم الحساب':'Account No.'}</th><th>{language==='ar'?'طريقة الربط':'Integration'}</th><th>{language==='ar'?'آخر مزامنة':'Last Sync'}</th><th>{language==='ar'?'الحالة':'Status'}</th></tr></thead><tbody>{accounts.map((account)=><tr key={account.id}><td><strong>{account.utility_type}</strong></td><td>{account.provider_name}</td><td>{account.account_number}</td><td>{account.integration_mode}</td><td>{account.last_sync_at||'—'}</td><td><Status value={account.status}/></td></tr>)}</tbody></table></div>{accounts.length===0&&<div className="housing-inline-empty">{t('noRecords')}</div>}</section>{modalOpen&&<HousingRecordModal titleAr="إضافة حساب خدمة" titleEn="Add Utility Account" fields={fields} initial={{utility_type:'Electricity',integration_mode:'Manual'}} onClose={()=>setModalOpen(false)} onSave={save} saving={saving}/>}</>
}
