import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { after, before, describe, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const COMPANY_A = "10000000-0000-4000-8000-000000000001";
const COMPANY_B = "10000000-0000-4000-8000-000000000002";
const AGENCY_A = "20000000-0000-4000-8000-000000000001";
const AGENCY_B = "20000000-0000-4000-8000-000000000002";
const COMPANY_ADMIN_A = "30000000-0000-4000-8000-000000000001";
const COMPANY_ADMIN_B = "30000000-0000-4000-8000-000000000002";
const AGENCY_USER_A = "30000000-0000-4000-8000-000000000003";
const AGENCY_USER_B = "30000000-0000-4000-8000-000000000004";

const fixtureSql = `
create schema auth;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.agencies (
  id uuid primary key, name text not null, status text not null
);
create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid, company_id uuid, agency_id uuid,
  email text, role text not null, status text not null,
  is_active boolean not null default true
);
create table public.agency_company_user_access (
  user_id bigint not null, company_id uuid not null, agency_id uuid not null,
  status text not null,
  can_view_requests boolean not null default true,
  can_upload_candidates boolean not null default true,
  can_update_candidates boolean not null default true,
  primary key (user_id, company_id, agency_id)
);
create table public.requests (
  id bigint generated by default as identity primary key,
  company_id uuid not null, request_no text
);
create table public.request_lines (
  id uuid default gen_random_uuid() primary key,
  company_id uuid not null, request_no text
);
create table public.visa_batches (
  id uuid default gen_random_uuid() primary key,
  company_id uuid not null, visa_no text
);
create table public.visa_batch_lines (
  id bigint generated by default as identity primary key,
  company_id uuid not null, visa_no text
);
create table public.visa_allocations (
  id bigint generated by default as identity primary key,
  company_id uuid not null, visa_no text
);
create table public.candidates (
  id uuid default gen_random_uuid() primary key,
  company_id uuid not null, agency text, candidate_name text not null
);

create function public.current_app_user_company_id()
returns uuid language sql stable security definer set search_path = '' as $$
  select company_id from public.users
  where auth_user_id = auth.uid() and status = 'Active' and is_active is true
$$;
create function public.current_app_user_role()
returns text language sql stable security definer set search_path = '' as $$
  select role from public.users
  where auth_user_id = auth.uid() and status = 'Active' and is_active is true
$$;
create function public.current_app_user_has_role(allowed_roles text[])
returns boolean language sql stable security definer set search_path = '' as $$
  select public.current_app_user_role() = any(allowed_roles)
$$;
create function public.is_current_platform_user()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.users
    where auth_user_id = auth.uid() and status = 'Active' and is_active is true
      and role in ('Platform Owner','Platform Accounts User','Platform Support User')
  )
$$;

grant usage on schema public, auth to authenticated;
grant execute on function auth.uid() to authenticated;
grant execute on function public.current_app_user_company_id() to authenticated;
grant execute on function public.current_app_user_role() to authenticated;
grant execute on function public.current_app_user_has_role(text[]) to authenticated;
grant execute on function public.is_current_platform_user() to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
`;

let db;
let migration;

async function asAuthenticated(authUserId, callback) {
  await db.exec("reset role");
  await db.query("select set_config('request.jwt.claim.sub', $1::text, false)", [authUserId]);
  await db.exec("set role authenticated");
  try {
    return await callback();
  } finally {
    await db.exec("reset role");
  }
}

describe("operational tenant RLS on temporary PostgreSQL", () => {
  before(async () => {
    db = new PGlite();
    migration = await readFile(
      new URL("../supabase/migrations/20260801000100_harden_operational_tenant_rls.sql", import.meta.url),
      "utf8"
    );
    await db.exec(fixtureSql);
    await db.exec(migration);

    await db.query(
      `insert into public.agencies(id,name,status) values
        ($1,'Agency A','Active'),($2,'Agency B','Active')`,
      [AGENCY_A, AGENCY_B]
    );
    await db.query(
      `insert into public.users(auth_user_id,company_id,agency_id,email,role,status,is_active) values
        ($1,$5,null,'admin-a@example.test','Company Admin','Active',true),
        ($2,$6,null,'admin-b@example.test','Company Admin','Active',true),
        ($3,null,$7,'agency-a@example.test','Agency','Active',true),
        ($4,null,$8,'agency-b@example.test','Agency','Active',true)`,
      [COMPANY_ADMIN_A, COMPANY_ADMIN_B, AGENCY_USER_A, AGENCY_USER_B, COMPANY_A, COMPANY_B, AGENCY_A, AGENCY_B]
    );
    await db.query(
      `insert into public.agency_company_user_access(
        user_id,company_id,agency_id,status,
        can_view_requests,can_upload_candidates,can_update_candidates
      )
      select id,$1::uuid,$2::uuid,'Active',true,true,true from public.users where auth_user_id=$3::uuid
      union all
      select id,$4::uuid,$5::uuid,'Active',true,true,true from public.users where auth_user_id=$6::uuid`,
      [COMPANY_A, AGENCY_A, AGENCY_USER_A, COMPANY_B, AGENCY_B, AGENCY_USER_B]
    );
    await db.query("insert into public.requests(company_id,request_no) values ($1,'A-1'),($2,'B-1')", [COMPANY_A, COMPANY_B]);
    await db.query("insert into public.request_lines(company_id,request_no) values ($1,'A-1'),($2,'B-1')", [COMPANY_A, COMPANY_B]);
    await db.query("insert into public.visa_batches(company_id,visa_no) values ($1,'VA'),($2,'VB')", [COMPANY_A, COMPANY_B]);
    await db.query("insert into public.visa_batch_lines(company_id,visa_no) values ($1,'VA'),($2,'VB')", [COMPANY_A, COMPANY_B]);
    await db.query("insert into public.visa_allocations(company_id,visa_no) values ($1,'VA'),($2,'VB')", [COMPANY_A, COMPANY_B]);
    await db.query(
      `insert into public.candidates(company_id,agency,candidate_name) values
        ($1,'Agency A','Candidate A'),($1,'Agency B','Candidate B in A'),($2,'Agency B','Candidate B')`,
      [COMPANY_A, COMPANY_B]
    );
  });

  after(async () => db?.close());

  test("enables RLS on every operational table in scope", async () => {
    const result = await db.query(`
      select relname, relrowsecurity from pg_class
      where oid in (
        'public.users'::regclass,'public.requests'::regclass,
        'public.request_lines'::regclass,'public.visa_batches'::regclass,
        'public.visa_batch_lines'::regclass,'public.visa_allocations'::regclass,
        'public.candidates'::regclass
      )
    `);
    assert.equal(result.rows.length, 7);
    assert.ok(result.rows.every((row) => row.relrowsecurity === true));
  });

  test("agency sees only itself and its own candidates, not internal demand or visa inventory", async () => {
    await asAuthenticated(AGENCY_USER_A, async () => {
      const users = await db.query("select auth_user_id from public.users order by auth_user_id");
      assert.deepEqual(users.rows.map((row) => row.auth_user_id), [AGENCY_USER_A]);
      for (const table of ["requests", "request_lines", "visa_batches", "visa_batch_lines", "visa_allocations"]) {
        const result = await db.query(`select count(*)::int as count from public.${table}`);
        assert.equal(result.rows[0].count, 0, table);
      }
      const candidates = await db.query("select candidate_name from public.candidates order by candidate_name");
      assert.deepEqual(candidates.rows, [{ candidate_name: "Candidate A" }]);
    });
  });

  test("agency candidate writes are permission and identity scoped", async () => {
    await asAuthenticated(AGENCY_USER_A, async () => {
      await db.query(
        "insert into public.candidates(company_id,agency,candidate_name) values ($1,'Agency A','Agency Upload')",
        [COMPANY_A]
      );
      await assert.rejects(
        db.query(
          "insert into public.candidates(company_id,agency,candidate_name) values ($1,'Agency B','Cross Agency')",
          [COMPANY_A]
        ),
        /row-level security policy/
      );
      const update = await db.query("update public.candidates set candidate_name='Blocked' where agency='Agency B'");
      assert.equal(update.affectedRows, 0);
    });
  });

  test("Company Admin retains same-tenant operations and cannot read tenant B", async () => {
    await asAuthenticated(COMPANY_ADMIN_A, async () => {
      const requests = await db.query("select request_no from public.requests order by request_no");
      assert.deepEqual(requests.rows, [{ request_no: "A-1" }]);
      await db.query("insert into public.requests(company_id,request_no) values ($1,'A-2')", [COMPANY_A]);
      await assert.rejects(
        db.query("insert into public.requests(company_id,request_no) values ($1,'B-X')", [COMPANY_B]),
        /row-level security policy/
      );
      const visas = await db.query("select visa_no from public.visa_batches");
      assert.deepEqual(visas.rows, [{ visa_no: "VA" }]);
    });
  });
});
