import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { after, before, describe, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const COMPANY_A = "10000000-0000-4000-8000-000000000001";
const COMPANY_B = "10000000-0000-4000-8000-000000000002";
const AGENCY_A = "20000000-0000-4000-8000-000000000001";
const AGENCY_B = "20000000-0000-4000-8000-000000000002";
const ADMIN_A = "30000000-0000-4000-8000-000000000001";
const OPS_A = "30000000-0000-4000-8000-000000000002";
const RECRUITER_A = "30000000-0000-4000-8000-000000000003";
const AGENCY_USER_A = "30000000-0000-4000-8000-000000000004";

const fixtureSql = `
create schema auth;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.companies (id uuid primary key, name text not null);
create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  company_id uuid,
  agency_id uuid,
  role text not null,
  status text not null default 'Active',
  is_active boolean not null default true
);
create table public.agencies (id uuid primary key, name text not null, status text not null);
create table public.agency_company_user_access (
  user_id bigint not null,
  company_id uuid not null,
  agency_id uuid not null,
  status text not null,
  can_view_interviews boolean not null default true,
  can_update_candidates boolean not null default true
);
create table public.employees (
  id uuid default gen_random_uuid() primary key,
  company_id uuid,
  employee_name text
);
create table public.interviews (
  id uuid default gen_random_uuid() primary key,
  company_id uuid,
  agency_id uuid,
  candidate_name text
);
create table public.mobilizations (
  id uuid default gen_random_uuid() primary key,
  company_id uuid,
  candidate_name text
);
create table public.agency_client_access (
  id uuid default gen_random_uuid() primary key,
  company_id uuid,
  agency_id uuid
);

create function public.current_app_user_company_id()
returns uuid language sql stable security definer set search_path = '' as $$
  select company_id from public.users
  where auth_user_id = auth.uid() and status = 'Active' and is_active is true
$$;
create function public.current_app_user_role()
returns text language sql stable security definer set search_path = '' as $$
  select role from public.users
  where auth_user_id = auth.uid() and status = 'Active' and is_active is true
$$;
create function public.current_app_user_has_role(allowed_roles text[])
returns boolean language sql stable security definer set search_path = '' as $$
  select public.current_app_user_role() = any(allowed_roles)
$$;
create function public.is_current_platform_user()
returns boolean language sql stable security definer set search_path = '' as $$ select false $$;
create function public.agency_recruitment_access_allowed(
  p_company_id uuid, p_agency_id uuid, p_operation text default 'select'
) returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1
    from public.users app_user
    join public.agency_company_user_access access_row
      on access_row.user_id = app_user.id
     and access_row.company_id = p_company_id
     and access_row.agency_id = p_agency_id
     and access_row.status = 'Active'
    where app_user.auth_user_id = auth.uid()
      and app_user.agency_id = p_agency_id
      and app_user.role = 'Agency'
      and app_user.status = 'Active'
      and app_user.is_active is true
      and case lower(coalesce(p_operation, 'select'))
        when 'view_interviews' then access_row.can_view_interviews
        when 'update' then access_row.can_update_candidates
        else true
      end
  )
$$;

grant usage on schema public, auth to anon, authenticated, service_role;
grant execute on function auth.uid() to authenticated;
grant execute on function public.current_app_user_company_id() to authenticated;
grant execute on function public.current_app_user_role() to authenticated;
grant execute on function public.current_app_user_has_role(text[]) to authenticated;
grant execute on function public.is_current_platform_user() to authenticated;
grant execute on function public.agency_recruitment_access_allowed(uuid,uuid,text) to authenticated;
grant all on all tables in schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
`;

let db;

async function asRole(role, authUserId, callback) {
  await db.exec("reset role");
  await db.query("select set_config('request.jwt.claim.sub', $1::text, false)", [authUserId ?? ""]);
  await db.exec(`set role ${role}`);
  try {
    return await callback();
  } finally {
    await db.exec("reset role");
  }
}

describe("security remediation RLS on temporary PostgreSQL", () => {
  before(async () => {
    db = new PGlite();
    await db.exec(fixtureSql);
    await db.query("insert into public.companies values ($1,'A'),($2,'B')", [COMPANY_A, COMPANY_B]);
    await db.query("insert into public.agencies values ($1,'Agency A','Active'),($2,'Agency B','Active')", [AGENCY_A, AGENCY_B]);
    await db.query(
      `insert into public.users(auth_user_id,company_id,agency_id,role) values
       ($1,$5,null,'Company Admin'),
       ($2,$5,null,'Operations Manager'),
       ($3,$5,null,'Recruitment Officer'),
       ($4,null,$6,'Agency')`,
      [ADMIN_A, OPS_A, RECRUITER_A, AGENCY_USER_A, COMPANY_A, AGENCY_A]
    );
    await db.query(
      `insert into public.agency_company_user_access(user_id,company_id,agency_id,status)
       select id,$1,$2,'Active' from public.users where auth_user_id=$3`,
      [COMPANY_A, AGENCY_A, AGENCY_USER_A]
    );
    for (const table of ["employees", "mobilizations"]) {
      await db.query(`insert into public.${table}(company_id,candidate_name) values ($1,'A'),($2,'B')`.replace("candidate_name", table === "employees" ? "employee_name" : "candidate_name"), [COMPANY_A, COMPANY_B]);
    }
    await db.query(
      "insert into public.interviews(company_id,agency_id,candidate_name) values ($1,$2,'A'),($3,$4,'B')",
      [COMPANY_A, AGENCY_A, COMPANY_B, AGENCY_B]
    );

    const migration = await readFile(
      new URL("../supabase/migrations/20260817000700_security_rls_remediation.sql", import.meta.url),
      "utf8"
    );
    await db.exec(migration);
  });

  after(async () => db?.close());

  test("enables RLS with exactly the reviewed policy set", async () => {
    const rls = await db.query(`
      select relname, relrowsecurity from pg_class
      where oid in ('public.employees'::regclass,'public.interviews'::regclass,
        'public.mobilizations'::regclass,'public.agency_client_access'::regclass)
      order by relname
    `);
    assert.equal(rls.rows.length, 4);
    assert.ok(rls.rows.every((row) => row.relrowsecurity));
    const policies = await db.query(`
      select tablename, count(*)::int as count from pg_policies
      where schemaname='public' and tablename = any(array[
        'employees','interviews','mobilizations','agency_client_access'
      ]) group by tablename order by tablename
    `);
    assert.deepEqual(policies.rows, [
      { tablename: "employees", count: 4 },
      { tablename: "interviews", count: 4 },
      { tablename: "mobilizations", count: 4 }
    ]);
  });

  test("Company Admin is tenant-scoped for reads and writes", async () => {
    await asRole("authenticated", ADMIN_A, async () => {
      for (const table of ["employees", "interviews", "mobilizations"]) {
        const visible = await db.query(`select company_id from public.${table}`);
        assert.deepEqual(visible.rows, [{ company_id: COMPANY_A }], table);
      }
      await db.query("insert into public.employees(company_id,employee_name) values ($1,'A2')", [COMPANY_A]);
      await assert.rejects(
        db.query("insert into public.employees(company_id,employee_name) values ($1,'B-X')", [COMPANY_B]),
        /row-level security policy/
      );
      const changed = await db.query("update public.mobilizations set candidate_name='blocked' where company_id=$1", [COMPANY_B]);
      assert.equal(changed.affectedRows, 0);
    });
  });

  test("operational roles retain only their legitimate workflows", async () => {
    await asRole("authenticated", OPS_A, async () => {
      await db.query("insert into public.employees(company_id,employee_name) values ($1,'Ops')", [COMPANY_A]);
      await db.query("insert into public.mobilizations(company_id,candidate_name) values ($1,'Ops')", [COMPANY_A]);
      await assert.rejects(
        db.query("insert into public.interviews(company_id,candidate_name) values ($1,'Ops')", [COMPANY_A]),
        /row-level security policy/
      );
    });
    await asRole("authenticated", RECRUITER_A, async () => {
      await db.query("insert into public.interviews(company_id,candidate_name) values ($1,'Recruiter')", [COMPANY_A]);
      await db.query("insert into public.mobilizations(company_id,candidate_name) values ($1,'Recruiter')", [COMPANY_A]);
      await assert.rejects(
        db.query("insert into public.employees(company_id,employee_name) values ($1,'Recruiter')", [COMPANY_A]),
        /row-level security policy/
      );
    });
  });

  test("Agency sees only owned interviews and no employee or mobilization data", async () => {
    await asRole("authenticated", AGENCY_USER_A, async () => {
      assert.equal((await db.query("select count(*)::int count from public.employees")).rows[0].count, 0);
      assert.equal((await db.query("select count(*)::int count from public.mobilizations")).rows[0].count, 0);
      const interviews = await db.query("select company_id, agency_id from public.interviews");
      assert.deepEqual(interviews.rows, [{ company_id: COMPANY_A, agency_id: AGENCY_A }]);
      await db.query(
        "insert into public.interviews(company_id,agency_id,candidate_name) values ($1,$2,'Agency A')",
        [COMPANY_A, AGENCY_A]
      );
      await assert.rejects(
        db.query(
          "insert into public.interviews(company_id,agency_id,candidate_name) values ($1,$2,'Cross tenant')",
          [COMPANY_B, AGENCY_B]
        ),
        /row-level security policy/
      );
      await assert.rejects(
        db.query("select * from public.agency_client_access"),
        /permission denied/
      );
    });
  });

  test("anon is denied and Service Role still bypasses RLS", async () => {
    await asRole("anon", null, async () => {
      await assert.rejects(db.query("select * from public.employees"), /permission denied/);
      await assert.rejects(db.query("select * from public.agency_client_access"), /permission denied/);
    });
    await asRole("service_role", null, async () => {
      const visible = await db.query("select count(*)::int count from public.employees");
      assert.ok(visible.rows[0].count >= 2);
      await db.query("insert into public.employees(company_id,employee_name) values ($1,'Service')", [COMPANY_B]);
      await db.query("insert into public.agency_client_access(company_id,agency_id) values ($1,$2)", [COMPANY_B, AGENCY_B]);
    });
  });
});
