-- Sprint 1: protected authorization delivery and agency decision workflow.
-- This migration is intentionally environment-agnostic and does not contain data or secrets.

alter table public.visa_authorizations
  add column if not exists agency_id uuid references public.agencies(id),
  add column if not exists agency_status text not null default 'New',
  add column if not exists sent_at timestamptz,
  add column if not exists sent_by uuid,
  add column if not exists viewed_at timestamptz,
  add column if not exists viewed_by uuid,
  add column if not exists acknowledged_at timestamptz,
  add column if not exists acknowledged_by uuid,
  add column if not exists decision_at timestamptz,
  add column if not exists decision_by uuid,
  add column if not exists response_reason text,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by uuid,
  add column if not exists send_count integer not null default 0;

alter table public.visa_authorizations
  drop constraint if exists visa_authorizations_agency_status_check;

alter table public.visa_authorizations
  add constraint visa_authorizations_agency_status_check
  check (agency_status in ('New', 'Viewed', 'Acknowledged', 'Accepted', 'Rejected'));

alter table public.visa_authorizations
  drop constraint if exists visa_authorizations_send_count_check;

alter table public.visa_authorizations
  add constraint visa_authorizations_send_count_check
  check (send_count >= 0);

create index if not exists idx_visa_authorizations_company_agency
  on public.visa_authorizations(company_id, agency_id);

create index if not exists idx_visa_authorizations_agency_status
  on public.visa_authorizations(agency_id, agency_status);

create table if not exists public.authorization_events (
  id bigint generated by default as identity primary key,
  authorization_id uuid not null references public.visa_authorizations(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  agency_id uuid references public.agencies(id),
  event_type text not null
    check (event_type in ('Created', 'Sent', 'Viewed', 'Acknowledged', 'Accepted', 'Rejected', 'Cancelled')),
  actor_user_id bigint references public.users(id),
  actor_auth_user_id uuid,
  actor_name text not null,
  actor_email text,
  actor_role text not null,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_authorization_events_timeline
  on public.authorization_events(authorization_id, created_at, id);

create index if not exists idx_authorization_events_tenant
  on public.authorization_events(company_id, agency_id);

-- Backfill legacy name-only assignments only when the company has exactly one
-- active agency with that normalized name. Ambiguous rows stay unassigned and
-- must be reviewed instead of being exposed to the wrong agency.
with unambiguous_agency_matches as (
  select
    authorization.id as authorization_id,
    (array_agg(distinct access.agency_id))[1] as agency_id
  from public.visa_authorizations authorization
  join public.company_agency_access access
    on access.company_id = authorization.company_id
   and coalesce(access.status, 'Active') = 'Active'
  join public.agencies agency
    on agency.id = access.agency_id
   and lower(trim(agency.name)) = lower(trim(authorization.agency))
  where authorization.agency_id is null
  group by authorization.id
  having count(distinct access.agency_id) = 1
)
update public.visa_authorizations authorization
set agency_id = matched.agency_id
from unambiguous_agency_matches matched
where authorization.id = matched.authorization_id;

insert into public.authorization_events (
  authorization_id,
  company_id,
  agency_id,
  event_type,
  actor_name,
  actor_email,
  actor_role,
  created_at,
  metadata
)
select
  authorization.id,
  authorization.company_id,
  authorization.agency_id,
  'Created',
  coalesce(nullif(authorization.created_by_name, ''), 'Legacy Import'),
  nullif(authorization.created_by_email, ''),
  coalesce(nullif(authorization.created_by_role, ''), 'System'),
  coalesce(authorization.created_at, now()),
  jsonb_build_object('backfilled', true)
from public.visa_authorizations authorization
where authorization.company_id is not null
  and not exists (
    select 1
    from public.authorization_events event
    where event.authorization_id = authorization.id
      and event.event_type = 'Created'
  );

alter table public.notification_events
  add column if not exists recipient_role text;

create index if not exists idx_notification_events_authorization_recipient
  on public.notification_events(company_id, agency_id, recipient_role, related_id)
  where related_table = 'visa_authorizations';

alter table public.visa_authorizations enable row level security;
alter table public.authorization_events enable row level security;

drop policy if exists visa_authorizations_select_tenant_policy
  on public.visa_authorizations;

create policy visa_authorizations_select_prelaunch_workflow
  on public.visa_authorizations
  for select
  to authenticated
  using (
    public.is_current_platform_user()
    or (
      public.current_app_user_role() <> 'Agency'
      and company_id = public.current_app_user_company_id()
    )
    or (
      public.current_app_user_role() = 'Agency'
      and agency_id = public.current_app_user_agency_id()
      and exists (
        select 1
        from public.agency_company_user_access access
        where access.user_id = public.current_app_user_id()
          and access.company_id = visa_authorizations.company_id
          and access.agency_id = visa_authorizations.agency_id
          and coalesce(access.status, 'Active') = 'Active'
      )
    )
  );

create policy authorization_events_select_prelaunch_workflow
  on public.authorization_events
  for select
  to authenticated
  using (
    public.is_current_platform_user()
    or (
      public.current_app_user_role() <> 'Agency'
      and company_id = public.current_app_user_company_id()
    )
    or (
      public.current_app_user_role() = 'Agency'
      and agency_id = public.current_app_user_agency_id()
      and exists (
        select 1
        from public.agency_company_user_access access
        where access.user_id = public.current_app_user_id()
          and access.company_id = authorization_events.company_id
          and access.agency_id = authorization_events.agency_id
          and coalesce(access.status, 'Active') = 'Active'
      )
    )
  );

-- All protected mutations are performed by authorization-workflow after JWT,
-- role, tenant, agency membership, and state-transition checks.
revoke insert, update, delete on table public.visa_authorizations from anon, authenticated;
revoke all on table public.authorization_events from anon, authenticated;
grant select on table public.visa_authorizations to authenticated;
grant select on table public.authorization_events to authenticated;
grant usage, select on sequence public.authorization_events_id_seq to service_role;

comment on table public.authorization_events is
  'Immutable server-written Authorization timeline. Browser clients have SELECT only.';

comment on column public.visa_authorizations.company_id is
  'Server-controlled tenant identifier. The Authorization Edge Function derives it from the authenticated actor.';
